/* Generated by re2c 0.10.2 on Sun May  7 20:28:55 2006 */
#line 1 "pdo_user_sql_tokenizer.re"
#include "php.h"
#include "php_pdo_user_sql.h"

static void php_pdo_user_unquote(php_pdo_user_sql_token *token)
{
	char *out = emalloc(token->token_len + 1), *p = out;
	int i;

	token->token_len--;
	for(i = 1; i < token->token_len; i++) {
		switch (token->token[i]) {
			case '\\':
				if ((i + 1) >= token->token_len) {
					/* EOL */
					*(p++) = '\\';
					goto done;
				}
				switch (token->token[++i]) {
					case 'r':	*(p++) = '\r';		goto next_iter;
					case 'n':	*(p++) = '\n';		goto next_iter;
					case 't':	*(p++) = '\t';		goto next_iter;
					case '\\':	*(p++) = '\\';		goto next_iter;
					case 'x':
					{
						unsigned char val = 0;

						if (++i >= token->token_len) {
							*(p++) = 'x';
							goto done;
						}
						if (token->token[i] >= '0' && token->token[i] <= '9') {
							val = token->token[i] - '0';
						} else if (token->token[i] >= 'A' && token->token[i] <= 'F') {
							val = 10 + token->token[i] - 'A';
						} else if (token->token[i] >= 'a' && token->token[i] <= 'f') {
							val = 10 + token->token[i] - 'a';
						} else {
							*(p++) = 'x';
							i--;
							goto next_iter;
						}
						if (++i >= token->token_len) {
							*(p++) = val;
							goto done;
						}
						if (token->token[i] >= '0' && token->token[i] <= '9') {
							val <<= 4;
							val |= token->token[i] - '0';
						} else if (token->token[i] >= 'A' && token->token[i] <= 'F') {
							val <<= 4;
							val |= 10 + token->token[i] - 'A';
						} else if (token->token[i] >= 'a' && token->token[i] <= 'f') {
							val <<= 4;
							val |= 10 + token->token[i] - 'a';
						} else {
							*(p++) = val;
							i--;
							goto next_iter;
						}
						*(p++) = val;
						goto next_iter;
					}
					default: /* local-quote, octal, and non-escaped */
					{
						unsigned char val = 0;

						if (token->token[i] >= '0' && token->token[i] <= '7') {
							val = token->token[i] - '0';
						} else {
							*(p++) = token->token[i];
							goto next_iter;
						}
						if (++i >= token->token_len) {
							*(p++) = val;
							goto done;
						}
						if (token->token[i] >= '0' && token->token[i] <= '7') {
							val <<= 3;
							val |= token->token[i] - '0';
						} else {
							*(p++) = val;
							i--;
							goto next_iter;
						}
						if (val > 0x1F) {
							*(p++) = val;
							goto next_iter;
						}
						if (++i >= token->token_len) {
							*(p++) = val;
							goto done;
						}
						if (token->token[i] >= '0' && token->token[i] <= '7') {
							val <<= 3;
							val |= token->token[i] - '0';
						} else {
							*(p++) = val;
							i--;
							goto next_iter;
						}
						*(p++) = val;
						goto next_iter;
					}
				}
			default:
				*(p++) = token->token[i];
		}
next_iter:
		continue; /* avoids warning */
	}

done:
	token->token = out;
	token->token_len = p - out;
	*p = 0;

	token->freeme = 1;
}

#define RET(num) { token->token_len = t->start - token->token; token->id = num; return (num); }
#define RET_UNESC(num) { token->token_len = t->start - token->token; token->id = num; php_pdo_user_unquote(token); return (num); }

#define YYCTYPE		char
#define YYCURSOR	(t->start)
#define YYLIMIT		(t->end)
#define YYFILL(n)
#define YYMARKER	marker

int php_pdo_user_sql_get_token(php_pdo_user_sql_tokenizer *t, php_pdo_user_sql_token *token)
{
	token->freeme = 0;
	token->token = t->start;
	char *marker = t->start;

{
	static unsigned char yybm[] = {
		  0,   7,   7,   7,   7,   7,   7,   7, 
		  7,  15,  15,   7,   7,  15,   7,   7, 
		  7,   7,   7,   7,   7,   7,   7,   7, 
		  7,   7,   7,   7,   7,   7,   7,   7, 
		 15,   7,   5,   7,   7,   7,   7,   3, 
		  7,   7,   7,   7,   7,   7,   7,   7, 
		119, 119, 119, 119, 119, 119, 119, 119, 
		119, 119,   7,   7,   7,   7,   7,   7, 
		  7, 103, 103, 103, 103, 103, 103,  39, 
		 39,  39,  39,  39,  39,  39,  39,  39, 
		 39,  39,  39,  39,  39,  39,  39,  39, 
		 39,  39,  39,   7,   0,   7,   7,  39, 
		  6, 103, 103, 103, 103, 103, 103,  39, 
		 39,  39,  39,  39,  39,  39,  39,  39, 
		 39,  39,  39, 175,  39,  39,  39,  39, 
		 39,  39,  39,   7,   7,   7,   7,   7, 
		 39,  39,  39,  39,  39,  39,  39,  39, 
		 39,  39,  39,  39,  39,  39,  39,  39, 
		 39,  39,  39,  39,  39,  39,  39,  39, 
		 39,  39,  39,  39,  39,  39,  39,  39, 
		 39,  39,  39,  39,  39,  39,  39,  39, 
		 39,  39,  39,  39,  39,  39,  39,  39, 
		 39,  39,  39,  39,  39,  39,  39,  39, 
		 39,  39,  39,  39,  39,  39,  39,  39, 
		 39,  39,  39,  39,  39,  39,  39,  39, 
		 39,  39,  39,  39,  39,  39,  39,  39, 
		 39,  39,  39,  39,  39,  39,  39,  39, 
		 39,  39,  39,  39,  39,  39,  39,  39, 
		 39,  39,  39,  39,  39,  39,  39,  39, 
		 39,  39,  39,  39,  39,  39,  39,  39, 
		 39,  39,  39,  39,  39,  39,  39,  39, 
		 39,  39,  39,  39,  39,  39,  39,  39, 
	};

#line 174 "<stdout>"
	{
		YYCTYPE yych;

		if((YYLIMIT - YYCURSOR) < 15) YYFILL(15);
		yych = *YYCURSOR;
		switch(yych){
		case 0x00:	goto yy64;
		case 0x01:
		case 0x02:
		case 0x03:
		case 0x04:
		case 0x05:
		case 0x06:
		case 0x07:
		case 0x08:
		case 0x0B:
		case 0x0C:
		case 0x0E:
		case 0x0F:
		case 0x10:
		case 0x11:
		case 0x12:
		case 0x13:
		case 0x14:
		case 0x15:
		case 0x16:
		case 0x17:
		case 0x18:
		case 0x19:
		case 0x1A:
		case 0x1B:
		case 0x1C:
		case 0x1D:
		case 0x1E:
		case 0x1F:
		case '#':
		case '$':
		case '&':
		case '.':
		case ':':
		case '?':
		case '@':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '{':
		case '|':
		case '}':
		case '~':
		case 0x7F:	goto yy2;
		case 0x09:
		case 0x0A:
		case 0x0D:
		case ' ':	goto yy56;
		case '!':	goto yy26;
		case '"':	goto yy52;
		case '%':	goto yy38;
		case '\'':	goto yy54;
		case '(':	goto yy40;
		case ')':	goto yy42;
		case '*':	goto yy34;
		case '+':	goto yy30;
		case ',':	goto yy44;
		case '-':	goto yy32;
		case '/':	goto yy36;
		case '0':	goto yy58;
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':	goto yy60;
		case ';':	goto yy48;
		case '<':	goto yy27;
		case '=':	goto yy46;
		case '>':	goto yy28;
		case 'A':
		case 'a':	goto yy12;
		case 'B':
		case 'b':	goto yy23;
		case 'C':
		case 'c':	goto yy10;
		case 'D':
		case 'd':	goto yy9;
		case 'E':
		case 'e':	goto yy25;
		case 'F':
		case 'f':	goto yy18;
		case 'G':
		case 'g':	goto yy13;
		case 'H':
		case 'h':	goto yy21;
		case 'I':
		case 'i':	goto yy7;
		case 'K':
		case 'k':	goto yy16;
		case 'L':
		case 'l':	goto yy20;
		case 'N':
		case 'n':	goto yy17;
		case 'O':
		case 'o':	goto yy22;
		case 'P':
		case 'p':	goto yy24;
		case 'R':
		case 'r':	goto yy11;
		case 'S':	goto yy3;
		case 'T':
		case 't':	goto yy14;
		case 'U':
		case 'u':	goto yy8;
		case 'V':
		case 'v':	goto yy15;
		case 'W':
		case 'w':	goto yy19;
		case 'X':
		case 'x':	goto yy29;
		case '`':	goto yy50;
		case 's':	goto yy5;
		default:	goto yy62;
		}
yy2:
		YYCURSOR = YYMARKER;
		goto yy59;
yy3:
		++YYCURSOR;
		if((yych = *YYCURSOR) == 'E') goto yy343;
		if(yych == 'e') goto yy343;
		goto yy63;
yy4:
#line 236 "pdo_user_sql_tokenizer.re"
		{ RET(PU_LABEL); }
#line 311 "<stdout>"
yy5:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 128) {
			goto yy344;
		}
		if(yych <= '^') {
			if(yych <= '@') {
				if(yych <= '/') goto yy57;
				if(yych <= '9') goto yy62;
				goto yy57;
			} else {
				if(yych == 'E') goto yy343;
				if(yych <= 'Z') goto yy62;
				goto yy57;
			}
		} else {
			if(yych <= 'd') {
				if(yych == '`') goto yy57;
				goto yy62;
			} else {
				if(yych <= 'e') goto yy343;
				if(yych <= 'z') goto yy62;
				if(yych <= 0x7F) goto yy57;
				goto yy62;
			}
		}
yy6:
#line 233 "pdo_user_sql_tokenizer.re"
		{ RET(PU_WHITESPACE); }
#line 341 "<stdout>"
yy7:
		yych = *++YYCURSOR;
		if(yych <= 'N') {
			if(yych == 'D') goto yy323;
			if(yych <= 'M') goto yy63;
			goto yy324;
		} else {
			if(yych <= 'd') {
				if(yych <= 'c') goto yy63;
				goto yy323;
			} else {
				if(yych == 'n') goto yy324;
				goto yy63;
			}
		}
yy8:
		yych = *++YYCURSOR;
		if(yych <= 'P') {
			if(yych == 'N') goto yy311;
			if(yych <= 'O') goto yy63;
			goto yy312;
		} else {
			if(yych <= 'n') {
				if(yych <= 'm') goto yy63;
				goto yy311;
			} else {
				if(yych == 'p') goto yy312;
				goto yy63;
			}
		}
yy9:
		yych = *++YYCURSOR;
		switch(yych){
		case 'A':
		case 'a':	goto yy272;
		case 'E':
		case 'e':	goto yy273;
		case 'I':
		case 'i':	goto yy274;
		case 'O':
		case 'o':	goto yy275;
		case 'R':
		case 'r':	goto yy276;
		default:	goto yy63;
		}
yy10:
		yych = *++YYCURSOR;
		if(yych <= 'R') {
			if(yych <= 'N') {
				if(yych == 'H') goto yy256;
				goto yy63;
			} else {
				if(yych <= 'O') goto yy257;
				if(yych <= 'Q') goto yy63;
				goto yy258;
			}
		} else {
			if(yych <= 'n') {
				if(yych == 'h') goto yy256;
				goto yy63;
			} else {
				if(yych <= 'o') goto yy257;
				if(yych == 'r') goto yy258;
				goto yy63;
			}
		}
yy11:
		yych = *++YYCURSOR;
		if(yych <= 'L') {
			if(yych == 'E') goto yy240;
			if(yych <= 'K') goto yy63;
			goto yy241;
		} else {
			if(yych <= 'e') {
				if(yych <= 'd') goto yy63;
				goto yy240;
			} else {
				if(yych == 'l') goto yy241;
				goto yy63;
			}
		}
yy12:
		yych = *++YYCURSOR;
		switch(yych){
		case 'D':
		case 'd':	goto yy206;
		case 'F':
		case 'f':	goto yy207;
		case 'L':
		case 'l':	goto yy208;
		case 'N':
		case 'n':	goto yy209;
		case 'S':
		case 's':	goto yy210;
		case 'U':
		case 'u':	goto yy212;
		default:	goto yy63;
		}
yy13:
		yych = *++YYCURSOR;
		if(yych == 'R') goto yy197;
		if(yych == 'r') goto yy197;
		goto yy63;
yy14:
		yych = *++YYCURSOR;
		if(yych <= 'O') {
			if(yych <= 'E') {
				if(yych == 'A') goto yy176;
				if(yych <= 'D') goto yy63;
				goto yy177;
			} else {
				if(yych == 'I') goto yy178;
				if(yych <= 'N') goto yy63;
				goto yy179;
			}
		} else {
			if(yych <= 'e') {
				if(yych == 'a') goto yy176;
				if(yych <= 'd') goto yy63;
				goto yy177;
			} else {
				if(yych <= 'i') {
					if(yych <= 'h') goto yy63;
					goto yy178;
				} else {
					if(yych == 'o') goto yy179;
					goto yy63;
				}
			}
		}
yy15:
		yych = *++YYCURSOR;
		if(yych <= 'I') {
			if(yych == 'A') goto yy160;
			if(yych <= 'H') goto yy63;
			goto yy161;
		} else {
			if(yych <= 'a') {
				if(yych <= '`') goto yy63;
				goto yy160;
			} else {
				if(yych == 'i') goto yy161;
				goto yy63;
			}
		}
yy16:
		yych = *++YYCURSOR;
		if(yych == 'E') goto yy157;
		if(yych == 'e') goto yy157;
		goto yy63;
yy17:
		yych = *++YYCURSOR;
		if(yych <= 'U') {
			if(yych == 'O') goto yy150;
			if(yych <= 'T') goto yy63;
			goto yy151;
		} else {
			if(yych <= 'o') {
				if(yych <= 'n') goto yy63;
				goto yy150;
			} else {
				if(yych == 'u') goto yy151;
				goto yy63;
			}
		}
yy18:
		yych = *++YYCURSOR;
		if(yych <= 'R') {
			if(yych == 'L') goto yy141;
			if(yych <= 'Q') goto yy63;
			goto yy142;
		} else {
			if(yych <= 'l') {
				if(yych <= 'k') goto yy63;
				goto yy141;
			} else {
				if(yych == 'r') goto yy142;
				goto yy63;
			}
		}
yy19:
		yych = *++YYCURSOR;
		if(yych == 'H') goto yy136;
		if(yych == 'h') goto yy136;
		goto yy63;
yy20:
		yych = *++YYCURSOR;
		if(yych == 'I') goto yy128;
		if(yych == 'i') goto yy128;
		goto yy63;
yy21:
		yych = *++YYCURSOR;
		if(yych == 'A') goto yy122;
		if(yych == 'a') goto yy122;
		goto yy63;
yy22:
		yych = *++YYCURSOR;
		if(yych == 'R') goto yy116;
		if(yych == 'r') goto yy116;
		goto yy63;
yy23:
		yych = *++YYCURSOR;
		if(yych <= 'Y') {
			if(yych <= 'I') {
				if(yych == 'E') goto yy101;
				if(yych <= 'H') goto yy63;
				goto yy102;
			} else {
				if(yych == 'L') goto yy103;
				if(yych <= 'X') goto yy63;
				goto yy104;
			}
		} else {
			if(yych <= 'i') {
				if(yych == 'e') goto yy101;
				if(yych <= 'h') goto yy63;
				goto yy102;
			} else {
				if(yych <= 'l') {
					if(yych <= 'k') goto yy63;
					goto yy103;
				} else {
					if(yych == 'y') goto yy104;
					goto yy63;
				}
			}
		}
yy24:
		yych = *++YYCURSOR;
		if(yych == 'R') goto yy94;
		if(yych == 'r') goto yy94;
		goto yy63;
yy25:
		yych = *++YYCURSOR;
		if(yych == 'N') goto yy90;
		if(yych == 'n') goto yy90;
		goto yy63;
yy26:
		yych = *++YYCURSOR;
		if(yych == '=') goto yy88;
		goto yy2;
yy27:
		yych = *++YYCURSOR;
		if(yych <= '<') goto yy2;
		if(yych <= '=') goto yy84;
		if(yych <= '>') goto yy86;
		goto yy2;
yy28:
		yych = *++YYCURSOR;
		if(yych == '=') goto yy82;
		goto yy2;
yy29:
		yych = *++YYCURSOR;
		if(yych == 'O') goto yy79;
		if(yych == 'o') goto yy79;
		goto yy63;
yy30:
		++YYCURSOR;
#line 219 "pdo_user_sql_tokenizer.re"
		{ RET(PU_PLUS); }
#line 602 "<stdout>"
yy32:
		++YYCURSOR;
#line 220 "pdo_user_sql_tokenizer.re"
		{ RET(PU_MINUS); }
#line 607 "<stdout>"
yy34:
		++YYCURSOR;
#line 221 "pdo_user_sql_tokenizer.re"
		{ RET(PU_MUL); }
#line 612 "<stdout>"
yy36:
		++YYCURSOR;
#line 222 "pdo_user_sql_tokenizer.re"
		{ RET(PU_DIV); }
#line 617 "<stdout>"
yy38:
		++YYCURSOR;
#line 223 "pdo_user_sql_tokenizer.re"
		{ RET(PU_MOD); }
#line 622 "<stdout>"
yy40:
		++YYCURSOR;
#line 224 "pdo_user_sql_tokenizer.re"
		{ RET(PU_LPAREN); }
#line 627 "<stdout>"
yy42:
		++YYCURSOR;
#line 225 "pdo_user_sql_tokenizer.re"
		{ RET(PU_RPAREN); }
#line 632 "<stdout>"
yy44:
		++YYCURSOR;
#line 226 "pdo_user_sql_tokenizer.re"
		{ RET(PU_COMMA); }
#line 637 "<stdout>"
yy46:
		++YYCURSOR;
#line 227 "pdo_user_sql_tokenizer.re"
		{ RET(PU_EQUALS); }
#line 642 "<stdout>"
yy48:
		++YYCURSOR;
#line 228 "pdo_user_sql_tokenizer.re"
		{ RET(PU_SEMICOLON); }
#line 647 "<stdout>"
yy50:
		++YYCURSOR;
		if(YYLIMIT == YYCURSOR) YYFILL(1);
		yych = *YYCURSOR;
		if(yybm[0+yych] & 1) {
			goto yy50;
		}
		if(yych <= 0x00) goto yy2;
		if(yych <= '_') goto yy76;
		goto yy77;
yy52:
		++YYCURSOR;
		if(YYLIMIT == YYCURSOR) YYFILL(1);
		yych = *YYCURSOR;
		if(yybm[0+yych] & 2) {
			goto yy52;
		}
		if(yych <= 0x00) goto yy2;
		if(yych <= '[') goto yy74;
		goto yy73;
yy54:
		++YYCURSOR;
		if(YYLIMIT == YYCURSOR) YYFILL(1);
		yych = *YYCURSOR;
		if(yybm[0+yych] & 4) {
			goto yy54;
		}
		if(yych <= 0x00) goto yy2;
		if(yych <= '[') goto yy71;
		goto yy70;
yy56:
		++YYCURSOR;
		if(YYLIMIT == YYCURSOR) YYFILL(1);
		yych = *YYCURSOR;
yy57:
		if(yybm[0+yych] & 8) {
			goto yy56;
		}
		goto yy6;
yy58:
		yych = *(YYMARKER = ++YYCURSOR);
		if(yych == 'X') goto yy66;
		if(yych == 'x') goto yy66;
		goto yy61;
yy59:
#line 235 "pdo_user_sql_tokenizer.re"
		{ RET(PU_LNUM); }
#line 695 "<stdout>"
yy60:
		++YYCURSOR;
		if(YYLIMIT == YYCURSOR) YYFILL(1);
		yych = *YYCURSOR;
yy61:
		if(yybm[0+yych] & 16) {
			goto yy60;
		}
		goto yy59;
yy62:
		++YYCURSOR;
		if(YYLIMIT == YYCURSOR) YYFILL(1);
		yych = *YYCURSOR;
yy63:
		if(yybm[0+yych] & 32) {
			goto yy62;
		}
		goto yy4;
yy64:
		++YYCURSOR;
#line 237 "pdo_user_sql_tokenizer.re"
		{ RET(PU_END); }
#line 718 "<stdout>"
yy66:
		yych = *++YYCURSOR;
		if(yybm[0+yych] & 64) {
			goto yy67;
		}
		goto yy2;
yy67:
		++YYCURSOR;
		if(YYLIMIT == YYCURSOR) YYFILL(1);
		yych = *YYCURSOR;
		if(yybm[0+yych] & 64) {
			goto yy67;
		}
#line 234 "pdo_user_sql_tokenizer.re"
		{ RET(PU_HNUM); }
#line 734 "<stdout>"
yy70:
		++YYCURSOR;
		if(YYLIMIT == YYCURSOR) YYFILL(1);
		yych = *YYCURSOR;
		if(yych <= 'm') {
			if(yych <= '/') {
				if(yych == '\'') goto yy54;
				goto yy2;
			} else {
				if(yych <= '7') goto yy54;
				if(yych == '\\') goto yy54;
				goto yy2;
			}
		} else {
			if(yych <= 's') {
				if(yych <= 'n') goto yy54;
				if(yych == 'r') goto yy54;
				goto yy2;
			} else {
				if(yych <= 't') goto yy54;
				if(yych == 'x') goto yy54;
				goto yy2;
			}
		}
yy71:
		++YYCURSOR;
#line 232 "pdo_user_sql_tokenizer.re"
		{ RET_UNESC(PU_STRING); }
#line 763 "<stdout>"
yy73:
		++YYCURSOR;
		if(YYLIMIT == YYCURSOR) YYFILL(1);
		yych = *YYCURSOR;
		if(yych <= 'm') {
			if(yych <= '/') {
				if(yych == '"') goto yy52;
				goto yy2;
			} else {
				if(yych <= '7') goto yy52;
				if(yych == '\\') goto yy52;
				goto yy2;
			}
		} else {
			if(yych <= 's') {
				if(yych <= 'n') goto yy52;
				if(yych == 'r') goto yy52;
				goto yy2;
			} else {
				if(yych <= 't') goto yy52;
				if(yych == 'x') goto yy52;
				goto yy2;
			}
		}
yy74:
		++YYCURSOR;
#line 231 "pdo_user_sql_tokenizer.re"
		{ RET_UNESC(PU_STRING); }
#line 792 "<stdout>"
yy76:
		++YYCURSOR;
		if(YYLIMIT == YYCURSOR) YYFILL(1);
		yych = *YYCURSOR;
		if(yych <= 'm') {
			if(yych <= '[') {
				if(yych <= '/') goto yy2;
				if(yych <= '7') goto yy50;
				goto yy2;
			} else {
				if(yych <= '\\') goto yy50;
				if(yych == '`') goto yy50;
				goto yy2;
			}
		} else {
			if(yych <= 's') {
				if(yych <= 'n') goto yy50;
				if(yych == 'r') goto yy50;
				goto yy2;
			} else {
				if(yych <= 't') goto yy50;
				if(yych == 'x') goto yy50;
				goto yy2;
			}
		}
yy77:
		++YYCURSOR;
#line 230 "pdo_user_sql_tokenizer.re"
		{ RET_UNESC(PU_LABEL); }
#line 822 "<stdout>"
yy79:
		yych = *++YYCURSOR;
		if(yych == 'R') goto yy80;
		if(yych != 'r') goto yy63;
yy80:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy62;
		}
#line 216 "pdo_user_sql_tokenizer.re"
		{ RET(PU_XOR); }
#line 834 "<stdout>"
yy82:
		++YYCURSOR;
#line 210 "pdo_user_sql_tokenizer.re"
		{ RET(PU_GREATER_EQUAL); }
#line 839 "<stdout>"
yy84:
		++YYCURSOR;
#line 209 "pdo_user_sql_tokenizer.re"
		{ RET(PU_LESSER_EQUAL); }
#line 844 "<stdout>"
yy86:
		++YYCURSOR;
#line 208 "pdo_user_sql_tokenizer.re"
		{ RET(PU_UNEQUAL); }
#line 849 "<stdout>"
yy88:
		++YYCURSOR;
#line 207 "pdo_user_sql_tokenizer.re"
		{ RET(PU_NOT_EQUAL); }
#line 854 "<stdout>"
yy90:
		yych = *++YYCURSOR;
		if(yych == 'U') goto yy91;
		if(yych != 'u') goto yy63;
yy91:
		yych = *++YYCURSOR;
		if(yych == 'M') goto yy92;
		if(yych != 'm') goto yy63;
yy92:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy62;
		}
#line 204 "pdo_user_sql_tokenizer.re"
		{ RET(PU_ENUM); }
#line 870 "<stdout>"
yy94:
		yych = *++YYCURSOR;
		if(yych == 'I') goto yy95;
		if(yych != 'i') goto yy63;
yy95:
		yych = *++YYCURSOR;
		if(yych == 'M') goto yy96;
		if(yych != 'm') goto yy63;
yy96:
		yych = *++YYCURSOR;
		if(yych == 'A') goto yy97;
		if(yych != 'a') goto yy63;
yy97:
		yych = *++YYCURSOR;
		if(yych == 'R') goto yy98;
		if(yych != 'r') goto yy63;
yy98:
		yych = *++YYCURSOR;
		if(yych == 'Y') goto yy99;
		if(yych != 'y') goto yy63;
yy99:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy62;
		}
#line 184 "pdo_user_sql_tokenizer.re"
		{ RET(PU_PRIMARY); }
#line 898 "<stdout>"
yy101:
		yych = *++YYCURSOR;
		if(yych == 'F') goto yy111;
		if(yych == 'f') goto yy111;
		goto yy63;
yy102:
		yych = *++YYCURSOR;
		if(yych == 'T') goto yy109;
		if(yych == 't') goto yy109;
		goto yy63;
yy103:
		yych = *++YYCURSOR;
		if(yych == 'O') goto yy106;
		if(yych == 'o') goto yy106;
		goto yy63;
yy104:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy62;
		}
#line 179 "pdo_user_sql_tokenizer.re"
		{ RET(PU_BY); }
#line 921 "<stdout>"
yy106:
		yych = *++YYCURSOR;
		if(yych == 'B') goto yy107;
		if(yych != 'b') goto yy63;
yy107:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy62;
		}
#line 202 "pdo_user_sql_tokenizer.re"
		{ RET(PU_BLOB); }
#line 933 "<stdout>"
yy109:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy62;
		}
#line 192 "pdo_user_sql_tokenizer.re"
		{ RET(PU_BIT); }
#line 941 "<stdout>"
yy111:
		yych = *++YYCURSOR;
		if(yych == 'O') goto yy112;
		if(yych != 'o') goto yy63;
yy112:
		yych = *++YYCURSOR;
		if(yych == 'R') goto yy113;
		if(yych != 'r') goto yy63;
yy113:
		yych = *++YYCURSOR;
		if(yych == 'E') goto yy114;
		if(yych != 'e') goto yy63;
yy114:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy62;
		}
#line 185 "pdo_user_sql_tokenizer.re"
		{ RET(PU_BEFORE); }
#line 961 "<stdout>"
yy116:
		++YYCURSOR;
		if((yych = *YYCURSOR) <= '^') {
			if(yych <= '@') {
				if(yych <= '/') goto yy117;
				if(yych <= '9') goto yy62;
			} else {
				if(yych == 'D') goto yy118;
				if(yych <= 'Z') goto yy62;
			}
		} else {
			if(yych <= 'c') {
				if(yych != '`') goto yy62;
			} else {
				if(yych <= 'd') goto yy118;
				if(yych <= 'z') goto yy62;
				if(yych >= 0x80) goto yy62;
			}
		}
yy117:
#line 215 "pdo_user_sql_tokenizer.re"
		{ RET(PU_OR); }
#line 984 "<stdout>"
yy118:
		yych = *++YYCURSOR;
		if(yych == 'E') goto yy119;
		if(yych != 'e') goto yy63;
yy119:
		yych = *++YYCURSOR;
		if(yych == 'R') goto yy120;
		if(yych != 'r') goto yy63;
yy120:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy62;
		}
#line 178 "pdo_user_sql_tokenizer.re"
		{ RET(PU_ORDER); }
#line 1000 "<stdout>"
yy122:
		yych = *++YYCURSOR;
		if(yych == 'V') goto yy123;
		if(yych != 'v') goto yy63;
yy123:
		yych = *++YYCURSOR;
		if(yych == 'I') goto yy124;
		if(yych != 'i') goto yy63;
yy124:
		yych = *++YYCURSOR;
		if(yych == 'N') goto yy125;
		if(yych != 'n') goto yy63;
yy125:
		yych = *++YYCURSOR;
		if(yych == 'G') goto yy126;
		if(yych != 'g') goto yy63;
yy126:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy62;
		}
#line 177 "pdo_user_sql_tokenizer.re"
		{ RET(PU_HAVING); }
#line 1024 "<stdout>"
yy128:
		yych = *++YYCURSOR;
		if(yych <= 'M') {
			if(yych == 'K') goto yy130;
			if(yych <= 'L') goto yy63;
		} else {
			if(yych <= 'k') {
				if(yych <= 'j') goto yy63;
				goto yy130;
			} else {
				if(yych != 'm') goto yy63;
			}
		}
		yych = *++YYCURSOR;
		if(yych == 'I') goto yy133;
		if(yych == 'i') goto yy133;
		goto yy63;
yy130:
		yych = *++YYCURSOR;
		if(yych == 'E') goto yy131;
		if(yych != 'e') goto yy63;
yy131:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy62;
		}
#line 211 "pdo_user_sql_tokenizer.re"
		{ RET(PU_LIKE); }
#line 1053 "<stdout>"
yy133:
		yych = *++YYCURSOR;
		if(yych == 'T') goto yy134;
		if(yych != 't') goto yy63;
yy134:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy62;
		}
#line 176 "pdo_user_sql_tokenizer.re"
		{ RET(PU_LIMIT); }
#line 1065 "<stdout>"
yy136:
		yych = *++YYCURSOR;
		if(yych == 'E') goto yy137;
		if(yych != 'e') goto yy63;
yy137:
		yych = *++YYCURSOR;
		if(yych == 'R') goto yy138;
		if(yych != 'r') goto yy63;
yy138:
		yych = *++YYCURSOR;
		if(yych == 'E') goto yy139;
		if(yych != 'e') goto yy63;
yy139:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy62;
		}
#line 174 "pdo_user_sql_tokenizer.re"
		{ RET(PU_WHERE); }
#line 1085 "<stdout>"
yy141:
		yych = *++YYCURSOR;
		if(yych == 'O') goto yy146;
		if(yych == 'o') goto yy146;
		goto yy63;
yy142:
		yych = *++YYCURSOR;
		if(yych == 'O') goto yy143;
		if(yych != 'o') goto yy63;
yy143:
		yych = *++YYCURSOR;
		if(yych == 'M') goto yy144;
		if(yych != 'm') goto yy63;
yy144:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy62;
		}
#line 172 "pdo_user_sql_tokenizer.re"
		{ RET(PU_FROM); }
#line 1106 "<stdout>"
yy146:
		yych = *++YYCURSOR;
		if(yych == 'A') goto yy147;
		if(yych != 'a') goto yy63;
yy147:
		yych = *++YYCURSOR;
		if(yych == 'T') goto yy148;
		if(yych != 't') goto yy63;
yy148:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy62;
		}
#line 200 "pdo_user_sql_tokenizer.re"
		{ RET(PU_FLOAT); }
#line 1122 "<stdout>"
yy150:
		yych = *++YYCURSOR;
		if(yych == 'T') goto yy155;
		if(yych == 't') goto yy155;
		goto yy63;
yy151:
		yych = *++YYCURSOR;
		if(yych == 'L') goto yy152;
		if(yych != 'l') goto yy63;
yy152:
		yych = *++YYCURSOR;
		if(yych == 'L') goto yy153;
		if(yych != 'l') goto yy63;
yy153:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy62;
		}
#line 166 "pdo_user_sql_tokenizer.re"
		{ RET(PU_NULL); }
#line 1143 "<stdout>"
yy155:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy62;
		}
#line 213 "pdo_user_sql_tokenizer.re"
		{ RET(PU_NOT); }
#line 1151 "<stdout>"
yy157:
		yych = *++YYCURSOR;
		if(yych == 'Y') goto yy158;
		if(yych != 'y') goto yy63;
yy158:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy62;
		}
#line 165 "pdo_user_sql_tokenizer.re"
		{ RET(PU_KEY); }
#line 1163 "<stdout>"
yy160:
		yych = *++YYCURSOR;
		if(yych <= 'R') {
			if(yych == 'L') goto yy165;
			if(yych <= 'Q') goto yy63;
			goto yy166;
		} else {
			if(yych <= 'l') {
				if(yych <= 'k') goto yy63;
				goto yy165;
			} else {
				if(yych == 'r') goto yy166;
				goto yy63;
			}
		}
yy161:
		yych = *++YYCURSOR;
		if(yych == 'E') goto yy162;
		if(yych != 'e') goto yy63;
yy162:
		yych = *++YYCURSOR;
		if(yych == 'W') goto yy163;
		if(yych != 'w') goto yy63;
yy163:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy62;
		}
#line 163 "pdo_user_sql_tokenizer.re"
		{ RET(PU_VIEW); }
#line 1194 "<stdout>"
yy165:
		yych = *++YYCURSOR;
		if(yych == 'U') goto yy172;
		if(yych == 'u') goto yy172;
		goto yy63;
yy166:
		yych = *++YYCURSOR;
		if(yych == 'C') goto yy167;
		if(yych != 'c') goto yy63;
yy167:
		yych = *++YYCURSOR;
		if(yych == 'H') goto yy168;
		if(yych != 'h') goto yy63;
yy168:
		yych = *++YYCURSOR;
		if(yych == 'A') goto yy169;
		if(yych != 'a') goto yy63;
yy169:
		yych = *++YYCURSOR;
		if(yych == 'R') goto yy170;
		if(yych != 'r') goto yy63;
yy170:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy62;
		}
#line 194 "pdo_user_sql_tokenizer.re"
		{ RET(PU_VARCHAR); }
#line 1223 "<stdout>"
yy172:
		yych = *++YYCURSOR;
		if(yych == 'E') goto yy173;
		if(yych != 'e') goto yy63;
yy173:
		yych = *++YYCURSOR;
		if(yych == 'S') goto yy174;
		if(yych != 's') goto yy63;
yy174:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy62;
		}
#line 182 "pdo_user_sql_tokenizer.re"
		{ RET(PU_VALUES); }
#line 1239 "<stdout>"
yy176:
		yych = *++YYCURSOR;
		if(yych == 'B') goto yy193;
		if(yych == 'b') goto yy193;
		goto yy63;
yy177:
		yych = *++YYCURSOR;
		if(yych == 'X') goto yy190;
		if(yych == 'x') goto yy190;
		goto yy63;
yy178:
		yych = *++YYCURSOR;
		if(yych == 'M') goto yy181;
		if(yych == 'm') goto yy181;
		goto yy63;
yy179:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy62;
		}
#line 181 "pdo_user_sql_tokenizer.re"
		{ RET(PU_TO); }
#line 1262 "<stdout>"
yy181:
		yych = *++YYCURSOR;
		if(yych == 'E') goto yy182;
		if(yych != 'e') goto yy63;
yy182:
		++YYCURSOR;
		if((yych = *YYCURSOR) <= '^') {
			if(yych <= '@') {
				if(yych <= '/') goto yy183;
				if(yych <= '9') goto yy62;
			} else {
				if(yych == 'S') goto yy184;
				if(yych <= 'Z') goto yy62;
			}
		} else {
			if(yych <= 'r') {
				if(yych != '`') goto yy62;
			} else {
				if(yych <= 's') goto yy184;
				if(yych <= 'z') goto yy62;
				if(yych >= 0x80) goto yy62;
			}
		}
yy183:
#line 197 "pdo_user_sql_tokenizer.re"
		{ RET(PU_TIME); }
#line 1289 "<stdout>"
yy184:
		yych = *++YYCURSOR;
		if(yych == 'T') goto yy185;
		if(yych != 't') goto yy63;
yy185:
		yych = *++YYCURSOR;
		if(yych == 'A') goto yy186;
		if(yych != 'a') goto yy63;
yy186:
		yych = *++YYCURSOR;
		if(yych == 'M') goto yy187;
		if(yych != 'm') goto yy63;
yy187:
		yych = *++YYCURSOR;
		if(yych == 'P') goto yy188;
		if(yych != 'p') goto yy63;
yy188:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy62;
		}
#line 198 "pdo_user_sql_tokenizer.re"
		{ RET(PU_TIMESTAMP); }
#line 1313 "<stdout>"
yy190:
		yych = *++YYCURSOR;
		if(yych == 'T') goto yy191;
		if(yych != 't') goto yy63;
yy191:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy62;
		}
#line 201 "pdo_user_sql_tokenizer.re"
		{ RET(PU_TEXT); }
#line 1325 "<stdout>"
yy193:
		yych = *++YYCURSOR;
		if(yych == 'L') goto yy194;
		if(yych != 'l') goto yy63;
yy194:
		yych = *++YYCURSOR;
		if(yych == 'E') goto yy195;
		if(yych != 'e') goto yy63;
yy195:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy62;
		}
#line 162 "pdo_user_sql_tokenizer.re"
		{ RET(PU_TABLE); }
#line 1341 "<stdout>"
yy197:
		yych = *++YYCURSOR;
		if(yych <= 'O') {
			if(yych == 'A') goto yy198;
			if(yych <= 'N') goto yy63;
			goto yy199;
		} else {
			if(yych <= 'a') {
				if(yych <= '`') goto yy63;
			} else {
				if(yych == 'o') goto yy199;
				goto yy63;
			}
		}
yy198:
		yych = *++YYCURSOR;
		if(yych == 'N') goto yy203;
		if(yych == 'n') goto yy203;
		goto yy63;
yy199:
		yych = *++YYCURSOR;
		if(yych == 'U') goto yy200;
		if(yych != 'u') goto yy63;
yy200:
		yych = *++YYCURSOR;
		if(yych == 'P') goto yy201;
		if(yych != 'p') goto yy63;
yy201:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy62;
		}
#line 175 "pdo_user_sql_tokenizer.re"
		{ RET(PU_GROUP); }
#line 1376 "<stdout>"
yy203:
		yych = *++YYCURSOR;
		if(yych == 'T') goto yy204;
		if(yych != 't') goto yy63;
yy204:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy62;
		}
#line 156 "pdo_user_sql_tokenizer.re"
		{ RET(PU_GRANT); }
#line 1388 "<stdout>"
yy206:
		yych = *++YYCURSOR;
		if(yych == 'D') goto yy238;
		if(yych == 'd') goto yy238;
		goto yy63;
yy207:
		yych = *++YYCURSOR;
		if(yych == 'T') goto yy234;
		if(yych == 't') goto yy234;
		goto yy63;
yy208:
		yych = *++YYCURSOR;
		if(yych <= 'T') {
			if(yych == 'L') goto yy229;
			if(yych <= 'S') goto yy63;
			goto yy228;
		} else {
			if(yych <= 'l') {
				if(yych <= 'k') goto yy63;
				goto yy229;
			} else {
				if(yych == 't') goto yy228;
				goto yy63;
			}
		}
yy209:
		yych = *++YYCURSOR;
		if(yych == 'D') goto yy226;
		if(yych == 'd') goto yy226;
		goto yy63;
yy210:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy62;
		}
#line 180 "pdo_user_sql_tokenizer.re"
		{ RET(PU_AS); }
#line 1426 "<stdout>"
yy212:
		yych = *++YYCURSOR;
		if(yych == 'T') goto yy213;
		if(yych != 't') goto yy63;
yy213:
		yych = *++YYCURSOR;
		if(yych == 'O') goto yy214;
		if(yych != 'o') goto yy63;
yy214:
		yych = *++YYCURSOR;
		if(yych != '_') goto yy63;
		yych = *++YYCURSOR;
		if(yych == 'I') goto yy216;
		if(yych != 'i') goto yy63;
yy216:
		yych = *++YYCURSOR;
		if(yych == 'N') goto yy217;
		if(yych != 'n') goto yy63;
yy217:
		yych = *++YYCURSOR;
		if(yych == 'C') goto yy218;
		if(yych != 'c') goto yy63;
yy218:
		yych = *++YYCURSOR;
		if(yych == 'R') goto yy219;
		if(yych != 'r') goto yy63;
yy219:
		yych = *++YYCURSOR;
		if(yych == 'E') goto yy220;
		if(yych != 'e') goto yy63;
yy220:
		yych = *++YYCURSOR;
		if(yych == 'M') goto yy221;
		if(yych != 'm') goto yy63;
yy221:
		yych = *++YYCURSOR;
		if(yych == 'E') goto yy222;
		if(yych != 'e') goto yy63;
yy222:
		yych = *++YYCURSOR;
		if(yych == 'N') goto yy223;
		if(yych != 'n') goto yy63;
yy223:
		yych = *++YYCURSOR;
		if(yych == 'T') goto yy224;
		if(yych != 't') goto yy63;
yy224:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy62;
		}
#line 167 "pdo_user_sql_tokenizer.re"
		{ RET(PU_AUTO_INCREMENT); }
#line 1480 "<stdout>"
yy226:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy62;
		}
#line 214 "pdo_user_sql_tokenizer.re"
		{ RET(PU_AND); }
#line 1488 "<stdout>"
yy228:
		yych = *++YYCURSOR;
		if(yych == 'E') goto yy231;
		if(yych == 'e') goto yy231;
		goto yy63;
yy229:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy62;
		}
#line 168 "pdo_user_sql_tokenizer.re"
		{ RET(PU_ALL); }
#line 1501 "<stdout>"
yy231:
		yych = *++YYCURSOR;
		if(yych == 'R') goto yy232;
		if(yych != 'r') goto yy63;
yy232:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy62;
		}
#line 155 "pdo_user_sql_tokenizer.re"
		{ RET(PU_ALTER); }
#line 1513 "<stdout>"
yy234:
		yych = *++YYCURSOR;
		if(yych == 'E') goto yy235;
		if(yych != 'e') goto yy63;
yy235:
		yych = *++YYCURSOR;
		if(yych == 'R') goto yy236;
		if(yych != 'r') goto yy63;
yy236:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy62;
		}
#line 186 "pdo_user_sql_tokenizer.re"
		{ RET(PU_AFTER); }
#line 1529 "<stdout>"
yy238:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy62;
		}
#line 158 "pdo_user_sql_tokenizer.re"
		{ RET(PU_ADD); }
#line 1537 "<stdout>"
yy240:
		yych = *++YYCURSOR;
		if(yych <= 'V') {
			if(yych == 'N') goto yy246;
			if(yych <= 'U') goto yy63;
			goto yy247;
		} else {
			if(yych <= 'n') {
				if(yych <= 'm') goto yy63;
				goto yy246;
			} else {
				if(yych == 'v') goto yy247;
				goto yy63;
			}
		}
yy241:
		yych = *++YYCURSOR;
		if(yych == 'I') goto yy242;
		if(yych != 'i') goto yy63;
yy242:
		yych = *++YYCURSOR;
		if(yych == 'K') goto yy243;
		if(yych != 'k') goto yy63;
yy243:
		yych = *++YYCURSOR;
		if(yych == 'E') goto yy244;
		if(yych != 'e') goto yy63;
yy244:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy62;
		}
#line 212 "pdo_user_sql_tokenizer.re"
		{ RET(PU_RLIKE); }
#line 1572 "<stdout>"
yy246:
		yych = *++YYCURSOR;
		if(yych == 'A') goto yy252;
		if(yych == 'a') goto yy252;
		goto yy63;
yy247:
		yych = *++YYCURSOR;
		if(yych == 'O') goto yy248;
		if(yych != 'o') goto yy63;
yy248:
		yych = *++YYCURSOR;
		if(yych == 'K') goto yy249;
		if(yych != 'k') goto yy63;
yy249:
		yych = *++YYCURSOR;
		if(yych == 'E') goto yy250;
		if(yych != 'e') goto yy63;
yy250:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy62;
		}
#line 157 "pdo_user_sql_tokenizer.re"
		{ RET(PU_REVOKE); }
#line 1597 "<stdout>"
yy252:
		yych = *++YYCURSOR;
		if(yych == 'M') goto yy253;
		if(yych != 'm') goto yy63;
yy253:
		yych = *++YYCURSOR;
		if(yych == 'E') goto yy254;
		if(yych != 'e') goto yy63;
yy254:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy62;
		}
#line 154 "pdo_user_sql_tokenizer.re"
		{ RET(PU_RENAME); }
#line 1613 "<stdout>"
yy256:
		yych = *++YYCURSOR;
		if(yych == 'A') goto yy269;
		if(yych == 'a') goto yy269;
		goto yy63;
yy257:
		yych = *++YYCURSOR;
		if(yych == 'L') goto yy264;
		if(yych == 'l') goto yy264;
		goto yy63;
yy258:
		yych = *++YYCURSOR;
		if(yych == 'E') goto yy259;
		if(yych != 'e') goto yy63;
yy259:
		yych = *++YYCURSOR;
		if(yych == 'A') goto yy260;
		if(yych != 'a') goto yy63;
yy260:
		yych = *++YYCURSOR;
		if(yych == 'T') goto yy261;
		if(yych != 't') goto yy63;
yy261:
		yych = *++YYCURSOR;
		if(yych == 'E') goto yy262;
		if(yych != 'e') goto yy63;
yy262:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy62;
		}
#line 153 "pdo_user_sql_tokenizer.re"
		{ RET(PU_CREATE); }
#line 1647 "<stdout>"
yy264:
		yych = *++YYCURSOR;
		if(yych == 'U') goto yy265;
		if(yych != 'u') goto yy63;
yy265:
		yych = *++YYCURSOR;
		if(yych == 'M') goto yy266;
		if(yych != 'm') goto yy63;
yy266:
		yych = *++YYCURSOR;
		if(yych == 'N') goto yy267;
		if(yych != 'n') goto yy63;
yy267:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy62;
		}
#line 164 "pdo_user_sql_tokenizer.re"
		{ RET(PU_COLUMN); }
#line 1667 "<stdout>"
yy269:
		yych = *++YYCURSOR;
		if(yych == 'R') goto yy270;
		if(yych != 'r') goto yy63;
yy270:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy62;
		}
#line 193 "pdo_user_sql_tokenizer.re"
		{ RET(PU_CHAR); }
#line 1679 "<stdout>"
yy272:
		yych = *++YYCURSOR;
		if(yych == 'T') goto yy303;
		if(yych == 't') goto yy303;
		goto yy63;
yy273:
		yych = *++YYCURSOR;
		if(yych <= 'L') {
			if(yych == 'F') goto yy293;
			if(yych <= 'K') goto yy63;
			goto yy292;
		} else {
			if(yych <= 'f') {
				if(yych <= 'e') goto yy63;
				goto yy293;
			} else {
				if(yych == 'l') goto yy292;
				goto yy63;
			}
		}
yy274:
		yych = *++YYCURSOR;
		if(yych == 'S') goto yy285;
		if(yych == 's') goto yy285;
		goto yy63;
yy275:
		yych = *++YYCURSOR;
		if(yych == 'U') goto yy280;
		if(yych == 'u') goto yy280;
		goto yy63;
yy276:
		yych = *++YYCURSOR;
		if(yych == 'O') goto yy277;
		if(yych != 'o') goto yy63;
yy277:
		yych = *++YYCURSOR;
		if(yych == 'P') goto yy278;
		if(yych != 'p') goto yy63;
yy278:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy62;
		}
#line 159 "pdo_user_sql_tokenizer.re"
		{ RET(PU_DROP); }
#line 1725 "<stdout>"
yy280:
		yych = *++YYCURSOR;
		if(yych == 'B') goto yy281;
		if(yych != 'b') goto yy63;
yy281:
		yych = *++YYCURSOR;
		if(yych == 'L') goto yy282;
		if(yych != 'l') goto yy63;
yy282:
		yych = *++YYCURSOR;
		if(yych == 'E') goto yy283;
		if(yych != 'e') goto yy63;
yy283:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy62;
		}
#line 199 "pdo_user_sql_tokenizer.re"
		{ RET(PU_DOUBLE); }
#line 1745 "<stdout>"
yy285:
		yych = *++YYCURSOR;
		if(yych == 'T') goto yy286;
		if(yych != 't') goto yy63;
yy286:
		yych = *++YYCURSOR;
		if(yych == 'I') goto yy287;
		if(yych != 'i') goto yy63;
yy287:
		yych = *++YYCURSOR;
		if(yych == 'N') goto yy288;
		if(yych != 'n') goto yy63;
yy288:
		yych = *++YYCURSOR;
		if(yych == 'C') goto yy289;
		if(yych != 'c') goto yy63;
yy289:
		yych = *++YYCURSOR;
		if(yych == 'T') goto yy290;
		if(yych != 't') goto yy63;
yy290:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy62;
		}
#line 188 "pdo_user_sql_tokenizer.re"
		{ RET(PU_DISTINCT); }
#line 1773 "<stdout>"
yy292:
		yych = *++YYCURSOR;
		if(yych == 'E') goto yy299;
		if(yych == 'e') goto yy299;
		goto yy63;
yy293:
		yych = *++YYCURSOR;
		if(yych == 'A') goto yy294;
		if(yych != 'a') goto yy63;
yy294:
		yych = *++YYCURSOR;
		if(yych == 'U') goto yy295;
		if(yych != 'u') goto yy63;
yy295:
		yych = *++YYCURSOR;
		if(yych == 'L') goto yy296;
		if(yych != 'l') goto yy63;
yy296:
		yych = *++YYCURSOR;
		if(yych == 'T') goto yy297;
		if(yych != 't') goto yy63;
yy297:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy62;
		}
#line 173 "pdo_user_sql_tokenizer.re"
		{ RET(PU_DEFAULT); }
#line 1802 "<stdout>"
yy299:
		yych = *++YYCURSOR;
		if(yych == 'T') goto yy300;
		if(yych != 't') goto yy63;
yy300:
		yych = *++YYCURSOR;
		if(yych == 'E') goto yy301;
		if(yych != 'e') goto yy63;
yy301:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy62;
		}
#line 152 "pdo_user_sql_tokenizer.re"
		{ RET(PU_DELETE); }
#line 1818 "<stdout>"
yy303:
		yych = *++YYCURSOR;
		if(yych == 'E') goto yy304;
		if(yych != 'e') goto yy63;
yy304:
		++YYCURSOR;
		if((yych = *YYCURSOR) <= '^') {
			if(yych <= '@') {
				if(yych <= '/') goto yy305;
				if(yych <= '9') goto yy62;
			} else {
				if(yych == 'T') goto yy306;
				if(yych <= 'Z') goto yy62;
			}
		} else {
			if(yych <= 's') {
				if(yych != '`') goto yy62;
			} else {
				if(yych <= 't') goto yy306;
				if(yych <= 'z') goto yy62;
				if(yych >= 0x80) goto yy62;
			}
		}
yy305:
#line 196 "pdo_user_sql_tokenizer.re"
		{ RET(PU_DATE); }
#line 1845 "<stdout>"
yy306:
		yych = *++YYCURSOR;
		if(yych == 'I') goto yy307;
		if(yych != 'i') goto yy63;
yy307:
		yych = *++YYCURSOR;
		if(yych == 'M') goto yy308;
		if(yych != 'm') goto yy63;
yy308:
		yych = *++YYCURSOR;
		if(yych == 'E') goto yy309;
		if(yych != 'e') goto yy63;
yy309:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy62;
		}
#line 195 "pdo_user_sql_tokenizer.re"
		{ RET(PU_DATETIME); }
#line 1865 "<stdout>"
yy311:
		yych = *++YYCURSOR;
		if(yych == 'I') goto yy318;
		if(yych == 'i') goto yy318;
		goto yy63;
yy312:
		yych = *++YYCURSOR;
		if(yych == 'D') goto yy313;
		if(yych != 'd') goto yy63;
yy313:
		yych = *++YYCURSOR;
		if(yych == 'A') goto yy314;
		if(yych != 'a') goto yy63;
yy314:
		yych = *++YYCURSOR;
		if(yych == 'T') goto yy315;
		if(yych != 't') goto yy63;
yy315:
		yych = *++YYCURSOR;
		if(yych == 'E') goto yy316;
		if(yych != 'e') goto yy63;
yy316:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy62;
		}
#line 151 "pdo_user_sql_tokenizer.re"
		{ RET(PU_UPDATE); }
#line 1894 "<stdout>"
yy318:
		yych = *++YYCURSOR;
		if(yych == 'Q') goto yy319;
		if(yych != 'q') goto yy63;
yy319:
		yych = *++YYCURSOR;
		if(yych == 'U') goto yy320;
		if(yych != 'u') goto yy63;
yy320:
		yych = *++YYCURSOR;
		if(yych == 'E') goto yy321;
		if(yych != 'e') goto yy63;
yy321:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy62;
		}
#line 183 "pdo_user_sql_tokenizer.re"
		{ RET(PU_UNIQUE); }
#line 1914 "<stdout>"
yy323:
		yych = *++YYCURSOR;
		if(yych == 'E') goto yy334;
		if(yych == 'e') goto yy334;
		goto yy63;
yy324:
		yych = *++YYCURSOR;
		if(yych <= 'T') {
			if(yych <= 'R') goto yy63;
			if(yych >= 'T') goto yy326;
		} else {
			if(yych <= 'r') goto yy63;
			if(yych <= 's') goto yy325;
			if(yych <= 't') goto yy326;
			goto yy63;
		}
yy325:
		yych = *++YYCURSOR;
		if(yych == 'E') goto yy330;
		if(yych == 'e') goto yy330;
		goto yy63;
yy326:
		++YYCURSOR;
		if((yych = *YYCURSOR) <= '^') {
			if(yych <= '@') {
				if(yych <= '/') goto yy327;
				if(yych <= '9') goto yy62;
			} else {
				if(yych == 'O') goto yy328;
				if(yych <= 'Z') goto yy62;
			}
		} else {
			if(yych <= 'n') {
				if(yych != '`') goto yy62;
			} else {
				if(yych <= 'o') goto yy328;
				if(yych <= 'z') goto yy62;
				if(yych >= 0x80) goto yy62;
			}
		}
yy327:
#line 191 "pdo_user_sql_tokenizer.re"
		{ RET(PU_INT); }
#line 1958 "<stdout>"
yy328:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy62;
		}
#line 171 "pdo_user_sql_tokenizer.re"
		{ RET(PU_INTO); }
#line 1966 "<stdout>"
yy330:
		yych = *++YYCURSOR;
		if(yych == 'R') goto yy331;
		if(yych != 'r') goto yy63;
yy331:
		yych = *++YYCURSOR;
		if(yych == 'T') goto yy332;
		if(yych != 't') goto yy63;
yy332:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy62;
		}
#line 150 "pdo_user_sql_tokenizer.re"
		{ RET(PU_INSERT); }
#line 1982 "<stdout>"
yy334:
		yych = *++YYCURSOR;
		if(yych == 'N') goto yy335;
		if(yych != 'n') goto yy63;
yy335:
		yych = *++YYCURSOR;
		if(yych == 'T') goto yy336;
		if(yych != 't') goto yy63;
yy336:
		yych = *++YYCURSOR;
		if(yych == 'I') goto yy337;
		if(yych != 'i') goto yy63;
yy337:
		yych = *++YYCURSOR;
		if(yych == 'F') goto yy338;
		if(yych != 'f') goto yy63;
yy338:
		yych = *++YYCURSOR;
		if(yych == 'I') goto yy339;
		if(yych != 'i') goto yy63;
yy339:
		yych = *++YYCURSOR;
		if(yych == 'E') goto yy340;
		if(yych != 'e') goto yy63;
yy340:
		yych = *++YYCURSOR;
		if(yych == 'D') goto yy341;
		if(yych != 'd') goto yy63;
yy341:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy62;
		}
#line 187 "pdo_user_sql_tokenizer.re"
		{ RET(PU_IDENTIFIED); }
#line 2018 "<stdout>"
yy343:
		yych = *++YYCURSOR;
		if(yych <= 'T') {
			if(yych == 'L') goto yy346;
			if(yych <= 'S') goto yy63;
			goto yy347;
		} else {
			if(yych <= 'l') {
				if(yych <= 'k') goto yy63;
				goto yy346;
			} else {
				if(yych == 't') goto yy347;
				goto yy63;
			}
		}
yy344:
		++YYCURSOR;
		if(YYLIMIT == YYCURSOR) YYFILL(1);
		yych = *YYCURSOR;
		if(yybm[0+yych] & 128) {
			goto yy344;
		}
		if(yych <= '9') {
			if(yych <= 0x0D) {
				if(yych <= 0x08) goto yy6;
				if(yych <= 0x0A) goto yy56;
				if(yych <= 0x0C) goto yy6;
				goto yy56;
			} else {
				if(yych == ' ') goto yy56;
				if(yych <= '/') goto yy6;
				goto yy62;
			}
		} else {
			if(yych <= '_') {
				if(yych <= '@') goto yy6;
				if(yych <= 'Z') goto yy62;
				if(yych <= '^') goto yy6;
				goto yy62;
			} else {
				if(yych <= '`') goto yy6;
				if(yych <= 'z') goto yy62;
				if(yych <= 0x7F) goto yy6;
				goto yy62;
			}
		}
yy346:
		yych = *++YYCURSOR;
		if(yych == 'E') goto yy349;
		if(yych == 'e') goto yy349;
		goto yy63;
yy347:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy62;
		}
#line 203 "pdo_user_sql_tokenizer.re"
		{ RET(PU_SET); }
#line 2077 "<stdout>"
yy349:
		yych = *++YYCURSOR;
		if(yych == 'C') goto yy350;
		if(yych != 'c') goto yy63;
yy350:
		yych = *++YYCURSOR;
		if(yych == 'T') goto yy351;
		if(yych != 't') goto yy63;
yy351:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy62;
		}
#line 149 "pdo_user_sql_tokenizer.re"
		{ RET(PU_SELECT); }
#line 2093 "<stdout>"
	}
}
#line 238 "pdo_user_sql_tokenizer.re"

}

#define PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(v)	{ v, #v },
 
php_pdo_user_sql_token_label php_pdo_user_sql_token_labels[] = {
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_END)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_LABEL)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_STRING)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_WHITESPACE)

	/* Verbs */
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_SELECT)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_INSERT)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_UPDATE)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_DELETE)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_CREATE)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_RENAME)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_ALTER)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_GRANT)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_REVOKE)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_ADD)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_DROP)

	/* Nouns */
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_TABLE)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_VIEW)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_COLUMN)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_KEY)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_NULL)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_AUTO_INCREMENT)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_HNUM)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_LNUM)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_ALL)

	/* Prepositions */
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_INTO)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_FROM)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(	PU_DEFAULT)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_WHERE)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_GROUP)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_LIMIT)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_HAVING)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_ORDER)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_BY)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_AS)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_TO)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_VALUES)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_UNIQUE)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_PRIMARY)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_BEFORE)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_AFTER)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_IDENTIFIED)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_DISTINCT)

	/* SQL Types */
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_INT)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_BIT)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_CHAR)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_VARCHAR)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_DATETIME)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_DATE)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_TIME)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_TIMESTAMP)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_DOUBLE)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_FLOAT)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_TEXT)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_BLOB)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_SET)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_ENUM)

	/* Logicals */
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_NOT_EQUAL) 	/* != */
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_UNEQUAL)		/* <> */
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_LESSER_EQUAL)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_GREATER_EQUAL)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_LIKE)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_RLIKE)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_NOT)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_AND)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_OR)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_XOR)

	/* Single Character Tokens */
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_PLUS)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_MINUS)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_MUL)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_DIV)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_MOD)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_LPAREN)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_RPAREN)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_COMMA)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_EQUALS)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_SEMICOLON)

	{ 0, NULL }
};
