#define PU_NOT                             1
#define PU_GROUP                           2
#define PU_ORDER                           3
#define PU_BY                              4
#define PU_LIMIT                           5
#define PU_WHERE                           6
#define PU_HAVING                          7
#define PU_SELECT                          8
#define PU_INSERT                          9
#define PU_INTO                           10
#define PU_COMMA                          11
#define PU_AND                            12
#define PU_OR                             13
#define PU_XOR                            14
#define PU_AS                             15
#define PU_BETWEEN                        16
#define PU_LIKE                           17
#define PU_RLIKE                          18
#define PU_EQUALS                         19
#define PU_LESSER                         20
#define PU_GREATER                        21
#define PU_LESS_EQUAL                     22
#define PU_GREATER_EQUAL                  23
#define PU_DISTINCT                       24
#define PU_MUL                            25
#define PU_DIV                            26
#define PU_MOD                            27
#define PU_RPAREN                         28
#define PU_PLUS                           29
#define PU_MINUS                          30
#define PU_LPAREN                         31
#define PU_LABEL                          32
#define PU_LNUM                           33
#define PU_HNUM                           34
#define PU_STRING                         35
#define PU_SEMICOLON                      36
#define PU_VALUES                         37
#define PU_UPDATE                         38
#define PU_SET                            39
#define PU_DELETE                         40
#define PU_RENAME                         41
#define PU_TABLE                          42
#define PU_CREATE                         43
#define PU_DROP                           44
#define PU_FROM                           45
#define PU_NULL                           46
#define PU_DEFAULT                        47
#define PU_PRIMARY                        48
#define PU_KEY                            49
#define PU_UNIQUE                         50
#define PU_AUTO_INCREMENT                 51
#define PU_BIT                            52
#define PU_INT                            53
#define PU_INTEGER                        54
#define PU_TINYINT                        55
#define PU_SMALLINT                       56
#define PU_MEDIUMINT                      57
#define PU_BIGINT                         58
#define PU_YEAR                           59
#define PU_FLOAT                          60
#define PU_REAL                           61
#define PU_DECIMAL                        62
#define PU_DOUBLE                         63
#define PU_CHAR                           64
#define PU_VARCHAR                        65
#define PU_DATE                           66
#define PU_TIME                           67
#define PU_DATETIME                       68
#define PU_TIMESTAMP                      69
#define PU_TEXT                           70
#define PU_TINYTEXT                       71
#define PU_MEDIUMTEXT                     72
#define PU_LONGTEXT                       73
#define PU_BLOB                           74
#define PU_TINYBLOB                       75
#define PU_MEDIUMBLOB                     76
#define PU_LONGBLOB                       77
#define PU_BINARY                         78
#define PU_VARBINARY                      79
#define PU_ENUM                           80
#define PU_UNSIGNED                       81
#define PU_ZEROFILL                       82
#define PU_TO                             83
#define PU_DOT                            84
#define PU_ON                             85
#define PU_INNER                          86
#define PU_JOIN                           87
#define PU_OUTER                          88
#define PU_LEFT                           89
#define PU_RIGHT                          90
#define PU_IN                             91
#define PU_NOT_EQUAL                      92
#define PU_UNEQUAL                        93
#define PU_LESSER_EQUAL                   94
#define PU_COLON                          95
#define PU_DNUM                           96
#define PU_ASC                            97
#define PU_DESC                           98
