/* Generated by re2c 0.10.2 on Tue May  9 01:18:42 2006 */
#line 1 "pdo_user_sql_tokenizer.re"
#include "php.h"
#include "php_pdo_user_sql.h"

static void php_pdo_user_unquote(php_pdo_user_sql_token *token)
{
	char *out = emalloc(token->token_len + 1), *p = out;
	int i;

	token->token_len--;
	for(i = 1; i < token->token_len; i++) {
		switch (token->token[i]) {
			case '\\':
				if ((i + 1) >= token->token_len) {
					/* EOL */
					*(p++) = '\\';
					goto done;
				}
				switch (token->token[++i]) {
					case 'r':	*(p++) = '\r';		goto next_iter;
					case 'n':	*(p++) = '\n';		goto next_iter;
					case 't':	*(p++) = '\t';		goto next_iter;
					case '\\':	*(p++) = '\\';		goto next_iter;
					case 'x':
					{
						unsigned char val = 0;

						if (++i >= token->token_len) {
							*(p++) = 'x';
							goto done;
						}
						if (token->token[i] >= '0' && token->token[i] <= '9') {
							val = token->token[i] - '0';
						} else if (token->token[i] >= 'A' && token->token[i] <= 'F') {
							val = 10 + token->token[i] - 'A';
						} else if (token->token[i] >= 'a' && token->token[i] <= 'f') {
							val = 10 + token->token[i] - 'a';
						} else {
							*(p++) = 'x';
							i--;
							goto next_iter;
						}
						if (++i >= token->token_len) {
							*(p++) = val;
							goto done;
						}
						if (token->token[i] >= '0' && token->token[i] <= '9') {
							val <<= 4;
							val |= token->token[i] - '0';
						} else if (token->token[i] >= 'A' && token->token[i] <= 'F') {
							val <<= 4;
							val |= 10 + token->token[i] - 'A';
						} else if (token->token[i] >= 'a' && token->token[i] <= 'f') {
							val <<= 4;
							val |= 10 + token->token[i] - 'a';
						} else {
							*(p++) = val;
							i--;
							goto next_iter;
						}
						*(p++) = val;
						goto next_iter;
					}
					default: /* local-quote, octal, and non-escaped */
					{
						unsigned char val = 0;

						if (token->token[i] >= '0' && token->token[i] <= '7') {
							val = token->token[i] - '0';
						} else {
							*(p++) = token->token[i];
							goto next_iter;
						}
						if (++i >= token->token_len) {
							*(p++) = val;
							goto done;
						}
						if (token->token[i] >= '0' && token->token[i] <= '7') {
							val <<= 3;
							val |= token->token[i] - '0';
						} else {
							*(p++) = val;
							i--;
							goto next_iter;
						}
						if (val > 0x1F) {
							*(p++) = val;
							goto next_iter;
						}
						if (++i >= token->token_len) {
							*(p++) = val;
							goto done;
						}
						if (token->token[i] >= '0' && token->token[i] <= '7') {
							val <<= 3;
							val |= token->token[i] - '0';
						} else {
							*(p++) = val;
							i--;
							goto next_iter;
						}
						*(p++) = val;
						goto next_iter;
					}
				}
			default:
				*(p++) = token->token[i];
		}
next_iter:
		continue; /* avoids warning */
	}

done:
	token->token = out;
	token->token_len = p - out;
	*p = 0;

	token->freeme = 1;
}

#define RET(num) { token->token_len = t->start - token->token; token->id = num; return (num); }
#define RET_UNESC(num) { token->token_len = t->start - token->token; token->id = num; php_pdo_user_unquote(token); return (num); }

#define YYCTYPE		char
#define YYCURSOR	(t->start)
#define YYLIMIT		(t->end)
#define YYFILL(n)
#define YYMARKER	marker

int php_pdo_user_sql_get_token(php_pdo_user_sql_tokenizer *t, php_pdo_user_sql_token *token)
{
	token->freeme = 0;
	token->token = t->start;
	char *marker = t->start;

{
	static unsigned char yybm[] = {
		  0,   7,   7,   7,   7,   7,   7,   7, 
		  7,  15,  15,   7,   7,  15,   7,   7, 
		  7,   7,   7,   7,   7,   7,   7,   7, 
		  7,   7,   7,   7,   7,   7,   7,   7, 
		 15,   7,   5,   7,   7,   7,   7,   3, 
		  7,   7,   7,   7,   7,   7,   7,   7, 
		119, 119, 119, 119, 119, 119, 119, 119, 
		119, 119,   7,   7,   7,   7,   7,   7, 
		  7, 103, 103, 103, 103, 103, 103,  39, 
		 39,  39,  39,  39,  39,  39,  39,  39, 
		 39,  39,  39,  39,  39,  39,  39,  39, 
		 39,  39,  39,   7,   0,   7,   7,  39, 
		  6, 103, 103, 103, 103, 103, 103,  39, 
		 39,  39,  39,  39,  39,  39,  39,  39, 
		 39,  39,  39, 175,  39,  39,  39,  39, 
		 39,  39,  39,   7,   7,   7,   7,   7, 
		 39,  39,  39,  39,  39,  39,  39,  39, 
		 39,  39,  39,  39,  39,  39,  39,  39, 
		 39,  39,  39,  39,  39,  39,  39,  39, 
		 39,  39,  39,  39,  39,  39,  39,  39, 
		 39,  39,  39,  39,  39,  39,  39,  39, 
		 39,  39,  39,  39,  39,  39,  39,  39, 
		 39,  39,  39,  39,  39,  39,  39,  39, 
		 39,  39,  39,  39,  39,  39,  39,  39, 
		 39,  39,  39,  39,  39,  39,  39,  39, 
		 39,  39,  39,  39,  39,  39,  39,  39, 
		 39,  39,  39,  39,  39,  39,  39,  39, 
		 39,  39,  39,  39,  39,  39,  39,  39, 
		 39,  39,  39,  39,  39,  39,  39,  39, 
		 39,  39,  39,  39,  39,  39,  39,  39, 
		 39,  39,  39,  39,  39,  39,  39,  39, 
		 39,  39,  39,  39,  39,  39,  39,  39, 
	};

#line 174 "pdo_user_sql_tokenizer.c"
	{
		YYCTYPE yych;
		unsigned int yyaccept = 0;

		if((YYLIMIT - YYCURSOR) < 15) YYFILL(15);
		yych = *YYCURSOR;
		switch(yych){
		case 0x00:	goto yy70;
		case 0x01:
		case 0x02:
		case 0x03:
		case 0x04:
		case 0x05:
		case 0x06:
		case 0x07:
		case 0x08:
		case 0x0B:
		case 0x0C:
		case 0x0E:
		case 0x0F:
		case 0x10:
		case 0x11:
		case 0x12:
		case 0x13:
		case 0x14:
		case 0x15:
		case 0x16:
		case 0x17:
		case 0x18:
		case 0x19:
		case 0x1A:
		case 0x1B:
		case 0x1C:
		case 0x1D:
		case 0x1E:
		case 0x1F:
		case '#':
		case '$':
		case '&':
		case ':':
		case '?':
		case '@':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '{':
		case '|':
		case '}':
		case '~':
		case 0x7F:	goto yy2;
		case 0x09:
		case 0x0A:
		case 0x0D:
		case ' ':	goto yy62;
		case '!':	goto yy30;
		case '"':	goto yy58;
		case '%':	goto yy42;
		case '\'':	goto yy60;
		case '(':	goto yy44;
		case ')':	goto yy46;
		case '*':	goto yy38;
		case '+':	goto yy34;
		case ',':	goto yy48;
		case '-':	goto yy36;
		case '.':	goto yy54;
		case '/':	goto yy40;
		case '0':	goto yy64;
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':	goto yy66;
		case ';':	goto yy52;
		case '<':	goto yy31;
		case '=':	goto yy50;
		case '>':	goto yy32;
		case 'A':
		case 'a':	goto yy12;
		case 'B':
		case 'b':	goto yy23;
		case 'C':
		case 'c':	goto yy10;
		case 'D':
		case 'd':	goto yy9;
		case 'E':
		case 'e':	goto yy29;
		case 'F':
		case 'f':	goto yy18;
		case 'G':
		case 'g':	goto yy13;
		case 'H':
		case 'h':	goto yy21;
		case 'I':
		case 'i':	goto yy7;
		case 'J':
		case 'j':	goto yy25;
		case 'K':
		case 'k':	goto yy16;
		case 'L':
		case 'l':	goto yy20;
		case 'M':
		case 'm':	goto yy27;
		case 'N':
		case 'n':	goto yy17;
		case 'O':
		case 'o':	goto yy22;
		case 'P':
		case 'p':	goto yy24;
		case 'R':
		case 'r':	goto yy11;
		case 'S':	goto yy3;
		case 'T':
		case 't':	goto yy14;
		case 'U':
		case 'u':	goto yy8;
		case 'V':
		case 'v':	goto yy15;
		case 'W':
		case 'w':	goto yy19;
		case 'X':
		case 'x':	goto yy33;
		case 'Y':
		case 'y':	goto yy28;
		case 'Z':
		case 'z':	goto yy26;
		case '`':	goto yy56;
		case 's':	goto yy5;
		default:	goto yy68;
		}
yy2:
		YYCURSOR = YYMARKER;
		switch(yyaccept) {
		case 0:	goto yy37;
		case 1:	goto yy65;
		}
yy3:
		++YYCURSOR;
		if((yych = *YYCURSOR) <= 'M') {
			if(yych == 'E') goto yy482;
			if(yych <= 'L') goto yy69;
			goto yy483;
		} else {
			if(yych <= 'e') {
				if(yych <= 'd') goto yy69;
				goto yy482;
			} else {
				if(yych == 'm') goto yy483;
				goto yy69;
			}
		}
yy4:
#line 264 "pdo_user_sql_tokenizer.re"
		{ RET(PU_LABEL); }
#line 333 "pdo_user_sql_tokenizer.c"
yy5:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 128) {
			goto yy484;
		}
		if(yych <= '^') {
			if(yych <= 'D') {
				if(yych <= '/') goto yy63;
				if(yych <= '9') goto yy68;
				if(yych <= '@') goto yy63;
				goto yy68;
			} else {
				if(yych <= 'L') {
					if(yych <= 'E') goto yy482;
					goto yy68;
				} else {
					if(yych <= 'M') goto yy483;
					if(yych <= 'Z') goto yy68;
					goto yy63;
				}
			}
		} else {
			if(yych <= 'e') {
				if(yych == '`') goto yy63;
				if(yych <= 'd') goto yy68;
				goto yy482;
			} else {
				if(yych <= 'm') {
					if(yych <= 'l') goto yy68;
					goto yy483;
				} else {
					if(yych <= 'z') goto yy68;
					if(yych <= 0x7F) goto yy63;
					goto yy68;
				}
			}
		}
yy6:
#line 260 "pdo_user_sql_tokenizer.re"
		{ RET(PU_WHITESPACE); }
#line 374 "pdo_user_sql_tokenizer.c"
yy7:
		yych = *++YYCURSOR;
		if(yych <= 'N') {
			if(yych == 'D') goto yy453;
			if(yych <= 'M') goto yy69;
			goto yy454;
		} else {
			if(yych <= 'd') {
				if(yych <= 'c') goto yy69;
				goto yy453;
			} else {
				if(yych == 'n') goto yy454;
				goto yy69;
			}
		}
yy8:
		yych = *++YYCURSOR;
		if(yych <= 'P') {
			if(yych == 'N') goto yy434;
			if(yych <= 'O') goto yy69;
			goto yy435;
		} else {
			if(yych <= 'n') {
				if(yych <= 'm') goto yy69;
				goto yy434;
			} else {
				if(yych == 'p') goto yy435;
				goto yy69;
			}
		}
yy9:
		yych = *++YYCURSOR;
		switch(yych){
		case 'A':
		case 'a':	goto yy386;
		case 'E':
		case 'e':	goto yy387;
		case 'I':
		case 'i':	goto yy388;
		case 'O':
		case 'o':	goto yy389;
		case 'R':
		case 'r':	goto yy390;
		default:	goto yy69;
		}
yy10:
		yych = *++YYCURSOR;
		if(yych <= 'R') {
			if(yych <= 'N') {
				if(yych == 'H') goto yy370;
				goto yy69;
			} else {
				if(yych <= 'O') goto yy371;
				if(yych <= 'Q') goto yy69;
				goto yy372;
			}
		} else {
			if(yych <= 'n') {
				if(yych == 'h') goto yy370;
				goto yy69;
			} else {
				if(yych <= 'o') goto yy371;
				if(yych == 'r') goto yy372;
				goto yy69;
			}
		}
yy11:
		yych = *++YYCURSOR;
		if(yych <= 'L') {
			if(yych <= 'H') {
				if(yych == 'E') goto yy346;
				goto yy69;
			} else {
				if(yych <= 'I') goto yy347;
				if(yych <= 'K') goto yy69;
				goto yy348;
			}
		} else {
			if(yych <= 'h') {
				if(yych == 'e') goto yy346;
				goto yy69;
			} else {
				if(yych <= 'i') goto yy347;
				if(yych == 'l') goto yy348;
				goto yy69;
			}
		}
yy12:
		yych = *++YYCURSOR;
		switch(yych){
		case 'D':
		case 'd':	goto yy310;
		case 'F':
		case 'f':	goto yy311;
		case 'L':
		case 'l':	goto yy312;
		case 'N':
		case 'n':	goto yy313;
		case 'S':
		case 's':	goto yy314;
		case 'U':
		case 'u':	goto yy316;
		default:	goto yy69;
		}
yy13:
		yych = *++YYCURSOR;
		if(yych == 'R') goto yy301;
		if(yych == 'r') goto yy301;
		goto yy69;
yy14:
		yych = *++YYCURSOR;
		if(yych <= 'O') {
			if(yych <= 'E') {
				if(yych == 'A') goto yy264;
				if(yych <= 'D') goto yy69;
				goto yy265;
			} else {
				if(yych == 'I') goto yy266;
				if(yych <= 'N') goto yy69;
				goto yy267;
			}
		} else {
			if(yych <= 'e') {
				if(yych == 'a') goto yy264;
				if(yych <= 'd') goto yy69;
				goto yy265;
			} else {
				if(yych <= 'i') {
					if(yych <= 'h') goto yy69;
					goto yy266;
				} else {
					if(yych == 'o') goto yy267;
					goto yy69;
				}
			}
		}
yy15:
		yych = *++YYCURSOR;
		if(yych <= 'I') {
			if(yych == 'A') goto yy241;
			if(yych <= 'H') goto yy69;
			goto yy242;
		} else {
			if(yych <= 'a') {
				if(yych <= '`') goto yy69;
				goto yy241;
			} else {
				if(yych == 'i') goto yy242;
				goto yy69;
			}
		}
yy16:
		yych = *++YYCURSOR;
		if(yych == 'E') goto yy238;
		if(yych == 'e') goto yy238;
		goto yy69;
yy17:
		yych = *++YYCURSOR;
		if(yych <= 'U') {
			if(yych == 'O') goto yy231;
			if(yych <= 'T') goto yy69;
			goto yy232;
		} else {
			if(yych <= 'o') {
				if(yych <= 'n') goto yy69;
				goto yy231;
			} else {
				if(yych == 'u') goto yy232;
				goto yy69;
			}
		}
yy18:
		yych = *++YYCURSOR;
		if(yych <= 'R') {
			if(yych == 'L') goto yy222;
			if(yych <= 'Q') goto yy69;
			goto yy223;
		} else {
			if(yych <= 'l') {
				if(yych <= 'k') goto yy69;
				goto yy222;
			} else {
				if(yych == 'r') goto yy223;
				goto yy69;
			}
		}
yy19:
		yych = *++YYCURSOR;
		if(yych == 'H') goto yy217;
		if(yych == 'h') goto yy217;
		goto yy69;
yy20:
		yych = *++YYCURSOR;
		if(yych <= 'O') {
			if(yych <= 'H') {
				if(yych == 'E') goto yy192;
				goto yy69;
			} else {
				if(yych <= 'I') goto yy193;
				if(yych <= 'N') goto yy69;
				goto yy194;
			}
		} else {
			if(yych <= 'h') {
				if(yych == 'e') goto yy192;
				goto yy69;
			} else {
				if(yych <= 'i') goto yy193;
				if(yych == 'o') goto yy194;
				goto yy69;
			}
		}
yy21:
		yych = *++YYCURSOR;
		if(yych == 'A') goto yy186;
		if(yych == 'a') goto yy186;
		goto yy69;
yy22:
		yych = *++YYCURSOR;
		if(yych <= 'U') {
			if(yych <= 'Q') {
				if(yych == 'N') goto yy173;
				goto yy69;
			} else {
				if(yych <= 'R') goto yy175;
				if(yych <= 'T') goto yy69;
				goto yy177;
			}
		} else {
			if(yych <= 'q') {
				if(yych == 'n') goto yy173;
				goto yy69;
			} else {
				if(yych <= 'r') goto yy175;
				if(yych == 'u') goto yy177;
				goto yy69;
			}
		}
yy23:
		yych = *++YYCURSOR;
		if(yych <= 'Y') {
			if(yych <= 'I') {
				if(yych == 'E') goto yy148;
				if(yych <= 'H') goto yy69;
				goto yy149;
			} else {
				if(yych == 'L') goto yy150;
				if(yych <= 'X') goto yy69;
				goto yy151;
			}
		} else {
			if(yych <= 'i') {
				if(yych == 'e') goto yy148;
				if(yych <= 'h') goto yy69;
				goto yy149;
			} else {
				if(yych <= 'l') {
					if(yych <= 'k') goto yy69;
					goto yy150;
				} else {
					if(yych == 'y') goto yy151;
					goto yy69;
				}
			}
		}
yy24:
		yych = *++YYCURSOR;
		if(yych == 'R') goto yy141;
		if(yych == 'r') goto yy141;
		goto yy69;
yy25:
		yych = *++YYCURSOR;
		if(yych == 'O') goto yy137;
		if(yych == 'o') goto yy137;
		goto yy69;
yy26:
		yych = *++YYCURSOR;
		if(yych == 'E') goto yy129;
		if(yych == 'e') goto yy129;
		goto yy69;
yy27:
		yych = *++YYCURSOR;
		if(yych == 'E') goto yy110;
		if(yych == 'e') goto yy110;
		goto yy69;
yy28:
		yych = *++YYCURSOR;
		if(yych == 'E') goto yy106;
		if(yych == 'e') goto yy106;
		goto yy69;
yy29:
		yych = *++YYCURSOR;
		if(yych == 'N') goto yy102;
		if(yych == 'n') goto yy102;
		goto yy69;
yy30:
		yych = *++YYCURSOR;
		if(yych == '=') goto yy100;
		goto yy2;
yy31:
		yych = *++YYCURSOR;
		if(yych <= '<') goto yy2;
		if(yych <= '=') goto yy96;
		if(yych <= '>') goto yy98;
		goto yy2;
yy32:
		yych = *++YYCURSOR;
		if(yych == '=') goto yy94;
		goto yy2;
yy33:
		yych = *++YYCURSOR;
		if(yych == 'O') goto yy91;
		if(yych == 'o') goto yy91;
		goto yy69;
yy34:
		++YYCURSOR;
#line 245 "pdo_user_sql_tokenizer.re"
		{ RET(PU_PLUS); }
#line 693 "pdo_user_sql_tokenizer.c"
yy36:
		yyaccept = 0;
		yych = *(YYMARKER = ++YYCURSOR);
		if(yych == '.') goto yy72;
		if(yych <= '/') goto yy37;
		if(yych <= '9') goto yy89;
yy37:
#line 246 "pdo_user_sql_tokenizer.re"
		{ RET(PU_MINUS); }
#line 703 "pdo_user_sql_tokenizer.c"
yy38:
		++YYCURSOR;
#line 247 "pdo_user_sql_tokenizer.re"
		{ RET(PU_MUL); }
#line 708 "pdo_user_sql_tokenizer.c"
yy40:
		++YYCURSOR;
#line 248 "pdo_user_sql_tokenizer.re"
		{ RET(PU_DIV); }
#line 713 "pdo_user_sql_tokenizer.c"
yy42:
		++YYCURSOR;
#line 249 "pdo_user_sql_tokenizer.re"
		{ RET(PU_MOD); }
#line 718 "pdo_user_sql_tokenizer.c"
yy44:
		++YYCURSOR;
#line 250 "pdo_user_sql_tokenizer.re"
		{ RET(PU_LPAREN); }
#line 723 "pdo_user_sql_tokenizer.c"
yy46:
		++YYCURSOR;
#line 251 "pdo_user_sql_tokenizer.re"
		{ RET(PU_RPAREN); }
#line 728 "pdo_user_sql_tokenizer.c"
yy48:
		++YYCURSOR;
#line 252 "pdo_user_sql_tokenizer.re"
		{ RET(PU_COMMA); }
#line 733 "pdo_user_sql_tokenizer.c"
yy50:
		++YYCURSOR;
#line 253 "pdo_user_sql_tokenizer.re"
		{ RET(PU_EQUALS); }
#line 738 "pdo_user_sql_tokenizer.c"
yy52:
		++YYCURSOR;
#line 254 "pdo_user_sql_tokenizer.re"
		{ RET(PU_SEMICOLON); }
#line 743 "pdo_user_sql_tokenizer.c"
yy54:
		++YYCURSOR;
		if((yych = *YYCURSOR) <= '/') goto yy55;
		if(yych <= '9') goto yy73;
yy55:
#line 255 "pdo_user_sql_tokenizer.re"
		{ RET(PU_DOT); }
#line 751 "pdo_user_sql_tokenizer.c"
yy56:
		++YYCURSOR;
		if(YYLIMIT == YYCURSOR) YYFILL(1);
		yych = *YYCURSOR;
		if(yybm[0+yych] & 1) {
			goto yy56;
		}
		if(yych <= 0x00) goto yy2;
		if(yych <= '_') goto yy86;
		goto yy87;
yy58:
		++YYCURSOR;
		if(YYLIMIT == YYCURSOR) YYFILL(1);
		yych = *YYCURSOR;
		if(yybm[0+yych] & 2) {
			goto yy58;
		}
		if(yych <= 0x00) goto yy2;
		if(yych <= '[') goto yy84;
		goto yy83;
yy60:
		++YYCURSOR;
		if(YYLIMIT == YYCURSOR) YYFILL(1);
		yych = *YYCURSOR;
		if(yybm[0+yych] & 4) {
			goto yy60;
		}
		if(yych <= 0x00) goto yy2;
		if(yych <= '[') goto yy81;
		goto yy80;
yy62:
		++YYCURSOR;
		if(YYLIMIT == YYCURSOR) YYFILL(1);
		yych = *YYCURSOR;
yy63:
		if(yybm[0+yych] & 8) {
			goto yy62;
		}
		goto yy6;
yy64:
		yyaccept = 1;
		yych = *(YYMARKER = ++YYCURSOR);
		if(yych == 'X') goto yy76;
		if(yych == 'x') goto yy76;
		goto yy67;
yy65:
#line 263 "pdo_user_sql_tokenizer.re"
		{ RET(PU_LNUM); }
#line 800 "pdo_user_sql_tokenizer.c"
yy66:
		yyaccept = 1;
		YYMARKER = ++YYCURSOR;
		if((YYLIMIT - YYCURSOR) < 2) YYFILL(2);
		yych = *YYCURSOR;
yy67:
		if(yybm[0+yych] & 16) {
			goto yy66;
		}
		if(yych == '.') goto yy72;
		goto yy65;
yy68:
		++YYCURSOR;
		if(YYLIMIT == YYCURSOR) YYFILL(1);
		yych = *YYCURSOR;
yy69:
		if(yybm[0+yych] & 32) {
			goto yy68;
		}
		goto yy4;
yy70:
		++YYCURSOR;
#line 265 "pdo_user_sql_tokenizer.re"
		{ RET(PU_END); }
#line 825 "pdo_user_sql_tokenizer.c"
yy72:
		yych = *++YYCURSOR;
		if(yych <= '/') goto yy2;
		if(yych >= ':') goto yy2;
yy73:
		++YYCURSOR;
		if(YYLIMIT == YYCURSOR) YYFILL(1);
		yych = *YYCURSOR;
		if(yych <= '/') goto yy75;
		if(yych <= '9') goto yy73;
yy75:
#line 262 "pdo_user_sql_tokenizer.re"
		{ RET(PU_DNUM); }
#line 839 "pdo_user_sql_tokenizer.c"
yy76:
		yych = *++YYCURSOR;
		if(yybm[0+yych] & 64) {
			goto yy77;
		}
		goto yy2;
yy77:
		++YYCURSOR;
		if(YYLIMIT == YYCURSOR) YYFILL(1);
		yych = *YYCURSOR;
		if(yybm[0+yych] & 64) {
			goto yy77;
		}
#line 261 "pdo_user_sql_tokenizer.re"
		{ RET(PU_HNUM); }
#line 855 "pdo_user_sql_tokenizer.c"
yy80:
		++YYCURSOR;
		if(YYLIMIT == YYCURSOR) YYFILL(1);
		yych = *YYCURSOR;
		if(yych <= 'm') {
			if(yych <= '/') {
				if(yych == '\'') goto yy60;
				goto yy2;
			} else {
				if(yych <= '7') goto yy60;
				if(yych == '\\') goto yy60;
				goto yy2;
			}
		} else {
			if(yych <= 's') {
				if(yych <= 'n') goto yy60;
				if(yych == 'r') goto yy60;
				goto yy2;
			} else {
				if(yych <= 't') goto yy60;
				if(yych == 'x') goto yy60;
				goto yy2;
			}
		}
yy81:
		++YYCURSOR;
#line 259 "pdo_user_sql_tokenizer.re"
		{ RET_UNESC(PU_STRING); }
#line 884 "pdo_user_sql_tokenizer.c"
yy83:
		++YYCURSOR;
		if(YYLIMIT == YYCURSOR) YYFILL(1);
		yych = *YYCURSOR;
		if(yych <= 'm') {
			if(yych <= '/') {
				if(yych == '"') goto yy58;
				goto yy2;
			} else {
				if(yych <= '7') goto yy58;
				if(yych == '\\') goto yy58;
				goto yy2;
			}
		} else {
			if(yych <= 's') {
				if(yych <= 'n') goto yy58;
				if(yych == 'r') goto yy58;
				goto yy2;
			} else {
				if(yych <= 't') goto yy58;
				if(yych == 'x') goto yy58;
				goto yy2;
			}
		}
yy84:
		++YYCURSOR;
#line 258 "pdo_user_sql_tokenizer.re"
		{ RET_UNESC(PU_STRING); }
#line 913 "pdo_user_sql_tokenizer.c"
yy86:
		++YYCURSOR;
		if(YYLIMIT == YYCURSOR) YYFILL(1);
		yych = *YYCURSOR;
		if(yych <= 'm') {
			if(yych <= '[') {
				if(yych <= '/') goto yy2;
				if(yych <= '7') goto yy56;
				goto yy2;
			} else {
				if(yych <= '\\') goto yy56;
				if(yych == '`') goto yy56;
				goto yy2;
			}
		} else {
			if(yych <= 's') {
				if(yych <= 'n') goto yy56;
				if(yych == 'r') goto yy56;
				goto yy2;
			} else {
				if(yych <= 't') goto yy56;
				if(yych == 'x') goto yy56;
				goto yy2;
			}
		}
yy87:
		++YYCURSOR;
#line 257 "pdo_user_sql_tokenizer.re"
		{ RET_UNESC(PU_LABEL); }
#line 943 "pdo_user_sql_tokenizer.c"
yy89:
		++YYCURSOR;
		if((YYLIMIT - YYCURSOR) < 2) YYFILL(2);
		yych = *YYCURSOR;
		if(yych == '.') goto yy72;
		if(yych <= '/') goto yy2;
		if(yych <= '9') goto yy89;
		goto yy2;
yy91:
		yych = *++YYCURSOR;
		if(yych == 'R') goto yy92;
		if(yych != 'r') goto yy69;
yy92:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy68;
		}
#line 242 "pdo_user_sql_tokenizer.re"
		{ RET(PU_XOR); }
#line 963 "pdo_user_sql_tokenizer.c"
yy94:
		++YYCURSOR;
#line 236 "pdo_user_sql_tokenizer.re"
		{ RET(PU_GREATER_EQUAL); }
#line 968 "pdo_user_sql_tokenizer.c"
yy96:
		++YYCURSOR;
#line 235 "pdo_user_sql_tokenizer.re"
		{ RET(PU_LESSER_EQUAL); }
#line 973 "pdo_user_sql_tokenizer.c"
yy98:
		++YYCURSOR;
#line 234 "pdo_user_sql_tokenizer.re"
		{ RET(PU_UNEQUAL); }
#line 978 "pdo_user_sql_tokenizer.c"
yy100:
		++YYCURSOR;
#line 233 "pdo_user_sql_tokenizer.re"
		{ RET(PU_NOT_EQUAL); }
#line 983 "pdo_user_sql_tokenizer.c"
yy102:
		yych = *++YYCURSOR;
		if(yych == 'U') goto yy103;
		if(yych != 'u') goto yy69;
yy103:
		yych = *++YYCURSOR;
		if(yych == 'M') goto yy104;
		if(yych != 'm') goto yy69;
yy104:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy68;
		}
#line 230 "pdo_user_sql_tokenizer.re"
		{ RET(PU_ENUM); }
#line 999 "pdo_user_sql_tokenizer.c"
yy106:
		yych = *++YYCURSOR;
		if(yych == 'A') goto yy107;
		if(yych != 'a') goto yy69;
yy107:
		yych = *++YYCURSOR;
		if(yych == 'R') goto yy108;
		if(yych != 'r') goto yy69;
yy108:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy68;
		}
#line 216 "pdo_user_sql_tokenizer.re"
		{ RET(PU_YEAR); }
#line 1015 "pdo_user_sql_tokenizer.c"
yy110:
		yych = *++YYCURSOR;
		if(yych == 'D') goto yy111;
		if(yych != 'd') goto yy69;
yy111:
		yych = *++YYCURSOR;
		if(yych == 'I') goto yy112;
		if(yych != 'i') goto yy69;
yy112:
		yych = *++YYCURSOR;
		if(yych == 'U') goto yy113;
		if(yych != 'u') goto yy69;
yy113:
		yych = *++YYCURSOR;
		if(yych == 'M') goto yy114;
		if(yych != 'm') goto yy69;
yy114:
		yych = *++YYCURSOR;
		if(yych <= 'T') {
			if(yych <= 'H') {
				if(yych == 'B') goto yy117;
				goto yy69;
			} else {
				if(yych <= 'I') goto yy115;
				if(yych <= 'S') goto yy69;
				goto yy116;
			}
		} else {
			if(yych <= 'h') {
				if(yych == 'b') goto yy117;
				goto yy69;
			} else {
				if(yych <= 'i') goto yy115;
				if(yych == 't') goto yy116;
				goto yy69;
			}
		}
yy115:
		yych = *++YYCURSOR;
		if(yych == 'N') goto yy126;
		if(yych == 'n') goto yy126;
		goto yy69;
yy116:
		yych = *++YYCURSOR;
		if(yych == 'E') goto yy122;
		if(yych == 'e') goto yy122;
		goto yy69;
yy117:
		yych = *++YYCURSOR;
		if(yych == 'L') goto yy118;
		if(yych != 'l') goto yy69;
yy118:
		yych = *++YYCURSOR;
		if(yych == 'O') goto yy119;
		if(yych != 'o') goto yy69;
yy119:
		yych = *++YYCURSOR;
		if(yych == 'B') goto yy120;
		if(yych != 'b') goto yy69;
yy120:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy68;
		}
#line 227 "pdo_user_sql_tokenizer.re"
		{ RET(PU_MEDIUMBLOB); }
#line 1082 "pdo_user_sql_tokenizer.c"
yy122:
		yych = *++YYCURSOR;
		if(yych == 'X') goto yy123;
		if(yych != 'x') goto yy69;
yy123:
		yych = *++YYCURSOR;
		if(yych == 'T') goto yy124;
		if(yych != 't') goto yy69;
yy124:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy68;
		}
#line 223 "pdo_user_sql_tokenizer.re"
		{ RET(PU_MEDIUMTEXT); }
#line 1098 "pdo_user_sql_tokenizer.c"
yy126:
		yych = *++YYCURSOR;
		if(yych == 'T') goto yy127;
		if(yych != 't') goto yy69;
yy127:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy68;
		}
#line 206 "pdo_user_sql_tokenizer.re"
		{ RET(PU_MEDIUMINT); }
#line 1110 "pdo_user_sql_tokenizer.c"
yy129:
		yych = *++YYCURSOR;
		if(yych == 'R') goto yy130;
		if(yych != 'r') goto yy69;
yy130:
		yych = *++YYCURSOR;
		if(yych == 'O') goto yy131;
		if(yych != 'o') goto yy69;
yy131:
		yych = *++YYCURSOR;
		if(yych == 'F') goto yy132;
		if(yych != 'f') goto yy69;
yy132:
		yych = *++YYCURSOR;
		if(yych == 'I') goto yy133;
		if(yych != 'i') goto yy69;
yy133:
		yych = *++YYCURSOR;
		if(yych == 'L') goto yy134;
		if(yych != 'l') goto yy69;
yy134:
		yych = *++YYCURSOR;
		if(yych == 'L') goto yy135;
		if(yych != 'l') goto yy69;
yy135:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy68;
		}
#line 198 "pdo_user_sql_tokenizer.re"
		{ RET(PU_ZEROFILL); }
#line 1142 "pdo_user_sql_tokenizer.c"
yy137:
		yych = *++YYCURSOR;
		if(yych == 'I') goto yy138;
		if(yych != 'i') goto yy69;
yy138:
		yych = *++YYCURSOR;
		if(yych == 'N') goto yy139;
		if(yych != 'n') goto yy69;
yy139:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy68;
		}
#line 193 "pdo_user_sql_tokenizer.re"
		{ RET(PU_JOIN); }
#line 1158 "pdo_user_sql_tokenizer.c"
yy141:
		yych = *++YYCURSOR;
		if(yych == 'I') goto yy142;
		if(yych != 'i') goto yy69;
yy142:
		yych = *++YYCURSOR;
		if(yych == 'M') goto yy143;
		if(yych != 'm') goto yy69;
yy143:
		yych = *++YYCURSOR;
		if(yych == 'A') goto yy144;
		if(yych != 'a') goto yy69;
yy144:
		yych = *++YYCURSOR;
		if(yych == 'R') goto yy145;
		if(yych != 'r') goto yy69;
yy145:
		yych = *++YYCURSOR;
		if(yych == 'Y') goto yy146;
		if(yych != 'y') goto yy69;
yy146:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy68;
		}
#line 184 "pdo_user_sql_tokenizer.re"
		{ RET(PU_PRIMARY); }
#line 1186 "pdo_user_sql_tokenizer.c"
yy148:
		yych = *++YYCURSOR;
		if(yych == 'F') goto yy168;
		if(yych == 'f') goto yy168;
		goto yy69;
yy149:
		yych = *++YYCURSOR;
		if(yych <= 'T') {
			if(yych <= 'M') {
				if(yych == 'G') goto yy158;
				goto yy69;
			} else {
				if(yych <= 'N') goto yy159;
				if(yych <= 'S') goto yy69;
				goto yy156;
			}
		} else {
			if(yych <= 'm') {
				if(yych == 'g') goto yy158;
				goto yy69;
			} else {
				if(yych <= 'n') goto yy159;
				if(yych == 't') goto yy156;
				goto yy69;
			}
		}
yy150:
		yych = *++YYCURSOR;
		if(yych == 'O') goto yy153;
		if(yych == 'o') goto yy153;
		goto yy69;
yy151:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy68;
		}
#line 179 "pdo_user_sql_tokenizer.re"
		{ RET(PU_BY); }
#line 1225 "pdo_user_sql_tokenizer.c"
yy153:
		yych = *++YYCURSOR;
		if(yych == 'B') goto yy154;
		if(yych != 'b') goto yy69;
yy154:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy68;
		}
#line 225 "pdo_user_sql_tokenizer.re"
		{ RET(PU_BLOB); }
#line 1237 "pdo_user_sql_tokenizer.c"
yy156:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy68;
		}
#line 201 "pdo_user_sql_tokenizer.re"
		{ RET(PU_BIT); }
#line 1245 "pdo_user_sql_tokenizer.c"
yy158:
		yych = *++YYCURSOR;
		if(yych == 'I') goto yy164;
		if(yych == 'i') goto yy164;
		goto yy69;
yy159:
		yych = *++YYCURSOR;
		if(yych == 'A') goto yy160;
		if(yych != 'a') goto yy69;
yy160:
		yych = *++YYCURSOR;
		if(yych == 'R') goto yy161;
		if(yych != 'r') goto yy69;
yy161:
		yych = *++YYCURSOR;
		if(yych == 'Y') goto yy162;
		if(yych != 'y') goto yy69;
yy162:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy68;
		}
#line 210 "pdo_user_sql_tokenizer.re"
		{ RET(PU_BINARY); }
#line 1270 "pdo_user_sql_tokenizer.c"
yy164:
		yych = *++YYCURSOR;
		if(yych == 'N') goto yy165;
		if(yych != 'n') goto yy69;
yy165:
		yych = *++YYCURSOR;
		if(yych == 'T') goto yy166;
		if(yych != 't') goto yy69;
yy166:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy68;
		}
#line 207 "pdo_user_sql_tokenizer.re"
		{ RET(PU_BIGINT); }
#line 1286 "pdo_user_sql_tokenizer.c"
yy168:
		yych = *++YYCURSOR;
		if(yych == 'O') goto yy169;
		if(yych != 'o') goto yy69;
yy169:
		yych = *++YYCURSOR;
		if(yych == 'R') goto yy170;
		if(yych != 'r') goto yy69;
yy170:
		yych = *++YYCURSOR;
		if(yych == 'E') goto yy171;
		if(yych != 'e') goto yy69;
yy171:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy68;
		}
#line 185 "pdo_user_sql_tokenizer.re"
		{ RET(PU_BEFORE); }
#line 1306 "pdo_user_sql_tokenizer.c"
yy173:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy68;
		}
#line 194 "pdo_user_sql_tokenizer.re"
		{ RET(PU_ON); }
#line 1314 "pdo_user_sql_tokenizer.c"
yy175:
		++YYCURSOR;
		if((yych = *YYCURSOR) <= '^') {
			if(yych <= '@') {
				if(yych <= '/') goto yy176;
				if(yych <= '9') goto yy68;
			} else {
				if(yych == 'D') goto yy182;
				if(yych <= 'Z') goto yy68;
			}
		} else {
			if(yych <= 'c') {
				if(yych != '`') goto yy68;
			} else {
				if(yych <= 'd') goto yy182;
				if(yych <= 'z') goto yy68;
				if(yych >= 0x80) goto yy68;
			}
		}
yy176:
#line 241 "pdo_user_sql_tokenizer.re"
		{ RET(PU_OR); }
#line 1337 "pdo_user_sql_tokenizer.c"
yy177:
		yych = *++YYCURSOR;
		if(yych == 'T') goto yy178;
		if(yych != 't') goto yy69;
yy178:
		yych = *++YYCURSOR;
		if(yych == 'E') goto yy179;
		if(yych != 'e') goto yy69;
yy179:
		yych = *++YYCURSOR;
		if(yych == 'R') goto yy180;
		if(yych != 'r') goto yy69;
yy180:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy68;
		}
#line 190 "pdo_user_sql_tokenizer.re"
		{ RET(PU_OUTER); }
#line 1357 "pdo_user_sql_tokenizer.c"
yy182:
		yych = *++YYCURSOR;
		if(yych == 'E') goto yy183;
		if(yych != 'e') goto yy69;
yy183:
		yych = *++YYCURSOR;
		if(yych == 'R') goto yy184;
		if(yych != 'r') goto yy69;
yy184:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy68;
		}
#line 178 "pdo_user_sql_tokenizer.re"
		{ RET(PU_ORDER); }
#line 1373 "pdo_user_sql_tokenizer.c"
yy186:
		yych = *++YYCURSOR;
		if(yych == 'V') goto yy187;
		if(yych != 'v') goto yy69;
yy187:
		yych = *++YYCURSOR;
		if(yych == 'I') goto yy188;
		if(yych != 'i') goto yy69;
yy188:
		yych = *++YYCURSOR;
		if(yych == 'N') goto yy189;
		if(yych != 'n') goto yy69;
yy189:
		yych = *++YYCURSOR;
		if(yych == 'G') goto yy190;
		if(yych != 'g') goto yy69;
yy190:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy68;
		}
#line 177 "pdo_user_sql_tokenizer.re"
		{ RET(PU_HAVING); }
#line 1397 "pdo_user_sql_tokenizer.c"
yy192:
		yych = *++YYCURSOR;
		if(yych == 'F') goto yy214;
		if(yych == 'f') goto yy214;
		goto yy69;
yy193:
		yych = *++YYCURSOR;
		if(yych <= 'M') {
			if(yych == 'K') goto yy208;
			if(yych <= 'L') goto yy69;
			goto yy207;
		} else {
			if(yych <= 'k') {
				if(yych <= 'j') goto yy69;
				goto yy208;
			} else {
				if(yych == 'm') goto yy207;
				goto yy69;
			}
		}
yy194:
		yych = *++YYCURSOR;
		if(yych == 'N') goto yy195;
		if(yych != 'n') goto yy69;
yy195:
		yych = *++YYCURSOR;
		if(yych == 'G') goto yy196;
		if(yych != 'g') goto yy69;
yy196:
		yych = *++YYCURSOR;
		if(yych <= 'T') {
			if(yych == 'B') goto yy198;
			if(yych <= 'S') goto yy69;
		} else {
			if(yych <= 'b') {
				if(yych <= 'a') goto yy69;
				goto yy198;
			} else {
				if(yych != 't') goto yy69;
			}
		}
		yych = *++YYCURSOR;
		if(yych == 'E') goto yy203;
		if(yych == 'e') goto yy203;
		goto yy69;
yy198:
		yych = *++YYCURSOR;
		if(yych == 'L') goto yy199;
		if(yych != 'l') goto yy69;
yy199:
		yych = *++YYCURSOR;
		if(yych == 'O') goto yy200;
		if(yych != 'o') goto yy69;
yy200:
		yych = *++YYCURSOR;
		if(yych == 'B') goto yy201;
		if(yych != 'b') goto yy69;
yy201:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy68;
		}
#line 228 "pdo_user_sql_tokenizer.re"
		{ RET(PU_LONGBLOB); }
#line 1462 "pdo_user_sql_tokenizer.c"
yy203:
		yych = *++YYCURSOR;
		if(yych == 'X') goto yy204;
		if(yych != 'x') goto yy69;
yy204:
		yych = *++YYCURSOR;
		if(yych == 'T') goto yy205;
		if(yych != 't') goto yy69;
yy205:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy68;
		}
#line 224 "pdo_user_sql_tokenizer.re"
		{ RET(PU_LONGTEXT); }
#line 1478 "pdo_user_sql_tokenizer.c"
yy207:
		yych = *++YYCURSOR;
		if(yych == 'I') goto yy211;
		if(yych == 'i') goto yy211;
		goto yy69;
yy208:
		yych = *++YYCURSOR;
		if(yych == 'E') goto yy209;
		if(yych != 'e') goto yy69;
yy209:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy68;
		}
#line 237 "pdo_user_sql_tokenizer.re"
		{ RET(PU_LIKE); }
#line 1495 "pdo_user_sql_tokenizer.c"
yy211:
		yych = *++YYCURSOR;
		if(yych == 'T') goto yy212;
		if(yych != 't') goto yy69;
yy212:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy68;
		}
#line 176 "pdo_user_sql_tokenizer.re"
		{ RET(PU_LIMIT); }
#line 1507 "pdo_user_sql_tokenizer.c"
yy214:
		yych = *++YYCURSOR;
		if(yych == 'T') goto yy215;
		if(yych != 't') goto yy69;
yy215:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy68;
		}
#line 191 "pdo_user_sql_tokenizer.re"
		{ RET(PU_LEFT); }
#line 1519 "pdo_user_sql_tokenizer.c"
yy217:
		yych = *++YYCURSOR;
		if(yych == 'E') goto yy218;
		if(yych != 'e') goto yy69;
yy218:
		yych = *++YYCURSOR;
		if(yych == 'R') goto yy219;
		if(yych != 'r') goto yy69;
yy219:
		yych = *++YYCURSOR;
		if(yych == 'E') goto yy220;
		if(yych != 'e') goto yy69;
yy220:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy68;
		}
#line 174 "pdo_user_sql_tokenizer.re"
		{ RET(PU_WHERE); }
#line 1539 "pdo_user_sql_tokenizer.c"
yy222:
		yych = *++YYCURSOR;
		if(yych == 'O') goto yy227;
		if(yych == 'o') goto yy227;
		goto yy69;
yy223:
		yych = *++YYCURSOR;
		if(yych == 'O') goto yy224;
		if(yych != 'o') goto yy69;
yy224:
		yych = *++YYCURSOR;
		if(yych == 'M') goto yy225;
		if(yych != 'm') goto yy69;
yy225:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy68;
		}
#line 172 "pdo_user_sql_tokenizer.re"
		{ RET(PU_FROM); }
#line 1560 "pdo_user_sql_tokenizer.c"
yy227:
		yych = *++YYCURSOR;
		if(yych == 'A') goto yy228;
		if(yych != 'a') goto yy69;
yy228:
		yych = *++YYCURSOR;
		if(yych == 'T') goto yy229;
		if(yych != 't') goto yy69;
yy229:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy68;
		}
#line 219 "pdo_user_sql_tokenizer.re"
		{ RET(PU_FLOAT); }
#line 1576 "pdo_user_sql_tokenizer.c"
yy231:
		yych = *++YYCURSOR;
		if(yych == 'T') goto yy236;
		if(yych == 't') goto yy236;
		goto yy69;
yy232:
		yych = *++YYCURSOR;
		if(yych == 'L') goto yy233;
		if(yych != 'l') goto yy69;
yy233:
		yych = *++YYCURSOR;
		if(yych == 'L') goto yy234;
		if(yych != 'l') goto yy69;
yy234:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy68;
		}
#line 166 "pdo_user_sql_tokenizer.re"
		{ RET(PU_NULL); }
#line 1597 "pdo_user_sql_tokenizer.c"
yy236:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy68;
		}
#line 239 "pdo_user_sql_tokenizer.re"
		{ RET(PU_NOT); }
#line 1605 "pdo_user_sql_tokenizer.c"
yy238:
		yych = *++YYCURSOR;
		if(yych == 'Y') goto yy239;
		if(yych != 'y') goto yy69;
yy239:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy68;
		}
#line 165 "pdo_user_sql_tokenizer.re"
		{ RET(PU_KEY); }
#line 1617 "pdo_user_sql_tokenizer.c"
yy241:
		yych = *++YYCURSOR;
		if(yych <= 'R') {
			if(yych == 'L') goto yy246;
			if(yych <= 'Q') goto yy69;
			goto yy247;
		} else {
			if(yych <= 'l') {
				if(yych <= 'k') goto yy69;
				goto yy246;
			} else {
				if(yych == 'r') goto yy247;
				goto yy69;
			}
		}
yy242:
		yych = *++YYCURSOR;
		if(yych == 'E') goto yy243;
		if(yych != 'e') goto yy69;
yy243:
		yych = *++YYCURSOR;
		if(yych == 'W') goto yy244;
		if(yych != 'w') goto yy69;
yy244:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy68;
		}
#line 163 "pdo_user_sql_tokenizer.re"
		{ RET(PU_VIEW); }
#line 1648 "pdo_user_sql_tokenizer.c"
yy246:
		yych = *++YYCURSOR;
		if(yych == 'U') goto yy260;
		if(yych == 'u') goto yy260;
		goto yy69;
yy247:
		yych = *++YYCURSOR;
		if(yych <= 'C') {
			if(yych <= 'A') goto yy69;
			if(yych >= 'C') goto yy249;
		} else {
			if(yych <= 'a') goto yy69;
			if(yych <= 'b') goto yy248;
			if(yych <= 'c') goto yy249;
			goto yy69;
		}
yy248:
		yych = *++YYCURSOR;
		if(yych == 'I') goto yy254;
		if(yych == 'i') goto yy254;
		goto yy69;
yy249:
		yych = *++YYCURSOR;
		if(yych == 'H') goto yy250;
		if(yych != 'h') goto yy69;
yy250:
		yych = *++YYCURSOR;
		if(yych == 'A') goto yy251;
		if(yych != 'a') goto yy69;
yy251:
		yych = *++YYCURSOR;
		if(yych == 'R') goto yy252;
		if(yych != 'r') goto yy69;
yy252:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy68;
		}
#line 209 "pdo_user_sql_tokenizer.re"
		{ RET(PU_VARCHAR); }
#line 1689 "pdo_user_sql_tokenizer.c"
yy254:
		yych = *++YYCURSOR;
		if(yych == 'N') goto yy255;
		if(yych != 'n') goto yy69;
yy255:
		yych = *++YYCURSOR;
		if(yych == 'A') goto yy256;
		if(yych != 'a') goto yy69;
yy256:
		yych = *++YYCURSOR;
		if(yych == 'R') goto yy257;
		if(yych != 'r') goto yy69;
yy257:
		yych = *++YYCURSOR;
		if(yych == 'Y') goto yy258;
		if(yych != 'y') goto yy69;
yy258:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy68;
		}
#line 211 "pdo_user_sql_tokenizer.re"
		{ RET(PU_VARBINARY); }
#line 1713 "pdo_user_sql_tokenizer.c"
yy260:
		yych = *++YYCURSOR;
		if(yych == 'E') goto yy261;
		if(yych != 'e') goto yy69;
yy261:
		yych = *++YYCURSOR;
		if(yych == 'S') goto yy262;
		if(yych != 's') goto yy69;
yy262:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy68;
		}
#line 182 "pdo_user_sql_tokenizer.re"
		{ RET(PU_VALUES); }
#line 1729 "pdo_user_sql_tokenizer.c"
yy264:
		yych = *++YYCURSOR;
		if(yych == 'B') goto yy297;
		if(yych == 'b') goto yy297;
		goto yy69;
yy265:
		yych = *++YYCURSOR;
		if(yych == 'X') goto yy294;
		if(yych == 'x') goto yy294;
		goto yy69;
yy266:
		yych = *++YYCURSOR;
		if(yych <= 'N') {
			if(yych <= 'L') goto yy69;
			if(yych <= 'M') goto yy270;
			goto yy269;
		} else {
			if(yych <= 'l') goto yy69;
			if(yych <= 'm') goto yy270;
			if(yych <= 'n') goto yy269;
			goto yy69;
		}
yy267:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy68;
		}
#line 181 "pdo_user_sql_tokenizer.re"
		{ RET(PU_TO); }
#line 1759 "pdo_user_sql_tokenizer.c"
yy269:
		yych = *++YYCURSOR;
		if(yych == 'Y') goto yy279;
		if(yych == 'y') goto yy279;
		goto yy69;
yy270:
		yych = *++YYCURSOR;
		if(yych == 'E') goto yy271;
		if(yych != 'e') goto yy69;
yy271:
		++YYCURSOR;
		if((yych = *YYCURSOR) <= '^') {
			if(yych <= '@') {
				if(yych <= '/') goto yy272;
				if(yych <= '9') goto yy68;
			} else {
				if(yych == 'S') goto yy273;
				if(yych <= 'Z') goto yy68;
			}
		} else {
			if(yych <= 'r') {
				if(yych != '`') goto yy68;
			} else {
				if(yych <= 's') goto yy273;
				if(yych <= 'z') goto yy68;
				if(yych >= 0x80) goto yy68;
			}
		}
yy272:
#line 214 "pdo_user_sql_tokenizer.re"
		{ RET(PU_TIME); }
#line 1791 "pdo_user_sql_tokenizer.c"
yy273:
		yych = *++YYCURSOR;
		if(yych == 'T') goto yy274;
		if(yych != 't') goto yy69;
yy274:
		yych = *++YYCURSOR;
		if(yych == 'A') goto yy275;
		if(yych != 'a') goto yy69;
yy275:
		yych = *++YYCURSOR;
		if(yych == 'M') goto yy276;
		if(yych != 'm') goto yy69;
yy276:
		yych = *++YYCURSOR;
		if(yych == 'P') goto yy277;
		if(yych != 'p') goto yy69;
yy277:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy68;
		}
#line 215 "pdo_user_sql_tokenizer.re"
		{ RET(PU_TIMESTAMP); }
#line 1815 "pdo_user_sql_tokenizer.c"
yy279:
		yych = *++YYCURSOR;
		if(yych <= 'T') {
			if(yych <= 'H') {
				if(yych == 'B') goto yy282;
				goto yy69;
			} else {
				if(yych <= 'I') goto yy280;
				if(yych <= 'S') goto yy69;
				goto yy281;
			}
		} else {
			if(yych <= 'h') {
				if(yych == 'b') goto yy282;
				goto yy69;
			} else {
				if(yych <= 'i') goto yy280;
				if(yych == 't') goto yy281;
				goto yy69;
			}
		}
yy280:
		yych = *++YYCURSOR;
		if(yych == 'N') goto yy291;
		if(yych == 'n') goto yy291;
		goto yy69;
yy281:
		yych = *++YYCURSOR;
		if(yych == 'E') goto yy287;
		if(yych == 'e') goto yy287;
		goto yy69;
yy282:
		yych = *++YYCURSOR;
		if(yych == 'L') goto yy283;
		if(yych != 'l') goto yy69;
yy283:
		yych = *++YYCURSOR;
		if(yych == 'O') goto yy284;
		if(yych != 'o') goto yy69;
yy284:
		yych = *++YYCURSOR;
		if(yych == 'B') goto yy285;
		if(yych != 'b') goto yy69;
yy285:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy68;
		}
#line 226 "pdo_user_sql_tokenizer.re"
		{ RET(PU_TINYBLOB); }
#line 1866 "pdo_user_sql_tokenizer.c"
yy287:
		yych = *++YYCURSOR;
		if(yych == 'X') goto yy288;
		if(yych != 'x') goto yy69;
yy288:
		yych = *++YYCURSOR;
		if(yych == 'T') goto yy289;
		if(yych != 't') goto yy69;
yy289:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy68;
		}
#line 222 "pdo_user_sql_tokenizer.re"
		{ RET(PU_TINYTEXT); }
#line 1882 "pdo_user_sql_tokenizer.c"
yy291:
		yych = *++YYCURSOR;
		if(yych == 'T') goto yy292;
		if(yych != 't') goto yy69;
yy292:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy68;
		}
#line 204 "pdo_user_sql_tokenizer.re"
		{ RET(PU_TINYINT); }
#line 1894 "pdo_user_sql_tokenizer.c"
yy294:
		yych = *++YYCURSOR;
		if(yych == 'T') goto yy295;
		if(yych != 't') goto yy69;
yy295:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy68;
		}
#line 221 "pdo_user_sql_tokenizer.re"
		{ RET(PU_TEXT); }
#line 1906 "pdo_user_sql_tokenizer.c"
yy297:
		yych = *++YYCURSOR;
		if(yych == 'L') goto yy298;
		if(yych != 'l') goto yy69;
yy298:
		yych = *++YYCURSOR;
		if(yych == 'E') goto yy299;
		if(yych != 'e') goto yy69;
yy299:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy68;
		}
#line 162 "pdo_user_sql_tokenizer.re"
		{ RET(PU_TABLE); }
#line 1922 "pdo_user_sql_tokenizer.c"
yy301:
		yych = *++YYCURSOR;
		if(yych <= 'O') {
			if(yych == 'A') goto yy302;
			if(yych <= 'N') goto yy69;
			goto yy303;
		} else {
			if(yych <= 'a') {
				if(yych <= '`') goto yy69;
			} else {
				if(yych == 'o') goto yy303;
				goto yy69;
			}
		}
yy302:
		yych = *++YYCURSOR;
		if(yych == 'N') goto yy307;
		if(yych == 'n') goto yy307;
		goto yy69;
yy303:
		yych = *++YYCURSOR;
		if(yych == 'U') goto yy304;
		if(yych != 'u') goto yy69;
yy304:
		yych = *++YYCURSOR;
		if(yych == 'P') goto yy305;
		if(yych != 'p') goto yy69;
yy305:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy68;
		}
#line 175 "pdo_user_sql_tokenizer.re"
		{ RET(PU_GROUP); }
#line 1957 "pdo_user_sql_tokenizer.c"
yy307:
		yych = *++YYCURSOR;
		if(yych == 'T') goto yy308;
		if(yych != 't') goto yy69;
yy308:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy68;
		}
#line 156 "pdo_user_sql_tokenizer.re"
		{ RET(PU_GRANT); }
#line 1969 "pdo_user_sql_tokenizer.c"
yy310:
		yych = *++YYCURSOR;
		if(yych == 'D') goto yy344;
		if(yych == 'd') goto yy344;
		goto yy69;
yy311:
		yych = *++YYCURSOR;
		if(yych == 'T') goto yy340;
		if(yych == 't') goto yy340;
		goto yy69;
yy312:
		yych = *++YYCURSOR;
		if(yych <= 'T') {
			if(yych == 'L') goto yy335;
			if(yych <= 'S') goto yy69;
			goto yy334;
		} else {
			if(yych <= 'l') {
				if(yych <= 'k') goto yy69;
				goto yy335;
			} else {
				if(yych == 't') goto yy334;
				goto yy69;
			}
		}
yy313:
		yych = *++YYCURSOR;
		if(yych == 'D') goto yy332;
		if(yych == 'd') goto yy332;
		goto yy69;
yy314:
		++YYCURSOR;
		if((yych = *YYCURSOR) <= '^') {
			if(yych <= '@') {
				if(yych <= '/') goto yy315;
				if(yych <= '9') goto yy68;
			} else {
				if(yych == 'C') goto yy330;
				if(yych <= 'Z') goto yy68;
			}
		} else {
			if(yych <= 'b') {
				if(yych != '`') goto yy68;
			} else {
				if(yych <= 'c') goto yy330;
				if(yych <= 'z') goto yy68;
				if(yych >= 0x80) goto yy68;
			}
		}
yy315:
#line 180 "pdo_user_sql_tokenizer.re"
		{ RET(PU_AS); }
#line 2022 "pdo_user_sql_tokenizer.c"
yy316:
		yych = *++YYCURSOR;
		if(yych == 'T') goto yy317;
		if(yych != 't') goto yy69;
yy317:
		yych = *++YYCURSOR;
		if(yych == 'O') goto yy318;
		if(yych != 'o') goto yy69;
yy318:
		yych = *++YYCURSOR;
		if(yych != '_') goto yy69;
		yych = *++YYCURSOR;
		if(yych == 'I') goto yy320;
		if(yych != 'i') goto yy69;
yy320:
		yych = *++YYCURSOR;
		if(yych == 'N') goto yy321;
		if(yych != 'n') goto yy69;
yy321:
		yych = *++YYCURSOR;
		if(yych == 'C') goto yy322;
		if(yych != 'c') goto yy69;
yy322:
		yych = *++YYCURSOR;
		if(yych == 'R') goto yy323;
		if(yych != 'r') goto yy69;
yy323:
		yych = *++YYCURSOR;
		if(yych == 'E') goto yy324;
		if(yych != 'e') goto yy69;
yy324:
		yych = *++YYCURSOR;
		if(yych == 'M') goto yy325;
		if(yych != 'm') goto yy69;
yy325:
		yych = *++YYCURSOR;
		if(yych == 'E') goto yy326;
		if(yych != 'e') goto yy69;
yy326:
		yych = *++YYCURSOR;
		if(yych == 'N') goto yy327;
		if(yych != 'n') goto yy69;
yy327:
		yych = *++YYCURSOR;
		if(yych == 'T') goto yy328;
		if(yych != 't') goto yy69;
yy328:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy68;
		}
#line 167 "pdo_user_sql_tokenizer.re"
		{ RET(PU_AUTO_INCREMENT); }
#line 2076 "pdo_user_sql_tokenizer.c"
yy330:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy68;
		}
#line 195 "pdo_user_sql_tokenizer.re"
		{ RET(PU_ASC); }
#line 2084 "pdo_user_sql_tokenizer.c"
yy332:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy68;
		}
#line 240 "pdo_user_sql_tokenizer.re"
		{ RET(PU_AND); }
#line 2092 "pdo_user_sql_tokenizer.c"
yy334:
		yych = *++YYCURSOR;
		if(yych == 'E') goto yy337;
		if(yych == 'e') goto yy337;
		goto yy69;
yy335:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy68;
		}
#line 168 "pdo_user_sql_tokenizer.re"
		{ RET(PU_ALL); }
#line 2105 "pdo_user_sql_tokenizer.c"
yy337:
		yych = *++YYCURSOR;
		if(yych == 'R') goto yy338;
		if(yych != 'r') goto yy69;
yy338:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy68;
		}
#line 155 "pdo_user_sql_tokenizer.re"
		{ RET(PU_ALTER); }
#line 2117 "pdo_user_sql_tokenizer.c"
yy340:
		yych = *++YYCURSOR;
		if(yych == 'E') goto yy341;
		if(yych != 'e') goto yy69;
yy341:
		yych = *++YYCURSOR;
		if(yych == 'R') goto yy342;
		if(yych != 'r') goto yy69;
yy342:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy68;
		}
#line 186 "pdo_user_sql_tokenizer.re"
		{ RET(PU_AFTER); }
#line 2133 "pdo_user_sql_tokenizer.c"
yy344:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy68;
		}
#line 158 "pdo_user_sql_tokenizer.re"
		{ RET(PU_ADD); }
#line 2141 "pdo_user_sql_tokenizer.c"
yy346:
		yych = *++YYCURSOR;
		if(yych <= 'V') {
			if(yych <= 'M') {
				if(yych == 'A') goto yy359;
				goto yy69;
			} else {
				if(yych <= 'N') goto yy357;
				if(yych <= 'U') goto yy69;
				goto yy358;
			}
		} else {
			if(yych <= 'm') {
				if(yych == 'a') goto yy359;
				goto yy69;
			} else {
				if(yych <= 'n') goto yy357;
				if(yych == 'v') goto yy358;
				goto yy69;
			}
		}
yy347:
		yych = *++YYCURSOR;
		if(yych == 'G') goto yy353;
		if(yych == 'g') goto yy353;
		goto yy69;
yy348:
		yych = *++YYCURSOR;
		if(yych == 'I') goto yy349;
		if(yych != 'i') goto yy69;
yy349:
		yych = *++YYCURSOR;
		if(yych == 'K') goto yy350;
		if(yych != 'k') goto yy69;
yy350:
		yych = *++YYCURSOR;
		if(yych == 'E') goto yy351;
		if(yych != 'e') goto yy69;
yy351:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy68;
		}
#line 238 "pdo_user_sql_tokenizer.re"
		{ RET(PU_RLIKE); }
#line 2187 "pdo_user_sql_tokenizer.c"
yy353:
		yych = *++YYCURSOR;
		if(yych == 'H') goto yy354;
		if(yych != 'h') goto yy69;
yy354:
		yych = *++YYCURSOR;
		if(yych == 'T') goto yy355;
		if(yych != 't') goto yy69;
yy355:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy68;
		}
#line 192 "pdo_user_sql_tokenizer.re"
		{ RET(PU_RIGHT); }
#line 2203 "pdo_user_sql_tokenizer.c"
yy357:
		yych = *++YYCURSOR;
		if(yych == 'A') goto yy366;
		if(yych == 'a') goto yy366;
		goto yy69;
yy358:
		yych = *++YYCURSOR;
		if(yych == 'O') goto yy362;
		if(yych == 'o') goto yy362;
		goto yy69;
yy359:
		yych = *++YYCURSOR;
		if(yych == 'L') goto yy360;
		if(yych != 'l') goto yy69;
yy360:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy68;
		}
#line 217 "pdo_user_sql_tokenizer.re"
		{ RET(PU_REAL); }
#line 2225 "pdo_user_sql_tokenizer.c"
yy362:
		yych = *++YYCURSOR;
		if(yych == 'K') goto yy363;
		if(yych != 'k') goto yy69;
yy363:
		yych = *++YYCURSOR;
		if(yych == 'E') goto yy364;
		if(yych != 'e') goto yy69;
yy364:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy68;
		}
#line 157 "pdo_user_sql_tokenizer.re"
		{ RET(PU_REVOKE); }
#line 2241 "pdo_user_sql_tokenizer.c"
yy366:
		yych = *++YYCURSOR;
		if(yych == 'M') goto yy367;
		if(yych != 'm') goto yy69;
yy367:
		yych = *++YYCURSOR;
		if(yych == 'E') goto yy368;
		if(yych != 'e') goto yy69;
yy368:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy68;
		}
#line 154 "pdo_user_sql_tokenizer.re"
		{ RET(PU_RENAME); }
#line 2257 "pdo_user_sql_tokenizer.c"
yy370:
		yych = *++YYCURSOR;
		if(yych == 'A') goto yy383;
		if(yych == 'a') goto yy383;
		goto yy69;
yy371:
		yych = *++YYCURSOR;
		if(yych == 'L') goto yy378;
		if(yych == 'l') goto yy378;
		goto yy69;
yy372:
		yych = *++YYCURSOR;
		if(yych == 'E') goto yy373;
		if(yych != 'e') goto yy69;
yy373:
		yych = *++YYCURSOR;
		if(yych == 'A') goto yy374;
		if(yych != 'a') goto yy69;
yy374:
		yych = *++YYCURSOR;
		if(yych == 'T') goto yy375;
		if(yych != 't') goto yy69;
yy375:
		yych = *++YYCURSOR;
		if(yych == 'E') goto yy376;
		if(yych != 'e') goto yy69;
yy376:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy68;
		}
#line 153 "pdo_user_sql_tokenizer.re"
		{ RET(PU_CREATE); }
#line 2291 "pdo_user_sql_tokenizer.c"
yy378:
		yych = *++YYCURSOR;
		if(yych == 'U') goto yy379;
		if(yych != 'u') goto yy69;
yy379:
		yych = *++YYCURSOR;
		if(yych == 'M') goto yy380;
		if(yych != 'm') goto yy69;
yy380:
		yych = *++YYCURSOR;
		if(yych == 'N') goto yy381;
		if(yych != 'n') goto yy69;
yy381:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy68;
		}
#line 164 "pdo_user_sql_tokenizer.re"
		{ RET(PU_COLUMN); }
#line 2311 "pdo_user_sql_tokenizer.c"
yy383:
		yych = *++YYCURSOR;
		if(yych == 'R') goto yy384;
		if(yych != 'r') goto yy69;
yy384:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy68;
		}
#line 208 "pdo_user_sql_tokenizer.re"
		{ RET(PU_CHAR); }
#line 2323 "pdo_user_sql_tokenizer.c"
yy386:
		yych = *++YYCURSOR;
		if(yych == 'T') goto yy426;
		if(yych == 't') goto yy426;
		goto yy69;
yy387:
		yych = *++YYCURSOR;
		if(yych <= 'S') {
			if(yych <= 'F') {
				if(yych == 'C') goto yy409;
				if(yych <= 'E') goto yy69;
				goto yy407;
			} else {
				if(yych == 'L') goto yy406;
				if(yych <= 'R') goto yy69;
				goto yy408;
			}
		} else {
			if(yych <= 'f') {
				if(yych == 'c') goto yy409;
				if(yych <= 'e') goto yy69;
				goto yy407;
			} else {
				if(yych <= 'l') {
					if(yych <= 'k') goto yy69;
					goto yy406;
				} else {
					if(yych == 's') goto yy408;
					goto yy69;
				}
			}
		}
yy388:
		yych = *++YYCURSOR;
		if(yych == 'S') goto yy399;
		if(yych == 's') goto yy399;
		goto yy69;
yy389:
		yych = *++YYCURSOR;
		if(yych == 'U') goto yy394;
		if(yych == 'u') goto yy394;
		goto yy69;
yy390:
		yych = *++YYCURSOR;
		if(yych == 'O') goto yy391;
		if(yych != 'o') goto yy69;
yy391:
		yych = *++YYCURSOR;
		if(yych == 'P') goto yy392;
		if(yych != 'p') goto yy69;
yy392:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy68;
		}
#line 159 "pdo_user_sql_tokenizer.re"
		{ RET(PU_DROP); }
#line 2381 "pdo_user_sql_tokenizer.c"
yy394:
		yych = *++YYCURSOR;
		if(yych == 'B') goto yy395;
		if(yych != 'b') goto yy69;
yy395:
		yych = *++YYCURSOR;
		if(yych == 'L') goto yy396;
		if(yych != 'l') goto yy69;
yy396:
		yych = *++YYCURSOR;
		if(yych == 'E') goto yy397;
		if(yych != 'e') goto yy69;
yy397:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy68;
		}
#line 218 "pdo_user_sql_tokenizer.re"
		{ RET(PU_DOUBLE); }
#line 2401 "pdo_user_sql_tokenizer.c"
yy399:
		yych = *++YYCURSOR;
		if(yych == 'T') goto yy400;
		if(yych != 't') goto yy69;
yy400:
		yych = *++YYCURSOR;
		if(yych == 'I') goto yy401;
		if(yych != 'i') goto yy69;
yy401:
		yych = *++YYCURSOR;
		if(yych == 'N') goto yy402;
		if(yych != 'n') goto yy69;
yy402:
		yych = *++YYCURSOR;
		if(yych == 'C') goto yy403;
		if(yych != 'c') goto yy69;
yy403:
		yych = *++YYCURSOR;
		if(yych == 'T') goto yy404;
		if(yych != 't') goto yy69;
yy404:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy68;
		}
#line 188 "pdo_user_sql_tokenizer.re"
		{ RET(PU_DISTINCT); }
#line 2429 "pdo_user_sql_tokenizer.c"
yy406:
		yych = *++YYCURSOR;
		if(yych == 'E') goto yy422;
		if(yych == 'e') goto yy422;
		goto yy69;
yy407:
		yych = *++YYCURSOR;
		if(yych == 'A') goto yy417;
		if(yych == 'a') goto yy417;
		goto yy69;
yy408:
		yych = *++YYCURSOR;
		if(yych == 'C') goto yy415;
		if(yych == 'c') goto yy415;
		goto yy69;
yy409:
		yych = *++YYCURSOR;
		if(yych == 'I') goto yy410;
		if(yych != 'i') goto yy69;
yy410:
		yych = *++YYCURSOR;
		if(yych == 'M') goto yy411;
		if(yych != 'm') goto yy69;
yy411:
		yych = *++YYCURSOR;
		if(yych == 'A') goto yy412;
		if(yych != 'a') goto yy69;
yy412:
		yych = *++YYCURSOR;
		if(yych == 'L') goto yy413;
		if(yych != 'l') goto yy69;
yy413:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy68;
		}
#line 220 "pdo_user_sql_tokenizer.re"
		{ RET(PU_DECIMAL); }
#line 2468 "pdo_user_sql_tokenizer.c"
yy415:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy68;
		}
#line 196 "pdo_user_sql_tokenizer.re"
		{ RET(PU_DESC); }
#line 2476 "pdo_user_sql_tokenizer.c"
yy417:
		yych = *++YYCURSOR;
		if(yych == 'U') goto yy418;
		if(yych != 'u') goto yy69;
yy418:
		yych = *++YYCURSOR;
		if(yych == 'L') goto yy419;
		if(yych != 'l') goto yy69;
yy419:
		yych = *++YYCURSOR;
		if(yych == 'T') goto yy420;
		if(yych != 't') goto yy69;
yy420:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy68;
		}
#line 173 "pdo_user_sql_tokenizer.re"
		{ RET(PU_DEFAULT); }
#line 2496 "pdo_user_sql_tokenizer.c"
yy422:
		yych = *++YYCURSOR;
		if(yych == 'T') goto yy423;
		if(yych != 't') goto yy69;
yy423:
		yych = *++YYCURSOR;
		if(yych == 'E') goto yy424;
		if(yych != 'e') goto yy69;
yy424:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy68;
		}
#line 152 "pdo_user_sql_tokenizer.re"
		{ RET(PU_DELETE); }
#line 2512 "pdo_user_sql_tokenizer.c"
yy426:
		yych = *++YYCURSOR;
		if(yych == 'E') goto yy427;
		if(yych != 'e') goto yy69;
yy427:
		++YYCURSOR;
		if((yych = *YYCURSOR) <= '^') {
			if(yych <= '@') {
				if(yych <= '/') goto yy428;
				if(yych <= '9') goto yy68;
			} else {
				if(yych == 'T') goto yy429;
				if(yych <= 'Z') goto yy68;
			}
		} else {
			if(yych <= 's') {
				if(yych != '`') goto yy68;
			} else {
				if(yych <= 't') goto yy429;
				if(yych <= 'z') goto yy68;
				if(yych >= 0x80) goto yy68;
			}
		}
yy428:
#line 213 "pdo_user_sql_tokenizer.re"
		{ RET(PU_DATE); }
#line 2539 "pdo_user_sql_tokenizer.c"
yy429:
		yych = *++YYCURSOR;
		if(yych == 'I') goto yy430;
		if(yych != 'i') goto yy69;
yy430:
		yych = *++YYCURSOR;
		if(yych == 'M') goto yy431;
		if(yych != 'm') goto yy69;
yy431:
		yych = *++YYCURSOR;
		if(yych == 'E') goto yy432;
		if(yych != 'e') goto yy69;
yy432:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy68;
		}
#line 212 "pdo_user_sql_tokenizer.re"
		{ RET(PU_DATETIME); }
#line 2559 "pdo_user_sql_tokenizer.c"
yy434:
		yych = *++YYCURSOR;
		if(yych <= 'S') {
			if(yych == 'I') goto yy441;
			if(yych <= 'R') goto yy69;
			goto yy442;
		} else {
			if(yych <= 'i') {
				if(yych <= 'h') goto yy69;
				goto yy441;
			} else {
				if(yych == 's') goto yy442;
				goto yy69;
			}
		}
yy435:
		yych = *++YYCURSOR;
		if(yych == 'D') goto yy436;
		if(yych != 'd') goto yy69;
yy436:
		yych = *++YYCURSOR;
		if(yych == 'A') goto yy437;
		if(yych != 'a') goto yy69;
yy437:
		yych = *++YYCURSOR;
		if(yych == 'T') goto yy438;
		if(yych != 't') goto yy69;
yy438:
		yych = *++YYCURSOR;
		if(yych == 'E') goto yy439;
		if(yych != 'e') goto yy69;
yy439:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy68;
		}
#line 151 "pdo_user_sql_tokenizer.re"
		{ RET(PU_UPDATE); }
#line 2598 "pdo_user_sql_tokenizer.c"
yy441:
		yych = *++YYCURSOR;
		if(yych == 'Q') goto yy449;
		if(yych == 'q') goto yy449;
		goto yy69;
yy442:
		yych = *++YYCURSOR;
		if(yych == 'I') goto yy443;
		if(yych != 'i') goto yy69;
yy443:
		yych = *++YYCURSOR;
		if(yych == 'G') goto yy444;
		if(yych != 'g') goto yy69;
yy444:
		yych = *++YYCURSOR;
		if(yych == 'N') goto yy445;
		if(yych != 'n') goto yy69;
yy445:
		yych = *++YYCURSOR;
		if(yych == 'E') goto yy446;
		if(yych != 'e') goto yy69;
yy446:
		yych = *++YYCURSOR;
		if(yych == 'D') goto yy447;
		if(yych != 'd') goto yy69;
yy447:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy68;
		}
#line 197 "pdo_user_sql_tokenizer.re"
		{ RET(PU_UNSIGNED); }
#line 2631 "pdo_user_sql_tokenizer.c"
yy449:
		yych = *++YYCURSOR;
		if(yych == 'U') goto yy450;
		if(yych != 'u') goto yy69;
yy450:
		yych = *++YYCURSOR;
		if(yych == 'E') goto yy451;
		if(yych != 'e') goto yy69;
yy451:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy68;
		}
#line 183 "pdo_user_sql_tokenizer.re"
		{ RET(PU_UNIQUE); }
#line 2647 "pdo_user_sql_tokenizer.c"
yy453:
		yych = *++YYCURSOR;
		if(yych == 'E') goto yy473;
		if(yych == 'e') goto yy473;
		goto yy69;
yy454:
		yych = *++YYCURSOR;
		if(yych <= 'T') {
			if(yych <= 'N') {
				if(yych <= 'M') goto yy69;
				goto yy458;
			} else {
				if(yych <= 'R') goto yy69;
				if(yych >= 'T') goto yy456;
			}
		} else {
			if(yych <= 'r') {
				if(yych == 'n') goto yy458;
				goto yy69;
			} else {
				if(yych <= 's') goto yy455;
				if(yych <= 't') goto yy456;
				goto yy69;
			}
		}
yy455:
		yych = *++YYCURSOR;
		if(yych == 'E') goto yy469;
		if(yych == 'e') goto yy469;
		goto yy69;
yy456:
		++YYCURSOR;
		if((yych = *YYCURSOR) <= '^') {
			if(yych <= 'D') {
				if(yych <= '/') goto yy457;
				if(yych <= '9') goto yy68;
				if(yych >= 'A') goto yy68;
			} else {
				if(yych <= 'N') {
					if(yych <= 'E') goto yy462;
					goto yy68;
				} else {
					if(yych <= 'O') goto yy463;
					if(yych <= 'Z') goto yy68;
				}
			}
		} else {
			if(yych <= 'e') {
				if(yych == '`') goto yy457;
				if(yych <= 'd') goto yy68;
				goto yy462;
			} else {
				if(yych <= 'o') {
					if(yych <= 'n') goto yy68;
					goto yy463;
				} else {
					if(yych <= 'z') goto yy68;
					if(yych >= 0x80) goto yy68;
				}
			}
		}
yy457:
#line 202 "pdo_user_sql_tokenizer.re"
		{ RET(PU_INT); }
#line 2712 "pdo_user_sql_tokenizer.c"
yy458:
		yych = *++YYCURSOR;
		if(yych == 'E') goto yy459;
		if(yych != 'e') goto yy69;
yy459:
		yych = *++YYCURSOR;
		if(yych == 'R') goto yy460;
		if(yych != 'r') goto yy69;
yy460:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy68;
		}
#line 189 "pdo_user_sql_tokenizer.re"
		{ RET(PU_INNER); }
#line 2728 "pdo_user_sql_tokenizer.c"
yy462:
		yych = *++YYCURSOR;
		if(yych == 'G') goto yy465;
		if(yych == 'g') goto yy465;
		goto yy69;
yy463:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy68;
		}
#line 171 "pdo_user_sql_tokenizer.re"
		{ RET(PU_INTO); }
#line 2741 "pdo_user_sql_tokenizer.c"
yy465:
		yych = *++YYCURSOR;
		if(yych == 'E') goto yy466;
		if(yych != 'e') goto yy69;
yy466:
		yych = *++YYCURSOR;
		if(yych == 'R') goto yy467;
		if(yych != 'r') goto yy69;
yy467:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy68;
		}
#line 203 "pdo_user_sql_tokenizer.re"
		{ RET(PU_INTEGER); }
#line 2757 "pdo_user_sql_tokenizer.c"
yy469:
		yych = *++YYCURSOR;
		if(yych == 'R') goto yy470;
		if(yych != 'r') goto yy69;
yy470:
		yych = *++YYCURSOR;
		if(yych == 'T') goto yy471;
		if(yych != 't') goto yy69;
yy471:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy68;
		}
#line 150 "pdo_user_sql_tokenizer.re"
		{ RET(PU_INSERT); }
#line 2773 "pdo_user_sql_tokenizer.c"
yy473:
		yych = *++YYCURSOR;
		if(yych == 'N') goto yy474;
		if(yych != 'n') goto yy69;
yy474:
		yych = *++YYCURSOR;
		if(yych == 'T') goto yy475;
		if(yych != 't') goto yy69;
yy475:
		yych = *++YYCURSOR;
		if(yych == 'I') goto yy476;
		if(yych != 'i') goto yy69;
yy476:
		yych = *++YYCURSOR;
		if(yych == 'F') goto yy477;
		if(yych != 'f') goto yy69;
yy477:
		yych = *++YYCURSOR;
		if(yych == 'I') goto yy478;
		if(yych != 'i') goto yy69;
yy478:
		yych = *++YYCURSOR;
		if(yych == 'E') goto yy479;
		if(yych != 'e') goto yy69;
yy479:
		yych = *++YYCURSOR;
		if(yych == 'D') goto yy480;
		if(yych != 'd') goto yy69;
yy480:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy68;
		}
#line 187 "pdo_user_sql_tokenizer.re"
		{ RET(PU_IDENTIFIED); }
#line 2809 "pdo_user_sql_tokenizer.c"
yy482:
		yych = *++YYCURSOR;
		if(yych <= 'T') {
			if(yych == 'L') goto yy493;
			if(yych <= 'S') goto yy69;
			goto yy494;
		} else {
			if(yych <= 'l') {
				if(yych <= 'k') goto yy69;
				goto yy493;
			} else {
				if(yych == 't') goto yy494;
				goto yy69;
			}
		}
yy483:
		yych = *++YYCURSOR;
		if(yych == 'A') goto yy486;
		if(yych == 'a') goto yy486;
		goto yy69;
yy484:
		++YYCURSOR;
		if(YYLIMIT == YYCURSOR) YYFILL(1);
		yych = *YYCURSOR;
		if(yybm[0+yych] & 128) {
			goto yy484;
		}
		if(yych <= '9') {
			if(yych <= 0x0D) {
				if(yych <= 0x08) goto yy6;
				if(yych <= 0x0A) goto yy62;
				if(yych <= 0x0C) goto yy6;
				goto yy62;
			} else {
				if(yych == ' ') goto yy62;
				if(yych <= '/') goto yy6;
				goto yy68;
			}
		} else {
			if(yych <= '_') {
				if(yych <= '@') goto yy6;
				if(yych <= 'Z') goto yy68;
				if(yych <= '^') goto yy6;
				goto yy68;
			} else {
				if(yych <= '`') goto yy6;
				if(yych <= 'z') goto yy68;
				if(yych <= 0x7F) goto yy6;
				goto yy68;
			}
		}
yy486:
		yych = *++YYCURSOR;
		if(yych == 'L') goto yy487;
		if(yych != 'l') goto yy69;
yy487:
		yych = *++YYCURSOR;
		if(yych == 'L') goto yy488;
		if(yych != 'l') goto yy69;
yy488:
		yych = *++YYCURSOR;
		if(yych == 'I') goto yy489;
		if(yych != 'i') goto yy69;
yy489:
		yych = *++YYCURSOR;
		if(yych == 'N') goto yy490;
		if(yych != 'n') goto yy69;
yy490:
		yych = *++YYCURSOR;
		if(yych == 'T') goto yy491;
		if(yych != 't') goto yy69;
yy491:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy68;
		}
#line 205 "pdo_user_sql_tokenizer.re"
		{ RET(PU_SMALLINT); }
#line 2888 "pdo_user_sql_tokenizer.c"
yy493:
		yych = *++YYCURSOR;
		if(yych == 'E') goto yy496;
		if(yych == 'e') goto yy496;
		goto yy69;
yy494:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy68;
		}
#line 229 "pdo_user_sql_tokenizer.re"
		{ RET(PU_SET); }
#line 2901 "pdo_user_sql_tokenizer.c"
yy496:
		yych = *++YYCURSOR;
		if(yych == 'C') goto yy497;
		if(yych != 'c') goto yy69;
yy497:
		yych = *++YYCURSOR;
		if(yych == 'T') goto yy498;
		if(yych != 't') goto yy69;
yy498:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy68;
		}
#line 149 "pdo_user_sql_tokenizer.re"
		{ RET(PU_SELECT); }
#line 2917 "pdo_user_sql_tokenizer.c"
	}
}
#line 266 "pdo_user_sql_tokenizer.re"

}

#define PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(v)	{ v, #v },
 
php_pdo_user_sql_token_label php_pdo_user_sql_token_labels[] = {
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_END)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_LABEL)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_STRING)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_WHITESPACE)

	/* Verbs */
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_SELECT)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_INSERT)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_UPDATE)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_DELETE)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_CREATE)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_RENAME)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_ALTER)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_GRANT)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_REVOKE)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_ADD)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_DROP)

	/* Nouns */
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_TABLE)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_VIEW)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_COLUMN)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_KEY)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_NULL)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_AUTO_INCREMENT)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_HNUM)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_LNUM)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_ALL)

	/* Prepositions */
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_INTO)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_FROM)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(	PU_DEFAULT)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_WHERE)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_GROUP)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_LIMIT)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_HAVING)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_ORDER)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_BY)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_AS)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_TO)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_VALUES)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_UNIQUE)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_PRIMARY)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_BEFORE)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_AFTER)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_IDENTIFIED)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_DISTINCT)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_INNER)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_OUTER)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_LEFT)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_RIGHT)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_JOIN)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_ON)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_ASC)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_DESC)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_UNSIGNED)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_ZEROFILL)

	/* SQL Types */
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_BIT)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_INT)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_INTEGER)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_TINYINT)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_SMALLINT)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_MEDIUMINT)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_BIGINT)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_CHAR)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_VARCHAR)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_BINARY)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_VARBINARY)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_DATETIME)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_DATE)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_TIME)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_TIMESTAMP)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_YEAR)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_REAL)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_DECIMAL)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_DOUBLE)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_FLOAT)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_TEXT)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_TINYTEXT)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_MEDIUMTEXT)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_LONGTEXT)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_BLOB)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_TINYBLOB)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_MEDIUMBLOB)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_LONGBLOB)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_SET)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_ENUM)

	/* Logicals */
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_NOT_EQUAL) 	/* != */
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_UNEQUAL)		/* <> */
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_LESSER_EQUAL)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_GREATER_EQUAL)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_LIKE)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_RLIKE)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_NOT)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_AND)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_OR)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_XOR)

	/* Single Character Tokens */
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_PLUS)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_MINUS)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_MUL)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_DIV)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_MOD)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_LPAREN)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_RPAREN)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_COMMA)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_EQUALS)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_SEMICOLON)

	{ 0, NULL }
};
