/* Generated by re2c 0.10.2 on Sat Jun 10 16:26:33 2006 */
#line 1 "pdo_user_sql_tokenizer.re"
#include "php.h"
#include "php_pdo_user_sql.h"

static void php_pdo_user_unquote(php_pdo_user_sql_token *token)
{
	char *out = emalloc(token->token_len + 1), *p = out;
	int i;

	token->token_len--;
	for(i = 1; i < token->token_len; i++) {
		switch (token->token[i]) {
			case '\\':
				if ((i + 1) >= token->token_len) {
					/* EOL */
					*(p++) = '\\';
					goto done;
				}
				switch (token->token[++i]) {
					case 'r':	*(p++) = '\r';		goto next_iter;
					case 'n':	*(p++) = '\n';		goto next_iter;
					case 't':	*(p++) = '\t';		goto next_iter;
					case '\\':	*(p++) = '\\';		goto next_iter;
					case 'x':
					{
						unsigned char val = 0;

						if (++i >= token->token_len) {
							*(p++) = 'x';
							goto done;
						}
						if (token->token[i] >= '0' && token->token[i] <= '9') {
							val = token->token[i] - '0';
						} else if (token->token[i] >= 'A' && token->token[i] <= 'F') {
							val = 10 + token->token[i] - 'A';
						} else if (token->token[i] >= 'a' && token->token[i] <= 'f') {
							val = 10 + token->token[i] - 'a';
						} else {
							*(p++) = 'x';
							i--;
							goto next_iter;
						}
						if (++i >= token->token_len) {
							*(p++) = val;
							goto done;
						}
						if (token->token[i] >= '0' && token->token[i] <= '9') {
							val <<= 4;
							val |= token->token[i] - '0';
						} else if (token->token[i] >= 'A' && token->token[i] <= 'F') {
							val <<= 4;
							val |= 10 + token->token[i] - 'A';
						} else if (token->token[i] >= 'a' && token->token[i] <= 'f') {
							val <<= 4;
							val |= 10 + token->token[i] - 'a';
						} else {
							*(p++) = val;
							i--;
							goto next_iter;
						}
						*(p++) = val;
						goto next_iter;
					}
					default: /* local-quote, octal and literal */
					{
						unsigned char val = 0;

						if (token->token[i] == token->token[0]) {
							/* local-quote */
							*(p++) = token->token[i];
							goto next_iter;
						} else if (token->token[i] >= '0' && token->token[i] <= '7') {
							/* Octit #1 */
							val = token->token[i] - '0';
						} else {
							/* not a normal escape sequence */
							*(p++) = '\\';
							*(p++) = token->token[i];
							goto next_iter;
						}

						if (++i >= token->token_len) {
							*(p++) = val;
							goto done;
						}
						if (token->token[i] >= '0' && token->token[i] <= '7') {
							/* Octit #2 */
							val <<= 3;
							val |= token->token[i] - '0';
						} else {
							/* This was a single octit value, back up */
							*(p++) = val;
							i--;
							goto next_iter;
						}
						if (val > 0x1F) {
							*(p++) = val;
							goto next_iter;
						}
						if (++i >= token->token_len) {
							*(p++) = val;
							goto done;
						}
						if (token->token[i] >= '0' && token->token[i] <= '7') {
							/* Octit #3 */
							val <<= 3;
							val |= token->token[i] - '0';
						} else {
							/* This was a two-octit value, back up */
							*(p++) = val;
							i--;
							goto next_iter;
						}
						*(p++) = val;
						goto next_iter;
					}
				}
			default:
				*(p++) = token->token[i];
		}
next_iter:
		continue; /* avoids warning */
	}

done:
	token->token = out;
	token->token_len = p - out;
	*p = 0;

	token->freeme = 1;
}

#define RET(num) { token->token_len = t->start - token->token; token->id = num; return (num); }
#define RET_UNESC(num) { token->token_len = t->start - token->token; token->id = num; php_pdo_user_unquote(token); return (num); }

#define YYCTYPE		char
#define YYCURSOR	(t->start)
#define YYLIMIT		(t->end)
#define YYFILL(n)	
#define YYMARKER	marker

int php_pdo_user_sql_get_token(php_pdo_user_sql_tokenizer *t, php_pdo_user_sql_token *token)
{
	token->freeme = 0;
	token->token = t->start;
	char *marker = t->start;

{
	static unsigned char yybm[] = {
		  0,   7,   7,   7,   7,   7,   7,   7, 
		  7,  15,  15,   7,   7,  15,   7,   7, 
		  7,   7,   7,   7,   7,   7,   7,   7, 
		  7,   7,   7,   7,   7,   7,   7,   7, 
		 15,   7,   5,   7,   7,   7,   7,   3, 
		  7,   7,   7,   7,   7,   7,   7,   7, 
		119, 119, 119, 119, 119, 119, 119, 119, 
		119, 119,   7,   7,   7,   7,   7,   7, 
		  7, 103, 103, 103, 103, 103, 103,  39, 
		 39,  39,  39,  39,  39,  39,  39,  39, 
		 39,  39,  39,  39,  39,  39,  39,  39, 
		 39,  39,  39,   7,   0,   7,   7,  39, 
		  6, 103, 103, 103, 103, 103, 103,  39, 
		 39,  39,  39,  39,  39,  39,  39,  39, 
		 39,  39,  39, 175,  39,  39,  39,  39, 
		 39,  39,  39,   7,   7,   7,   7,   7, 
		 39,  39,  39,  39,  39,  39,  39,  39, 
		 39,  39,  39,  39,  39,  39,  39,  39, 
		 39,  39,  39,  39,  39,  39,  39,  39, 
		 39,  39,  39,  39,  39,  39,  39,  39, 
		 39,  39,  39,  39,  39,  39,  39,  39, 
		 39,  39,  39,  39,  39,  39,  39,  39, 
		 39,  39,  39,  39,  39,  39,  39,  39, 
		 39,  39,  39,  39,  39,  39,  39,  39, 
		 39,  39,  39,  39,  39,  39,  39,  39, 
		 39,  39,  39,  39,  39,  39,  39,  39, 
		 39,  39,  39,  39,  39,  39,  39,  39, 
		 39,  39,  39,  39,  39,  39,  39,  39, 
		 39,  39,  39,  39,  39,  39,  39,  39, 
		 39,  39,  39,  39,  39,  39,  39,  39, 
		 39,  39,  39,  39,  39,  39,  39,  39, 
		 39,  39,  39,  39,  39,  39,  39,  39, 
	};

#line 186 "pdo_user_sql_tokenizer.c"
	{
		YYCTYPE yych;
		unsigned int yyaccept = 0;

		if((YYLIMIT - YYCURSOR) < 15) YYFILL(15);
		yych = *YYCURSOR;
		switch(yych){
		case 0x00:	goto yy72;
		case 0x01:
		case 0x02:
		case 0x03:
		case 0x04:
		case 0x05:
		case 0x06:
		case 0x07:
		case 0x08:
		case 0x0B:
		case 0x0C:
		case 0x0E:
		case 0x0F:
		case 0x10:
		case 0x11:
		case 0x12:
		case 0x13:
		case 0x14:
		case 0x15:
		case 0x16:
		case 0x17:
		case 0x18:
		case 0x19:
		case 0x1A:
		case 0x1B:
		case 0x1C:
		case 0x1D:
		case 0x1E:
		case 0x1F:
		case '#':
		case '$':
		case '&':
		case '?':
		case '@':
		case '[':
		case '\\':
		case ']':
		case '^':
		case '{':
		case '|':
		case '}':
		case '~':
		case 0x7F:	goto yy2;
		case 0x09:
		case 0x0A:
		case 0x0D:
		case ' ':	goto yy64;
		case '!':	goto yy30;
		case '"':	goto yy60;
		case '%':	goto yy42;
		case '\'':	goto yy62;
		case '(':	goto yy44;
		case ')':	goto yy46;
		case '*':	goto yy38;
		case '+':	goto yy34;
		case ',':	goto yy48;
		case '-':	goto yy36;
		case '.':	goto yy54;
		case '/':	goto yy40;
		case '0':	goto yy66;
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':	goto yy68;
		case ':':	goto yy56;
		case ';':	goto yy52;
		case '<':	goto yy31;
		case '=':	goto yy50;
		case '>':	goto yy32;
		case 'A':
		case 'a':	goto yy12;
		case 'B':
		case 'b':	goto yy23;
		case 'C':
		case 'c':	goto yy10;
		case 'D':
		case 'd':	goto yy9;
		case 'E':
		case 'e':	goto yy29;
		case 'F':
		case 'f':	goto yy18;
		case 'G':
		case 'g':	goto yy13;
		case 'H':
		case 'h':	goto yy21;
		case 'I':
		case 'i':	goto yy7;
		case 'J':
		case 'j':	goto yy25;
		case 'K':
		case 'k':	goto yy16;
		case 'L':
		case 'l':	goto yy20;
		case 'M':
		case 'm':	goto yy27;
		case 'N':
		case 'n':	goto yy17;
		case 'O':
		case 'o':	goto yy22;
		case 'P':
		case 'p':	goto yy24;
		case 'R':
		case 'r':	goto yy11;
		case 'S':	goto yy3;
		case 'T':
		case 't':	goto yy14;
		case 'U':
		case 'u':	goto yy8;
		case 'V':
		case 'v':	goto yy15;
		case 'W':
		case 'w':	goto yy19;
		case 'X':
		case 'x':	goto yy33;
		case 'Y':
		case 'y':	goto yy28;
		case 'Z':
		case 'z':	goto yy26;
		case '`':	goto yy58;
		case 's':	goto yy5;
		default:	goto yy70;
		}
yy2:
		YYCURSOR = YYMARKER;
		switch(yyaccept) {
		case 0:	goto yy37;
		case 1:	goto yy67;
		}
yy3:
		++YYCURSOR;
		if((yych = *YYCURSOR) <= 'M') {
			if(yych == 'E') goto yy484;
			if(yych <= 'L') goto yy71;
			goto yy485;
		} else {
			if(yych <= 'e') {
				if(yych <= 'd') goto yy71;
				goto yy484;
			} else {
				if(yych == 'm') goto yy485;
				goto yy71;
			}
		}
yy4:
#line 276 "pdo_user_sql_tokenizer.re"
		{ RET(PU_LABEL); }
#line 345 "pdo_user_sql_tokenizer.c"
yy5:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 128) {
			goto yy486;
		}
		if(yych <= '^') {
			if(yych <= 'D') {
				if(yych <= '/') goto yy65;
				if(yych <= '9') goto yy70;
				if(yych <= '@') goto yy65;
				goto yy70;
			} else {
				if(yych <= 'L') {
					if(yych <= 'E') goto yy484;
					goto yy70;
				} else {
					if(yych <= 'M') goto yy485;
					if(yych <= 'Z') goto yy70;
					goto yy65;
				}
			}
		} else {
			if(yych <= 'e') {
				if(yych == '`') goto yy65;
				if(yych <= 'd') goto yy70;
				goto yy484;
			} else {
				if(yych <= 'm') {
					if(yych <= 'l') goto yy70;
					goto yy485;
				} else {
					if(yych <= 'z') goto yy70;
					if(yych <= 0x7F) goto yy65;
					goto yy70;
				}
			}
		}
yy6:
#line 272 "pdo_user_sql_tokenizer.re"
		{ RET(PU_WHITESPACE); }
#line 386 "pdo_user_sql_tokenizer.c"
yy7:
		yych = *++YYCURSOR;
		if(yych <= 'N') {
			if(yych == 'D') goto yy455;
			if(yych <= 'M') goto yy71;
			goto yy456;
		} else {
			if(yych <= 'd') {
				if(yych <= 'c') goto yy71;
				goto yy455;
			} else {
				if(yych == 'n') goto yy456;
				goto yy71;
			}
		}
yy8:
		yych = *++YYCURSOR;
		if(yych <= 'P') {
			if(yych == 'N') goto yy436;
			if(yych <= 'O') goto yy71;
			goto yy437;
		} else {
			if(yych <= 'n') {
				if(yych <= 'm') goto yy71;
				goto yy436;
			} else {
				if(yych == 'p') goto yy437;
				goto yy71;
			}
		}
yy9:
		yych = *++YYCURSOR;
		switch(yych){
		case 'A':
		case 'a':	goto yy388;
		case 'E':
		case 'e':	goto yy389;
		case 'I':
		case 'i':	goto yy390;
		case 'O':
		case 'o':	goto yy391;
		case 'R':
		case 'r':	goto yy392;
		default:	goto yy71;
		}
yy10:
		yych = *++YYCURSOR;
		if(yych <= 'R') {
			if(yych <= 'N') {
				if(yych == 'H') goto yy372;
				goto yy71;
			} else {
				if(yych <= 'O') goto yy373;
				if(yych <= 'Q') goto yy71;
				goto yy374;
			}
		} else {
			if(yych <= 'n') {
				if(yych == 'h') goto yy372;
				goto yy71;
			} else {
				if(yych <= 'o') goto yy373;
				if(yych == 'r') goto yy374;
				goto yy71;
			}
		}
yy11:
		yych = *++YYCURSOR;
		if(yych <= 'L') {
			if(yych <= 'H') {
				if(yych == 'E') goto yy348;
				goto yy71;
			} else {
				if(yych <= 'I') goto yy349;
				if(yych <= 'K') goto yy71;
				goto yy350;
			}
		} else {
			if(yych <= 'h') {
				if(yych == 'e') goto yy348;
				goto yy71;
			} else {
				if(yych <= 'i') goto yy349;
				if(yych == 'l') goto yy350;
				goto yy71;
			}
		}
yy12:
		yych = *++YYCURSOR;
		switch(yych){
		case 'D':
		case 'd':	goto yy312;
		case 'F':
		case 'f':	goto yy313;
		case 'L':
		case 'l':	goto yy314;
		case 'N':
		case 'n':	goto yy315;
		case 'S':
		case 's':	goto yy316;
		case 'U':
		case 'u':	goto yy318;
		default:	goto yy71;
		}
yy13:
		yych = *++YYCURSOR;
		if(yych == 'R') goto yy303;
		if(yych == 'r') goto yy303;
		goto yy71;
yy14:
		yych = *++YYCURSOR;
		if(yych <= 'O') {
			if(yych <= 'E') {
				if(yych == 'A') goto yy266;
				if(yych <= 'D') goto yy71;
				goto yy267;
			} else {
				if(yych == 'I') goto yy268;
				if(yych <= 'N') goto yy71;
				goto yy269;
			}
		} else {
			if(yych <= 'e') {
				if(yych == 'a') goto yy266;
				if(yych <= 'd') goto yy71;
				goto yy267;
			} else {
				if(yych <= 'i') {
					if(yych <= 'h') goto yy71;
					goto yy268;
				} else {
					if(yych == 'o') goto yy269;
					goto yy71;
				}
			}
		}
yy15:
		yych = *++YYCURSOR;
		if(yych <= 'I') {
			if(yych == 'A') goto yy243;
			if(yych <= 'H') goto yy71;
			goto yy244;
		} else {
			if(yych <= 'a') {
				if(yych <= '`') goto yy71;
				goto yy243;
			} else {
				if(yych == 'i') goto yy244;
				goto yy71;
			}
		}
yy16:
		yych = *++YYCURSOR;
		if(yych == 'E') goto yy240;
		if(yych == 'e') goto yy240;
		goto yy71;
yy17:
		yych = *++YYCURSOR;
		if(yych <= 'U') {
			if(yych == 'O') goto yy233;
			if(yych <= 'T') goto yy71;
			goto yy234;
		} else {
			if(yych <= 'o') {
				if(yych <= 'n') goto yy71;
				goto yy233;
			} else {
				if(yych == 'u') goto yy234;
				goto yy71;
			}
		}
yy18:
		yych = *++YYCURSOR;
		if(yych <= 'R') {
			if(yych == 'L') goto yy224;
			if(yych <= 'Q') goto yy71;
			goto yy225;
		} else {
			if(yych <= 'l') {
				if(yych <= 'k') goto yy71;
				goto yy224;
			} else {
				if(yych == 'r') goto yy225;
				goto yy71;
			}
		}
yy19:
		yych = *++YYCURSOR;
		if(yych == 'H') goto yy219;
		if(yych == 'h') goto yy219;
		goto yy71;
yy20:
		yych = *++YYCURSOR;
		if(yych <= 'O') {
			if(yych <= 'H') {
				if(yych == 'E') goto yy194;
				goto yy71;
			} else {
				if(yych <= 'I') goto yy195;
				if(yych <= 'N') goto yy71;
				goto yy196;
			}
		} else {
			if(yych <= 'h') {
				if(yych == 'e') goto yy194;
				goto yy71;
			} else {
				if(yych <= 'i') goto yy195;
				if(yych == 'o') goto yy196;
				goto yy71;
			}
		}
yy21:
		yych = *++YYCURSOR;
		if(yych == 'A') goto yy188;
		if(yych == 'a') goto yy188;
		goto yy71;
yy22:
		yych = *++YYCURSOR;
		if(yych <= 'U') {
			if(yych <= 'Q') {
				if(yych == 'N') goto yy175;
				goto yy71;
			} else {
				if(yych <= 'R') goto yy177;
				if(yych <= 'T') goto yy71;
				goto yy179;
			}
		} else {
			if(yych <= 'q') {
				if(yych == 'n') goto yy175;
				goto yy71;
			} else {
				if(yych <= 'r') goto yy177;
				if(yych == 'u') goto yy179;
				goto yy71;
			}
		}
yy23:
		yych = *++YYCURSOR;
		if(yych <= 'Y') {
			if(yych <= 'I') {
				if(yych == 'E') goto yy150;
				if(yych <= 'H') goto yy71;
				goto yy151;
			} else {
				if(yych == 'L') goto yy152;
				if(yych <= 'X') goto yy71;
				goto yy153;
			}
		} else {
			if(yych <= 'i') {
				if(yych == 'e') goto yy150;
				if(yych <= 'h') goto yy71;
				goto yy151;
			} else {
				if(yych <= 'l') {
					if(yych <= 'k') goto yy71;
					goto yy152;
				} else {
					if(yych == 'y') goto yy153;
					goto yy71;
				}
			}
		}
yy24:
		yych = *++YYCURSOR;
		if(yych == 'R') goto yy143;
		if(yych == 'r') goto yy143;
		goto yy71;
yy25:
		yych = *++YYCURSOR;
		if(yych == 'O') goto yy139;
		if(yych == 'o') goto yy139;
		goto yy71;
yy26:
		yych = *++YYCURSOR;
		if(yych == 'E') goto yy131;
		if(yych == 'e') goto yy131;
		goto yy71;
yy27:
		yych = *++YYCURSOR;
		if(yych == 'E') goto yy112;
		if(yych == 'e') goto yy112;
		goto yy71;
yy28:
		yych = *++YYCURSOR;
		if(yych == 'E') goto yy108;
		if(yych == 'e') goto yy108;
		goto yy71;
yy29:
		yych = *++YYCURSOR;
		if(yych == 'N') goto yy104;
		if(yych == 'n') goto yy104;
		goto yy71;
yy30:
		yych = *++YYCURSOR;
		if(yych == '=') goto yy102;
		goto yy2;
yy31:
		yych = *++YYCURSOR;
		if(yych <= '<') goto yy2;
		if(yych <= '=') goto yy98;
		if(yych <= '>') goto yy100;
		goto yy2;
yy32:
		yych = *++YYCURSOR;
		if(yych == '=') goto yy96;
		goto yy2;
yy33:
		yych = *++YYCURSOR;
		if(yych == 'O') goto yy93;
		if(yych == 'o') goto yy93;
		goto yy71;
yy34:
		++YYCURSOR;
#line 256 "pdo_user_sql_tokenizer.re"
		{ RET(PU_PLUS); }
#line 705 "pdo_user_sql_tokenizer.c"
yy36:
		yyaccept = 0;
		yych = *(YYMARKER = ++YYCURSOR);
		if(yych == '.') goto yy74;
		if(yych <= '/') goto yy37;
		if(yych <= '9') goto yy91;
yy37:
#line 257 "pdo_user_sql_tokenizer.re"
		{ RET(PU_MINUS); }
#line 715 "pdo_user_sql_tokenizer.c"
yy38:
		++YYCURSOR;
#line 258 "pdo_user_sql_tokenizer.re"
		{ RET(PU_MUL); }
#line 720 "pdo_user_sql_tokenizer.c"
yy40:
		++YYCURSOR;
#line 259 "pdo_user_sql_tokenizer.re"
		{ RET(PU_DIV); }
#line 725 "pdo_user_sql_tokenizer.c"
yy42:
		++YYCURSOR;
#line 260 "pdo_user_sql_tokenizer.re"
		{ RET(PU_MOD); }
#line 730 "pdo_user_sql_tokenizer.c"
yy44:
		++YYCURSOR;
#line 261 "pdo_user_sql_tokenizer.re"
		{ RET(PU_LPAREN); }
#line 735 "pdo_user_sql_tokenizer.c"
yy46:
		++YYCURSOR;
#line 262 "pdo_user_sql_tokenizer.re"
		{ RET(PU_RPAREN); }
#line 740 "pdo_user_sql_tokenizer.c"
yy48:
		++YYCURSOR;
#line 263 "pdo_user_sql_tokenizer.re"
		{ RET(PU_COMMA); }
#line 745 "pdo_user_sql_tokenizer.c"
yy50:
		++YYCURSOR;
#line 264 "pdo_user_sql_tokenizer.re"
		{ RET(PU_EQUALS); }
#line 750 "pdo_user_sql_tokenizer.c"
yy52:
		++YYCURSOR;
#line 265 "pdo_user_sql_tokenizer.re"
		{ RET(PU_SEMICOLON); }
#line 755 "pdo_user_sql_tokenizer.c"
yy54:
		++YYCURSOR;
		if((yych = *YYCURSOR) <= '/') goto yy55;
		if(yych <= '9') goto yy75;
yy55:
#line 266 "pdo_user_sql_tokenizer.re"
		{ RET(PU_DOT); }
#line 763 "pdo_user_sql_tokenizer.c"
yy56:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy70;
		}
#line 267 "pdo_user_sql_tokenizer.re"
		{ RET(PU_COLON); }
#line 771 "pdo_user_sql_tokenizer.c"
yy58:
		++YYCURSOR;
		if(YYLIMIT == YYCURSOR) YYFILL(1);
		yych = *YYCURSOR;
		if(yybm[0+yych] & 1) {
			goto yy58;
		}
		if(yych <= 0x00) goto yy2;
		if(yych <= '_') goto yy88;
		goto yy89;
yy60:
		++YYCURSOR;
		if(YYLIMIT == YYCURSOR) YYFILL(1);
		yych = *YYCURSOR;
		if(yybm[0+yych] & 2) {
			goto yy60;
		}
		if(yych <= 0x00) goto yy2;
		if(yych <= '[') goto yy86;
		goto yy85;
yy62:
		++YYCURSOR;
		if(YYLIMIT == YYCURSOR) YYFILL(1);
		yych = *YYCURSOR;
		if(yybm[0+yych] & 4) {
			goto yy62;
		}
		if(yych <= 0x00) goto yy2;
		if(yych <= '[') goto yy83;
		goto yy82;
yy64:
		++YYCURSOR;
		if(YYLIMIT == YYCURSOR) YYFILL(1);
		yych = *YYCURSOR;
yy65:
		if(yybm[0+yych] & 8) {
			goto yy64;
		}
		goto yy6;
yy66:
		yyaccept = 1;
		yych = *(YYMARKER = ++YYCURSOR);
		if(yych == 'X') goto yy78;
		if(yych == 'x') goto yy78;
		goto yy69;
yy67:
#line 275 "pdo_user_sql_tokenizer.re"
		{ RET(PU_LNUM); }
#line 820 "pdo_user_sql_tokenizer.c"
yy68:
		yyaccept = 1;
		YYMARKER = ++YYCURSOR;
		if((YYLIMIT - YYCURSOR) < 2) YYFILL(2);
		yych = *YYCURSOR;
yy69:
		if(yybm[0+yych] & 16) {
			goto yy68;
		}
		if(yych == '.') goto yy74;
		goto yy67;
yy70:
		++YYCURSOR;
		if(YYLIMIT == YYCURSOR) YYFILL(1);
		yych = *YYCURSOR;
yy71:
		if(yybm[0+yych] & 32) {
			goto yy70;
		}
		goto yy4;
yy72:
		++YYCURSOR;
#line 277 "pdo_user_sql_tokenizer.re"
		{ RET(PU_END); }
#line 845 "pdo_user_sql_tokenizer.c"
yy74:
		yych = *++YYCURSOR;
		if(yych <= '/') goto yy2;
		if(yych >= ':') goto yy2;
yy75:
		++YYCURSOR;
		if(YYLIMIT == YYCURSOR) YYFILL(1);
		yych = *YYCURSOR;
		if(yych <= '/') goto yy77;
		if(yych <= '9') goto yy75;
yy77:
#line 274 "pdo_user_sql_tokenizer.re"
		{ RET(PU_DNUM); }
#line 859 "pdo_user_sql_tokenizer.c"
yy78:
		yych = *++YYCURSOR;
		if(yybm[0+yych] & 64) {
			goto yy79;
		}
		goto yy2;
yy79:
		++YYCURSOR;
		if(YYLIMIT == YYCURSOR) YYFILL(1);
		yych = *YYCURSOR;
		if(yybm[0+yych] & 64) {
			goto yy79;
		}
#line 273 "pdo_user_sql_tokenizer.re"
		{ RET(PU_HNUM); }
#line 875 "pdo_user_sql_tokenizer.c"
yy82:
		++YYCURSOR;
		if(YYLIMIT == YYCURSOR) YYFILL(1);
		yych = *YYCURSOR;
		if(yych == 0x0A) goto yy2;
		goto yy62;
yy83:
		++YYCURSOR;
#line 271 "pdo_user_sql_tokenizer.re"
		{ RET_UNESC(PU_STRING); }
#line 886 "pdo_user_sql_tokenizer.c"
yy85:
		++YYCURSOR;
		if(YYLIMIT == YYCURSOR) YYFILL(1);
		yych = *YYCURSOR;
		if(yych == 0x0A) goto yy2;
		goto yy60;
yy86:
		++YYCURSOR;
#line 270 "pdo_user_sql_tokenizer.re"
		{ RET_UNESC(PU_STRING); }
#line 897 "pdo_user_sql_tokenizer.c"
yy88:
		++YYCURSOR;
		if(YYLIMIT == YYCURSOR) YYFILL(1);
		yych = *YYCURSOR;
		if(yych == 0x0A) goto yy2;
		goto yy58;
yy89:
		++YYCURSOR;
#line 269 "pdo_user_sql_tokenizer.re"
		{ RET_UNESC(PU_LABEL); }
#line 908 "pdo_user_sql_tokenizer.c"
yy91:
		++YYCURSOR;
		if((YYLIMIT - YYCURSOR) < 2) YYFILL(2);
		yych = *YYCURSOR;
		if(yych == '.') goto yy74;
		if(yych <= '/') goto yy2;
		if(yych <= '9') goto yy91;
		goto yy2;
yy93:
		yych = *++YYCURSOR;
		if(yych == 'R') goto yy94;
		if(yych != 'r') goto yy71;
yy94:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy70;
		}
#line 253 "pdo_user_sql_tokenizer.re"
		{ RET(PU_XOR); }
#line 928 "pdo_user_sql_tokenizer.c"
yy96:
		++YYCURSOR;
#line 247 "pdo_user_sql_tokenizer.re"
		{ RET(PU_GREATER_EQUAL); }
#line 933 "pdo_user_sql_tokenizer.c"
yy98:
		++YYCURSOR;
#line 246 "pdo_user_sql_tokenizer.re"
		{ RET(PU_LESSER_EQUAL); }
#line 938 "pdo_user_sql_tokenizer.c"
yy100:
		++YYCURSOR;
#line 245 "pdo_user_sql_tokenizer.re"
		{ RET(PU_UNEQUAL); }
#line 943 "pdo_user_sql_tokenizer.c"
yy102:
		++YYCURSOR;
#line 244 "pdo_user_sql_tokenizer.re"
		{ RET(PU_NOT_EQUAL); }
#line 948 "pdo_user_sql_tokenizer.c"
yy104:
		yych = *++YYCURSOR;
		if(yych == 'U') goto yy105;
		if(yych != 'u') goto yy71;
yy105:
		yych = *++YYCURSOR;
		if(yych == 'M') goto yy106;
		if(yych != 'm') goto yy71;
yy106:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy70;
		}
#line 241 "pdo_user_sql_tokenizer.re"
		{ RET(PU_ENUM); }
#line 964 "pdo_user_sql_tokenizer.c"
yy108:
		yych = *++YYCURSOR;
		if(yych == 'A') goto yy109;
		if(yych != 'a') goto yy71;
yy109:
		yych = *++YYCURSOR;
		if(yych == 'R') goto yy110;
		if(yych != 'r') goto yy71;
yy110:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy70;
		}
#line 227 "pdo_user_sql_tokenizer.re"
		{ RET(PU_YEAR); }
#line 980 "pdo_user_sql_tokenizer.c"
yy112:
		yych = *++YYCURSOR;
		if(yych == 'D') goto yy113;
		if(yych != 'd') goto yy71;
yy113:
		yych = *++YYCURSOR;
		if(yych == 'I') goto yy114;
		if(yych != 'i') goto yy71;
yy114:
		yych = *++YYCURSOR;
		if(yych == 'U') goto yy115;
		if(yych != 'u') goto yy71;
yy115:
		yych = *++YYCURSOR;
		if(yych == 'M') goto yy116;
		if(yych != 'm') goto yy71;
yy116:
		yych = *++YYCURSOR;
		if(yych <= 'T') {
			if(yych <= 'H') {
				if(yych == 'B') goto yy119;
				goto yy71;
			} else {
				if(yych <= 'I') goto yy117;
				if(yych <= 'S') goto yy71;
				goto yy118;
			}
		} else {
			if(yych <= 'h') {
				if(yych == 'b') goto yy119;
				goto yy71;
			} else {
				if(yych <= 'i') goto yy117;
				if(yych == 't') goto yy118;
				goto yy71;
			}
		}
yy117:
		yych = *++YYCURSOR;
		if(yych == 'N') goto yy128;
		if(yych == 'n') goto yy128;
		goto yy71;
yy118:
		yych = *++YYCURSOR;
		if(yych == 'E') goto yy124;
		if(yych == 'e') goto yy124;
		goto yy71;
yy119:
		yych = *++YYCURSOR;
		if(yych == 'L') goto yy120;
		if(yych != 'l') goto yy71;
yy120:
		yych = *++YYCURSOR;
		if(yych == 'O') goto yy121;
		if(yych != 'o') goto yy71;
yy121:
		yych = *++YYCURSOR;
		if(yych == 'B') goto yy122;
		if(yych != 'b') goto yy71;
yy122:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy70;
		}
#line 238 "pdo_user_sql_tokenizer.re"
		{ RET(PU_MEDIUMBLOB); }
#line 1047 "pdo_user_sql_tokenizer.c"
yy124:
		yych = *++YYCURSOR;
		if(yych == 'X') goto yy125;
		if(yych != 'x') goto yy71;
yy125:
		yych = *++YYCURSOR;
		if(yych == 'T') goto yy126;
		if(yych != 't') goto yy71;
yy126:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy70;
		}
#line 234 "pdo_user_sql_tokenizer.re"
		{ RET(PU_MEDIUMTEXT); }
#line 1063 "pdo_user_sql_tokenizer.c"
yy128:
		yych = *++YYCURSOR;
		if(yych == 'T') goto yy129;
		if(yych != 't') goto yy71;
yy129:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy70;
		}
#line 217 "pdo_user_sql_tokenizer.re"
		{ RET(PU_MEDIUMINT); }
#line 1075 "pdo_user_sql_tokenizer.c"
yy131:
		yych = *++YYCURSOR;
		if(yych == 'R') goto yy132;
		if(yych != 'r') goto yy71;
yy132:
		yych = *++YYCURSOR;
		if(yych == 'O') goto yy133;
		if(yych != 'o') goto yy71;
yy133:
		yych = *++YYCURSOR;
		if(yych == 'F') goto yy134;
		if(yych != 'f') goto yy71;
yy134:
		yych = *++YYCURSOR;
		if(yych == 'I') goto yy135;
		if(yych != 'i') goto yy71;
yy135:
		yych = *++YYCURSOR;
		if(yych == 'L') goto yy136;
		if(yych != 'l') goto yy71;
yy136:
		yych = *++YYCURSOR;
		if(yych == 'L') goto yy137;
		if(yych != 'l') goto yy71;
yy137:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy70;
		}
#line 209 "pdo_user_sql_tokenizer.re"
		{ RET(PU_ZEROFILL); }
#line 1107 "pdo_user_sql_tokenizer.c"
yy139:
		yych = *++YYCURSOR;
		if(yych == 'I') goto yy140;
		if(yych != 'i') goto yy71;
yy140:
		yych = *++YYCURSOR;
		if(yych == 'N') goto yy141;
		if(yych != 'n') goto yy71;
yy141:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy70;
		}
#line 204 "pdo_user_sql_tokenizer.re"
		{ RET(PU_JOIN); }
#line 1123 "pdo_user_sql_tokenizer.c"
yy143:
		yych = *++YYCURSOR;
		if(yych == 'I') goto yy144;
		if(yych != 'i') goto yy71;
yy144:
		yych = *++YYCURSOR;
		if(yych == 'M') goto yy145;
		if(yych != 'm') goto yy71;
yy145:
		yych = *++YYCURSOR;
		if(yych == 'A') goto yy146;
		if(yych != 'a') goto yy71;
yy146:
		yych = *++YYCURSOR;
		if(yych == 'R') goto yy147;
		if(yych != 'r') goto yy71;
yy147:
		yych = *++YYCURSOR;
		if(yych == 'Y') goto yy148;
		if(yych != 'y') goto yy71;
yy148:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy70;
		}
#line 195 "pdo_user_sql_tokenizer.re"
		{ RET(PU_PRIMARY); }
#line 1151 "pdo_user_sql_tokenizer.c"
yy150:
		yych = *++YYCURSOR;
		if(yych == 'F') goto yy170;
		if(yych == 'f') goto yy170;
		goto yy71;
yy151:
		yych = *++YYCURSOR;
		if(yych <= 'T') {
			if(yych <= 'M') {
				if(yych == 'G') goto yy160;
				goto yy71;
			} else {
				if(yych <= 'N') goto yy161;
				if(yych <= 'S') goto yy71;
				goto yy158;
			}
		} else {
			if(yych <= 'm') {
				if(yych == 'g') goto yy160;
				goto yy71;
			} else {
				if(yych <= 'n') goto yy161;
				if(yych == 't') goto yy158;
				goto yy71;
			}
		}
yy152:
		yych = *++YYCURSOR;
		if(yych == 'O') goto yy155;
		if(yych == 'o') goto yy155;
		goto yy71;
yy153:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy70;
		}
#line 190 "pdo_user_sql_tokenizer.re"
		{ RET(PU_BY); }
#line 1190 "pdo_user_sql_tokenizer.c"
yy155:
		yych = *++YYCURSOR;
		if(yych == 'B') goto yy156;
		if(yych != 'b') goto yy71;
yy156:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy70;
		}
#line 236 "pdo_user_sql_tokenizer.re"
		{ RET(PU_BLOB); }
#line 1202 "pdo_user_sql_tokenizer.c"
yy158:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy70;
		}
#line 212 "pdo_user_sql_tokenizer.re"
		{ RET(PU_BIT); }
#line 1210 "pdo_user_sql_tokenizer.c"
yy160:
		yych = *++YYCURSOR;
		if(yych == 'I') goto yy166;
		if(yych == 'i') goto yy166;
		goto yy71;
yy161:
		yych = *++YYCURSOR;
		if(yych == 'A') goto yy162;
		if(yych != 'a') goto yy71;
yy162:
		yych = *++YYCURSOR;
		if(yych == 'R') goto yy163;
		if(yych != 'r') goto yy71;
yy163:
		yych = *++YYCURSOR;
		if(yych == 'Y') goto yy164;
		if(yych != 'y') goto yy71;
yy164:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy70;
		}
#line 221 "pdo_user_sql_tokenizer.re"
		{ RET(PU_BINARY); }
#line 1235 "pdo_user_sql_tokenizer.c"
yy166:
		yych = *++YYCURSOR;
		if(yych == 'N') goto yy167;
		if(yych != 'n') goto yy71;
yy167:
		yych = *++YYCURSOR;
		if(yych == 'T') goto yy168;
		if(yych != 't') goto yy71;
yy168:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy70;
		}
#line 218 "pdo_user_sql_tokenizer.re"
		{ RET(PU_BIGINT); }
#line 1251 "pdo_user_sql_tokenizer.c"
yy170:
		yych = *++YYCURSOR;
		if(yych == 'O') goto yy171;
		if(yych != 'o') goto yy71;
yy171:
		yych = *++YYCURSOR;
		if(yych == 'R') goto yy172;
		if(yych != 'r') goto yy71;
yy172:
		yych = *++YYCURSOR;
		if(yych == 'E') goto yy173;
		if(yych != 'e') goto yy71;
yy173:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy70;
		}
#line 196 "pdo_user_sql_tokenizer.re"
		{ RET(PU_BEFORE); }
#line 1271 "pdo_user_sql_tokenizer.c"
yy175:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy70;
		}
#line 205 "pdo_user_sql_tokenizer.re"
		{ RET(PU_ON); }
#line 1279 "pdo_user_sql_tokenizer.c"
yy177:
		++YYCURSOR;
		if((yych = *YYCURSOR) <= '^') {
			if(yych <= '@') {
				if(yych <= '/') goto yy178;
				if(yych <= '9') goto yy70;
			} else {
				if(yych == 'D') goto yy184;
				if(yych <= 'Z') goto yy70;
			}
		} else {
			if(yych <= 'c') {
				if(yych != '`') goto yy70;
			} else {
				if(yych <= 'd') goto yy184;
				if(yych <= 'z') goto yy70;
				if(yych >= 0x80) goto yy70;
			}
		}
yy178:
#line 252 "pdo_user_sql_tokenizer.re"
		{ RET(PU_OR); }
#line 1302 "pdo_user_sql_tokenizer.c"
yy179:
		yych = *++YYCURSOR;
		if(yych == 'T') goto yy180;
		if(yych != 't') goto yy71;
yy180:
		yych = *++YYCURSOR;
		if(yych == 'E') goto yy181;
		if(yych != 'e') goto yy71;
yy181:
		yych = *++YYCURSOR;
		if(yych == 'R') goto yy182;
		if(yych != 'r') goto yy71;
yy182:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy70;
		}
#line 201 "pdo_user_sql_tokenizer.re"
		{ RET(PU_OUTER); }
#line 1322 "pdo_user_sql_tokenizer.c"
yy184:
		yych = *++YYCURSOR;
		if(yych == 'E') goto yy185;
		if(yych != 'e') goto yy71;
yy185:
		yych = *++YYCURSOR;
		if(yych == 'R') goto yy186;
		if(yych != 'r') goto yy71;
yy186:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy70;
		}
#line 189 "pdo_user_sql_tokenizer.re"
		{ RET(PU_ORDER); }
#line 1338 "pdo_user_sql_tokenizer.c"
yy188:
		yych = *++YYCURSOR;
		if(yych == 'V') goto yy189;
		if(yych != 'v') goto yy71;
yy189:
		yych = *++YYCURSOR;
		if(yych == 'I') goto yy190;
		if(yych != 'i') goto yy71;
yy190:
		yych = *++YYCURSOR;
		if(yych == 'N') goto yy191;
		if(yych != 'n') goto yy71;
yy191:
		yych = *++YYCURSOR;
		if(yych == 'G') goto yy192;
		if(yych != 'g') goto yy71;
yy192:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy70;
		}
#line 188 "pdo_user_sql_tokenizer.re"
		{ RET(PU_HAVING); }
#line 1362 "pdo_user_sql_tokenizer.c"
yy194:
		yych = *++YYCURSOR;
		if(yych == 'F') goto yy216;
		if(yych == 'f') goto yy216;
		goto yy71;
yy195:
		yych = *++YYCURSOR;
		if(yych <= 'M') {
			if(yych == 'K') goto yy210;
			if(yych <= 'L') goto yy71;
			goto yy209;
		} else {
			if(yych <= 'k') {
				if(yych <= 'j') goto yy71;
				goto yy210;
			} else {
				if(yych == 'm') goto yy209;
				goto yy71;
			}
		}
yy196:
		yych = *++YYCURSOR;
		if(yych == 'N') goto yy197;
		if(yych != 'n') goto yy71;
yy197:
		yych = *++YYCURSOR;
		if(yych == 'G') goto yy198;
		if(yych != 'g') goto yy71;
yy198:
		yych = *++YYCURSOR;
		if(yych <= 'T') {
			if(yych == 'B') goto yy200;
			if(yych <= 'S') goto yy71;
		} else {
			if(yych <= 'b') {
				if(yych <= 'a') goto yy71;
				goto yy200;
			} else {
				if(yych != 't') goto yy71;
			}
		}
		yych = *++YYCURSOR;
		if(yych == 'E') goto yy205;
		if(yych == 'e') goto yy205;
		goto yy71;
yy200:
		yych = *++YYCURSOR;
		if(yych == 'L') goto yy201;
		if(yych != 'l') goto yy71;
yy201:
		yych = *++YYCURSOR;
		if(yych == 'O') goto yy202;
		if(yych != 'o') goto yy71;
yy202:
		yych = *++YYCURSOR;
		if(yych == 'B') goto yy203;
		if(yych != 'b') goto yy71;
yy203:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy70;
		}
#line 239 "pdo_user_sql_tokenizer.re"
		{ RET(PU_LONGBLOB); }
#line 1427 "pdo_user_sql_tokenizer.c"
yy205:
		yych = *++YYCURSOR;
		if(yych == 'X') goto yy206;
		if(yych != 'x') goto yy71;
yy206:
		yych = *++YYCURSOR;
		if(yych == 'T') goto yy207;
		if(yych != 't') goto yy71;
yy207:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy70;
		}
#line 235 "pdo_user_sql_tokenizer.re"
		{ RET(PU_LONGTEXT); }
#line 1443 "pdo_user_sql_tokenizer.c"
yy209:
		yych = *++YYCURSOR;
		if(yych == 'I') goto yy213;
		if(yych == 'i') goto yy213;
		goto yy71;
yy210:
		yych = *++YYCURSOR;
		if(yych == 'E') goto yy211;
		if(yych != 'e') goto yy71;
yy211:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy70;
		}
#line 248 "pdo_user_sql_tokenizer.re"
		{ RET(PU_LIKE); }
#line 1460 "pdo_user_sql_tokenizer.c"
yy213:
		yych = *++YYCURSOR;
		if(yych == 'T') goto yy214;
		if(yych != 't') goto yy71;
yy214:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy70;
		}
#line 187 "pdo_user_sql_tokenizer.re"
		{ RET(PU_LIMIT); }
#line 1472 "pdo_user_sql_tokenizer.c"
yy216:
		yych = *++YYCURSOR;
		if(yych == 'T') goto yy217;
		if(yych != 't') goto yy71;
yy217:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy70;
		}
#line 202 "pdo_user_sql_tokenizer.re"
		{ RET(PU_LEFT); }
#line 1484 "pdo_user_sql_tokenizer.c"
yy219:
		yych = *++YYCURSOR;
		if(yych == 'E') goto yy220;
		if(yych != 'e') goto yy71;
yy220:
		yych = *++YYCURSOR;
		if(yych == 'R') goto yy221;
		if(yych != 'r') goto yy71;
yy221:
		yych = *++YYCURSOR;
		if(yych == 'E') goto yy222;
		if(yych != 'e') goto yy71;
yy222:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy70;
		}
#line 185 "pdo_user_sql_tokenizer.re"
		{ RET(PU_WHERE); }
#line 1504 "pdo_user_sql_tokenizer.c"
yy224:
		yych = *++YYCURSOR;
		if(yych == 'O') goto yy229;
		if(yych == 'o') goto yy229;
		goto yy71;
yy225:
		yych = *++YYCURSOR;
		if(yych == 'O') goto yy226;
		if(yych != 'o') goto yy71;
yy226:
		yych = *++YYCURSOR;
		if(yych == 'M') goto yy227;
		if(yych != 'm') goto yy71;
yy227:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy70;
		}
#line 183 "pdo_user_sql_tokenizer.re"
		{ RET(PU_FROM); }
#line 1525 "pdo_user_sql_tokenizer.c"
yy229:
		yych = *++YYCURSOR;
		if(yych == 'A') goto yy230;
		if(yych != 'a') goto yy71;
yy230:
		yych = *++YYCURSOR;
		if(yych == 'T') goto yy231;
		if(yych != 't') goto yy71;
yy231:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy70;
		}
#line 230 "pdo_user_sql_tokenizer.re"
		{ RET(PU_FLOAT); }
#line 1541 "pdo_user_sql_tokenizer.c"
yy233:
		yych = *++YYCURSOR;
		if(yych == 'T') goto yy238;
		if(yych == 't') goto yy238;
		goto yy71;
yy234:
		yych = *++YYCURSOR;
		if(yych == 'L') goto yy235;
		if(yych != 'l') goto yy71;
yy235:
		yych = *++YYCURSOR;
		if(yych == 'L') goto yy236;
		if(yych != 'l') goto yy71;
yy236:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy70;
		}
#line 177 "pdo_user_sql_tokenizer.re"
		{ RET(PU_NULL); }
#line 1562 "pdo_user_sql_tokenizer.c"
yy238:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy70;
		}
#line 250 "pdo_user_sql_tokenizer.re"
		{ RET(PU_NOT); }
#line 1570 "pdo_user_sql_tokenizer.c"
yy240:
		yych = *++YYCURSOR;
		if(yych == 'Y') goto yy241;
		if(yych != 'y') goto yy71;
yy241:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy70;
		}
#line 176 "pdo_user_sql_tokenizer.re"
		{ RET(PU_KEY); }
#line 1582 "pdo_user_sql_tokenizer.c"
yy243:
		yych = *++YYCURSOR;
		if(yych <= 'R') {
			if(yych == 'L') goto yy248;
			if(yych <= 'Q') goto yy71;
			goto yy249;
		} else {
			if(yych <= 'l') {
				if(yych <= 'k') goto yy71;
				goto yy248;
			} else {
				if(yych == 'r') goto yy249;
				goto yy71;
			}
		}
yy244:
		yych = *++YYCURSOR;
		if(yych == 'E') goto yy245;
		if(yych != 'e') goto yy71;
yy245:
		yych = *++YYCURSOR;
		if(yych == 'W') goto yy246;
		if(yych != 'w') goto yy71;
yy246:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy70;
		}
#line 174 "pdo_user_sql_tokenizer.re"
		{ RET(PU_VIEW); }
#line 1613 "pdo_user_sql_tokenizer.c"
yy248:
		yych = *++YYCURSOR;
		if(yych == 'U') goto yy262;
		if(yych == 'u') goto yy262;
		goto yy71;
yy249:
		yych = *++YYCURSOR;
		if(yych <= 'C') {
			if(yych <= 'A') goto yy71;
			if(yych >= 'C') goto yy251;
		} else {
			if(yych <= 'a') goto yy71;
			if(yych <= 'b') goto yy250;
			if(yych <= 'c') goto yy251;
			goto yy71;
		}
yy250:
		yych = *++YYCURSOR;
		if(yych == 'I') goto yy256;
		if(yych == 'i') goto yy256;
		goto yy71;
yy251:
		yych = *++YYCURSOR;
		if(yych == 'H') goto yy252;
		if(yych != 'h') goto yy71;
yy252:
		yych = *++YYCURSOR;
		if(yych == 'A') goto yy253;
		if(yych != 'a') goto yy71;
yy253:
		yych = *++YYCURSOR;
		if(yych == 'R') goto yy254;
		if(yych != 'r') goto yy71;
yy254:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy70;
		}
#line 220 "pdo_user_sql_tokenizer.re"
		{ RET(PU_VARCHAR); }
#line 1654 "pdo_user_sql_tokenizer.c"
yy256:
		yych = *++YYCURSOR;
		if(yych == 'N') goto yy257;
		if(yych != 'n') goto yy71;
yy257:
		yych = *++YYCURSOR;
		if(yych == 'A') goto yy258;
		if(yych != 'a') goto yy71;
yy258:
		yych = *++YYCURSOR;
		if(yych == 'R') goto yy259;
		if(yych != 'r') goto yy71;
yy259:
		yych = *++YYCURSOR;
		if(yych == 'Y') goto yy260;
		if(yych != 'y') goto yy71;
yy260:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy70;
		}
#line 222 "pdo_user_sql_tokenizer.re"
		{ RET(PU_VARBINARY); }
#line 1678 "pdo_user_sql_tokenizer.c"
yy262:
		yych = *++YYCURSOR;
		if(yych == 'E') goto yy263;
		if(yych != 'e') goto yy71;
yy263:
		yych = *++YYCURSOR;
		if(yych == 'S') goto yy264;
		if(yych != 's') goto yy71;
yy264:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy70;
		}
#line 193 "pdo_user_sql_tokenizer.re"
		{ RET(PU_VALUES); }
#line 1694 "pdo_user_sql_tokenizer.c"
yy266:
		yych = *++YYCURSOR;
		if(yych == 'B') goto yy299;
		if(yych == 'b') goto yy299;
		goto yy71;
yy267:
		yych = *++YYCURSOR;
		if(yych == 'X') goto yy296;
		if(yych == 'x') goto yy296;
		goto yy71;
yy268:
		yych = *++YYCURSOR;
		if(yych <= 'N') {
			if(yych <= 'L') goto yy71;
			if(yych <= 'M') goto yy272;
			goto yy271;
		} else {
			if(yych <= 'l') goto yy71;
			if(yych <= 'm') goto yy272;
			if(yych <= 'n') goto yy271;
			goto yy71;
		}
yy269:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy70;
		}
#line 192 "pdo_user_sql_tokenizer.re"
		{ RET(PU_TO); }
#line 1724 "pdo_user_sql_tokenizer.c"
yy271:
		yych = *++YYCURSOR;
		if(yych == 'Y') goto yy281;
		if(yych == 'y') goto yy281;
		goto yy71;
yy272:
		yych = *++YYCURSOR;
		if(yych == 'E') goto yy273;
		if(yych != 'e') goto yy71;
yy273:
		++YYCURSOR;
		if((yych = *YYCURSOR) <= '^') {
			if(yych <= '@') {
				if(yych <= '/') goto yy274;
				if(yych <= '9') goto yy70;
			} else {
				if(yych == 'S') goto yy275;
				if(yych <= 'Z') goto yy70;
			}
		} else {
			if(yych <= 'r') {
				if(yych != '`') goto yy70;
			} else {
				if(yych <= 's') goto yy275;
				if(yych <= 'z') goto yy70;
				if(yych >= 0x80) goto yy70;
			}
		}
yy274:
#line 225 "pdo_user_sql_tokenizer.re"
		{ RET(PU_TIME); }
#line 1756 "pdo_user_sql_tokenizer.c"
yy275:
		yych = *++YYCURSOR;
		if(yych == 'T') goto yy276;
		if(yych != 't') goto yy71;
yy276:
		yych = *++YYCURSOR;
		if(yych == 'A') goto yy277;
		if(yych != 'a') goto yy71;
yy277:
		yych = *++YYCURSOR;
		if(yych == 'M') goto yy278;
		if(yych != 'm') goto yy71;
yy278:
		yych = *++YYCURSOR;
		if(yych == 'P') goto yy279;
		if(yych != 'p') goto yy71;
yy279:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy70;
		}
#line 226 "pdo_user_sql_tokenizer.re"
		{ RET(PU_TIMESTAMP); }
#line 1780 "pdo_user_sql_tokenizer.c"
yy281:
		yych = *++YYCURSOR;
		if(yych <= 'T') {
			if(yych <= 'H') {
				if(yych == 'B') goto yy284;
				goto yy71;
			} else {
				if(yych <= 'I') goto yy282;
				if(yych <= 'S') goto yy71;
				goto yy283;
			}
		} else {
			if(yych <= 'h') {
				if(yych == 'b') goto yy284;
				goto yy71;
			} else {
				if(yych <= 'i') goto yy282;
				if(yych == 't') goto yy283;
				goto yy71;
			}
		}
yy282:
		yych = *++YYCURSOR;
		if(yych == 'N') goto yy293;
		if(yych == 'n') goto yy293;
		goto yy71;
yy283:
		yych = *++YYCURSOR;
		if(yych == 'E') goto yy289;
		if(yych == 'e') goto yy289;
		goto yy71;
yy284:
		yych = *++YYCURSOR;
		if(yych == 'L') goto yy285;
		if(yych != 'l') goto yy71;
yy285:
		yych = *++YYCURSOR;
		if(yych == 'O') goto yy286;
		if(yych != 'o') goto yy71;
yy286:
		yych = *++YYCURSOR;
		if(yych == 'B') goto yy287;
		if(yych != 'b') goto yy71;
yy287:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy70;
		}
#line 237 "pdo_user_sql_tokenizer.re"
		{ RET(PU_TINYBLOB); }
#line 1831 "pdo_user_sql_tokenizer.c"
yy289:
		yych = *++YYCURSOR;
		if(yych == 'X') goto yy290;
		if(yych != 'x') goto yy71;
yy290:
		yych = *++YYCURSOR;
		if(yych == 'T') goto yy291;
		if(yych != 't') goto yy71;
yy291:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy70;
		}
#line 233 "pdo_user_sql_tokenizer.re"
		{ RET(PU_TINYTEXT); }
#line 1847 "pdo_user_sql_tokenizer.c"
yy293:
		yych = *++YYCURSOR;
		if(yych == 'T') goto yy294;
		if(yych != 't') goto yy71;
yy294:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy70;
		}
#line 215 "pdo_user_sql_tokenizer.re"
		{ RET(PU_TINYINT); }
#line 1859 "pdo_user_sql_tokenizer.c"
yy296:
		yych = *++YYCURSOR;
		if(yych == 'T') goto yy297;
		if(yych != 't') goto yy71;
yy297:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy70;
		}
#line 232 "pdo_user_sql_tokenizer.re"
		{ RET(PU_TEXT); }
#line 1871 "pdo_user_sql_tokenizer.c"
yy299:
		yych = *++YYCURSOR;
		if(yych == 'L') goto yy300;
		if(yych != 'l') goto yy71;
yy300:
		yych = *++YYCURSOR;
		if(yych == 'E') goto yy301;
		if(yych != 'e') goto yy71;
yy301:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy70;
		}
#line 173 "pdo_user_sql_tokenizer.re"
		{ RET(PU_TABLE); }
#line 1887 "pdo_user_sql_tokenizer.c"
yy303:
		yych = *++YYCURSOR;
		if(yych <= 'O') {
			if(yych == 'A') goto yy304;
			if(yych <= 'N') goto yy71;
			goto yy305;
		} else {
			if(yych <= 'a') {
				if(yych <= '`') goto yy71;
			} else {
				if(yych == 'o') goto yy305;
				goto yy71;
			}
		}
yy304:
		yych = *++YYCURSOR;
		if(yych == 'N') goto yy309;
		if(yych == 'n') goto yy309;
		goto yy71;
yy305:
		yych = *++YYCURSOR;
		if(yych == 'U') goto yy306;
		if(yych != 'u') goto yy71;
yy306:
		yych = *++YYCURSOR;
		if(yych == 'P') goto yy307;
		if(yych != 'p') goto yy71;
yy307:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy70;
		}
#line 186 "pdo_user_sql_tokenizer.re"
		{ RET(PU_GROUP); }
#line 1922 "pdo_user_sql_tokenizer.c"
yy309:
		yych = *++YYCURSOR;
		if(yych == 'T') goto yy310;
		if(yych != 't') goto yy71;
yy310:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy70;
		}
#line 167 "pdo_user_sql_tokenizer.re"
		{ RET(PU_GRANT); }
#line 1934 "pdo_user_sql_tokenizer.c"
yy312:
		yych = *++YYCURSOR;
		if(yych == 'D') goto yy346;
		if(yych == 'd') goto yy346;
		goto yy71;
yy313:
		yych = *++YYCURSOR;
		if(yych == 'T') goto yy342;
		if(yych == 't') goto yy342;
		goto yy71;
yy314:
		yych = *++YYCURSOR;
		if(yych <= 'T') {
			if(yych == 'L') goto yy337;
			if(yych <= 'S') goto yy71;
			goto yy336;
		} else {
			if(yych <= 'l') {
				if(yych <= 'k') goto yy71;
				goto yy337;
			} else {
				if(yych == 't') goto yy336;
				goto yy71;
			}
		}
yy315:
		yych = *++YYCURSOR;
		if(yych == 'D') goto yy334;
		if(yych == 'd') goto yy334;
		goto yy71;
yy316:
		++YYCURSOR;
		if((yych = *YYCURSOR) <= '^') {
			if(yych <= '@') {
				if(yych <= '/') goto yy317;
				if(yych <= '9') goto yy70;
			} else {
				if(yych == 'C') goto yy332;
				if(yych <= 'Z') goto yy70;
			}
		} else {
			if(yych <= 'b') {
				if(yych != '`') goto yy70;
			} else {
				if(yych <= 'c') goto yy332;
				if(yych <= 'z') goto yy70;
				if(yych >= 0x80) goto yy70;
			}
		}
yy317:
#line 191 "pdo_user_sql_tokenizer.re"
		{ RET(PU_AS); }
#line 1987 "pdo_user_sql_tokenizer.c"
yy318:
		yych = *++YYCURSOR;
		if(yych == 'T') goto yy319;
		if(yych != 't') goto yy71;
yy319:
		yych = *++YYCURSOR;
		if(yych == 'O') goto yy320;
		if(yych != 'o') goto yy71;
yy320:
		yych = *++YYCURSOR;
		if(yych != '_') goto yy71;
		yych = *++YYCURSOR;
		if(yych == 'I') goto yy322;
		if(yych != 'i') goto yy71;
yy322:
		yych = *++YYCURSOR;
		if(yych == 'N') goto yy323;
		if(yych != 'n') goto yy71;
yy323:
		yych = *++YYCURSOR;
		if(yych == 'C') goto yy324;
		if(yych != 'c') goto yy71;
yy324:
		yych = *++YYCURSOR;
		if(yych == 'R') goto yy325;
		if(yych != 'r') goto yy71;
yy325:
		yych = *++YYCURSOR;
		if(yych == 'E') goto yy326;
		if(yych != 'e') goto yy71;
yy326:
		yych = *++YYCURSOR;
		if(yych == 'M') goto yy327;
		if(yych != 'm') goto yy71;
yy327:
		yych = *++YYCURSOR;
		if(yych == 'E') goto yy328;
		if(yych != 'e') goto yy71;
yy328:
		yych = *++YYCURSOR;
		if(yych == 'N') goto yy329;
		if(yych != 'n') goto yy71;
yy329:
		yych = *++YYCURSOR;
		if(yych == 'T') goto yy330;
		if(yych != 't') goto yy71;
yy330:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy70;
		}
#line 178 "pdo_user_sql_tokenizer.re"
		{ RET(PU_AUTO_INCREMENT); }
#line 2041 "pdo_user_sql_tokenizer.c"
yy332:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy70;
		}
#line 206 "pdo_user_sql_tokenizer.re"
		{ RET(PU_ASC); }
#line 2049 "pdo_user_sql_tokenizer.c"
yy334:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy70;
		}
#line 251 "pdo_user_sql_tokenizer.re"
		{ RET(PU_AND); }
#line 2057 "pdo_user_sql_tokenizer.c"
yy336:
		yych = *++YYCURSOR;
		if(yych == 'E') goto yy339;
		if(yych == 'e') goto yy339;
		goto yy71;
yy337:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy70;
		}
#line 179 "pdo_user_sql_tokenizer.re"
		{ RET(PU_ALL); }
#line 2070 "pdo_user_sql_tokenizer.c"
yy339:
		yych = *++YYCURSOR;
		if(yych == 'R') goto yy340;
		if(yych != 'r') goto yy71;
yy340:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy70;
		}
#line 166 "pdo_user_sql_tokenizer.re"
		{ RET(PU_ALTER); }
#line 2082 "pdo_user_sql_tokenizer.c"
yy342:
		yych = *++YYCURSOR;
		if(yych == 'E') goto yy343;
		if(yych != 'e') goto yy71;
yy343:
		yych = *++YYCURSOR;
		if(yych == 'R') goto yy344;
		if(yych != 'r') goto yy71;
yy344:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy70;
		}
#line 197 "pdo_user_sql_tokenizer.re"
		{ RET(PU_AFTER); }
#line 2098 "pdo_user_sql_tokenizer.c"
yy346:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy70;
		}
#line 169 "pdo_user_sql_tokenizer.re"
		{ RET(PU_ADD); }
#line 2106 "pdo_user_sql_tokenizer.c"
yy348:
		yych = *++YYCURSOR;
		if(yych <= 'V') {
			if(yych <= 'M') {
				if(yych == 'A') goto yy361;
				goto yy71;
			} else {
				if(yych <= 'N') goto yy359;
				if(yych <= 'U') goto yy71;
				goto yy360;
			}
		} else {
			if(yych <= 'm') {
				if(yych == 'a') goto yy361;
				goto yy71;
			} else {
				if(yych <= 'n') goto yy359;
				if(yych == 'v') goto yy360;
				goto yy71;
			}
		}
yy349:
		yych = *++YYCURSOR;
		if(yych == 'G') goto yy355;
		if(yych == 'g') goto yy355;
		goto yy71;
yy350:
		yych = *++YYCURSOR;
		if(yych == 'I') goto yy351;
		if(yych != 'i') goto yy71;
yy351:
		yych = *++YYCURSOR;
		if(yych == 'K') goto yy352;
		if(yych != 'k') goto yy71;
yy352:
		yych = *++YYCURSOR;
		if(yych == 'E') goto yy353;
		if(yych != 'e') goto yy71;
yy353:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy70;
		}
#line 249 "pdo_user_sql_tokenizer.re"
		{ RET(PU_RLIKE); }
#line 2152 "pdo_user_sql_tokenizer.c"
yy355:
		yych = *++YYCURSOR;
		if(yych == 'H') goto yy356;
		if(yych != 'h') goto yy71;
yy356:
		yych = *++YYCURSOR;
		if(yych == 'T') goto yy357;
		if(yych != 't') goto yy71;
yy357:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy70;
		}
#line 203 "pdo_user_sql_tokenizer.re"
		{ RET(PU_RIGHT); }
#line 2168 "pdo_user_sql_tokenizer.c"
yy359:
		yych = *++YYCURSOR;
		if(yych == 'A') goto yy368;
		if(yych == 'a') goto yy368;
		goto yy71;
yy360:
		yych = *++YYCURSOR;
		if(yych == 'O') goto yy364;
		if(yych == 'o') goto yy364;
		goto yy71;
yy361:
		yych = *++YYCURSOR;
		if(yych == 'L') goto yy362;
		if(yych != 'l') goto yy71;
yy362:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy70;
		}
#line 228 "pdo_user_sql_tokenizer.re"
		{ RET(PU_REAL); }
#line 2190 "pdo_user_sql_tokenizer.c"
yy364:
		yych = *++YYCURSOR;
		if(yych == 'K') goto yy365;
		if(yych != 'k') goto yy71;
yy365:
		yych = *++YYCURSOR;
		if(yych == 'E') goto yy366;
		if(yych != 'e') goto yy71;
yy366:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy70;
		}
#line 168 "pdo_user_sql_tokenizer.re"
		{ RET(PU_REVOKE); }
#line 2206 "pdo_user_sql_tokenizer.c"
yy368:
		yych = *++YYCURSOR;
		if(yych == 'M') goto yy369;
		if(yych != 'm') goto yy71;
yy369:
		yych = *++YYCURSOR;
		if(yych == 'E') goto yy370;
		if(yych != 'e') goto yy71;
yy370:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy70;
		}
#line 165 "pdo_user_sql_tokenizer.re"
		{ RET(PU_RENAME); }
#line 2222 "pdo_user_sql_tokenizer.c"
yy372:
		yych = *++YYCURSOR;
		if(yych == 'A') goto yy385;
		if(yych == 'a') goto yy385;
		goto yy71;
yy373:
		yych = *++YYCURSOR;
		if(yych == 'L') goto yy380;
		if(yych == 'l') goto yy380;
		goto yy71;
yy374:
		yych = *++YYCURSOR;
		if(yych == 'E') goto yy375;
		if(yych != 'e') goto yy71;
yy375:
		yych = *++YYCURSOR;
		if(yych == 'A') goto yy376;
		if(yych != 'a') goto yy71;
yy376:
		yych = *++YYCURSOR;
		if(yych == 'T') goto yy377;
		if(yych != 't') goto yy71;
yy377:
		yych = *++YYCURSOR;
		if(yych == 'E') goto yy378;
		if(yych != 'e') goto yy71;
yy378:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy70;
		}
#line 164 "pdo_user_sql_tokenizer.re"
		{ RET(PU_CREATE); }
#line 2256 "pdo_user_sql_tokenizer.c"
yy380:
		yych = *++YYCURSOR;
		if(yych == 'U') goto yy381;
		if(yych != 'u') goto yy71;
yy381:
		yych = *++YYCURSOR;
		if(yych == 'M') goto yy382;
		if(yych != 'm') goto yy71;
yy382:
		yych = *++YYCURSOR;
		if(yych == 'N') goto yy383;
		if(yych != 'n') goto yy71;
yy383:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy70;
		}
#line 175 "pdo_user_sql_tokenizer.re"
		{ RET(PU_COLUMN); }
#line 2276 "pdo_user_sql_tokenizer.c"
yy385:
		yych = *++YYCURSOR;
		if(yych == 'R') goto yy386;
		if(yych != 'r') goto yy71;
yy386:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy70;
		}
#line 219 "pdo_user_sql_tokenizer.re"
		{ RET(PU_CHAR); }
#line 2288 "pdo_user_sql_tokenizer.c"
yy388:
		yych = *++YYCURSOR;
		if(yych == 'T') goto yy428;
		if(yych == 't') goto yy428;
		goto yy71;
yy389:
		yych = *++YYCURSOR;
		if(yych <= 'S') {
			if(yych <= 'F') {
				if(yych == 'C') goto yy411;
				if(yych <= 'E') goto yy71;
				goto yy409;
			} else {
				if(yych == 'L') goto yy408;
				if(yych <= 'R') goto yy71;
				goto yy410;
			}
		} else {
			if(yych <= 'f') {
				if(yych == 'c') goto yy411;
				if(yych <= 'e') goto yy71;
				goto yy409;
			} else {
				if(yych <= 'l') {
					if(yych <= 'k') goto yy71;
					goto yy408;
				} else {
					if(yych == 's') goto yy410;
					goto yy71;
				}
			}
		}
yy390:
		yych = *++YYCURSOR;
		if(yych == 'S') goto yy401;
		if(yych == 's') goto yy401;
		goto yy71;
yy391:
		yych = *++YYCURSOR;
		if(yych == 'U') goto yy396;
		if(yych == 'u') goto yy396;
		goto yy71;
yy392:
		yych = *++YYCURSOR;
		if(yych == 'O') goto yy393;
		if(yych != 'o') goto yy71;
yy393:
		yych = *++YYCURSOR;
		if(yych == 'P') goto yy394;
		if(yych != 'p') goto yy71;
yy394:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy70;
		}
#line 170 "pdo_user_sql_tokenizer.re"
		{ RET(PU_DROP); }
#line 2346 "pdo_user_sql_tokenizer.c"
yy396:
		yych = *++YYCURSOR;
		if(yych == 'B') goto yy397;
		if(yych != 'b') goto yy71;
yy397:
		yych = *++YYCURSOR;
		if(yych == 'L') goto yy398;
		if(yych != 'l') goto yy71;
yy398:
		yych = *++YYCURSOR;
		if(yych == 'E') goto yy399;
		if(yych != 'e') goto yy71;
yy399:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy70;
		}
#line 229 "pdo_user_sql_tokenizer.re"
		{ RET(PU_DOUBLE); }
#line 2366 "pdo_user_sql_tokenizer.c"
yy401:
		yych = *++YYCURSOR;
		if(yych == 'T') goto yy402;
		if(yych != 't') goto yy71;
yy402:
		yych = *++YYCURSOR;
		if(yych == 'I') goto yy403;
		if(yych != 'i') goto yy71;
yy403:
		yych = *++YYCURSOR;
		if(yych == 'N') goto yy404;
		if(yych != 'n') goto yy71;
yy404:
		yych = *++YYCURSOR;
		if(yych == 'C') goto yy405;
		if(yych != 'c') goto yy71;
yy405:
		yych = *++YYCURSOR;
		if(yych == 'T') goto yy406;
		if(yych != 't') goto yy71;
yy406:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy70;
		}
#line 199 "pdo_user_sql_tokenizer.re"
		{ RET(PU_DISTINCT); }
#line 2394 "pdo_user_sql_tokenizer.c"
yy408:
		yych = *++YYCURSOR;
		if(yych == 'E') goto yy424;
		if(yych == 'e') goto yy424;
		goto yy71;
yy409:
		yych = *++YYCURSOR;
		if(yych == 'A') goto yy419;
		if(yych == 'a') goto yy419;
		goto yy71;
yy410:
		yych = *++YYCURSOR;
		if(yych == 'C') goto yy417;
		if(yych == 'c') goto yy417;
		goto yy71;
yy411:
		yych = *++YYCURSOR;
		if(yych == 'I') goto yy412;
		if(yych != 'i') goto yy71;
yy412:
		yych = *++YYCURSOR;
		if(yych == 'M') goto yy413;
		if(yych != 'm') goto yy71;
yy413:
		yych = *++YYCURSOR;
		if(yych == 'A') goto yy414;
		if(yych != 'a') goto yy71;
yy414:
		yych = *++YYCURSOR;
		if(yych == 'L') goto yy415;
		if(yych != 'l') goto yy71;
yy415:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy70;
		}
#line 231 "pdo_user_sql_tokenizer.re"
		{ RET(PU_DECIMAL); }
#line 2433 "pdo_user_sql_tokenizer.c"
yy417:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy70;
		}
#line 207 "pdo_user_sql_tokenizer.re"
		{ RET(PU_DESC); }
#line 2441 "pdo_user_sql_tokenizer.c"
yy419:
		yych = *++YYCURSOR;
		if(yych == 'U') goto yy420;
		if(yych != 'u') goto yy71;
yy420:
		yych = *++YYCURSOR;
		if(yych == 'L') goto yy421;
		if(yych != 'l') goto yy71;
yy421:
		yych = *++YYCURSOR;
		if(yych == 'T') goto yy422;
		if(yych != 't') goto yy71;
yy422:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy70;
		}
#line 184 "pdo_user_sql_tokenizer.re"
		{ RET(PU_DEFAULT); }
#line 2461 "pdo_user_sql_tokenizer.c"
yy424:
		yych = *++YYCURSOR;
		if(yych == 'T') goto yy425;
		if(yych != 't') goto yy71;
yy425:
		yych = *++YYCURSOR;
		if(yych == 'E') goto yy426;
		if(yych != 'e') goto yy71;
yy426:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy70;
		}
#line 163 "pdo_user_sql_tokenizer.re"
		{ RET(PU_DELETE); }
#line 2477 "pdo_user_sql_tokenizer.c"
yy428:
		yych = *++YYCURSOR;
		if(yych == 'E') goto yy429;
		if(yych != 'e') goto yy71;
yy429:
		++YYCURSOR;
		if((yych = *YYCURSOR) <= '^') {
			if(yych <= '@') {
				if(yych <= '/') goto yy430;
				if(yych <= '9') goto yy70;
			} else {
				if(yych == 'T') goto yy431;
				if(yych <= 'Z') goto yy70;
			}
		} else {
			if(yych <= 's') {
				if(yych != '`') goto yy70;
			} else {
				if(yych <= 't') goto yy431;
				if(yych <= 'z') goto yy70;
				if(yych >= 0x80) goto yy70;
			}
		}
yy430:
#line 224 "pdo_user_sql_tokenizer.re"
		{ RET(PU_DATE); }
#line 2504 "pdo_user_sql_tokenizer.c"
yy431:
		yych = *++YYCURSOR;
		if(yych == 'I') goto yy432;
		if(yych != 'i') goto yy71;
yy432:
		yych = *++YYCURSOR;
		if(yych == 'M') goto yy433;
		if(yych != 'm') goto yy71;
yy433:
		yych = *++YYCURSOR;
		if(yych == 'E') goto yy434;
		if(yych != 'e') goto yy71;
yy434:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy70;
		}
#line 223 "pdo_user_sql_tokenizer.re"
		{ RET(PU_DATETIME); }
#line 2524 "pdo_user_sql_tokenizer.c"
yy436:
		yych = *++YYCURSOR;
		if(yych <= 'S') {
			if(yych == 'I') goto yy443;
			if(yych <= 'R') goto yy71;
			goto yy444;
		} else {
			if(yych <= 'i') {
				if(yych <= 'h') goto yy71;
				goto yy443;
			} else {
				if(yych == 's') goto yy444;
				goto yy71;
			}
		}
yy437:
		yych = *++YYCURSOR;
		if(yych == 'D') goto yy438;
		if(yych != 'd') goto yy71;
yy438:
		yych = *++YYCURSOR;
		if(yych == 'A') goto yy439;
		if(yych != 'a') goto yy71;
yy439:
		yych = *++YYCURSOR;
		if(yych == 'T') goto yy440;
		if(yych != 't') goto yy71;
yy440:
		yych = *++YYCURSOR;
		if(yych == 'E') goto yy441;
		if(yych != 'e') goto yy71;
yy441:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy70;
		}
#line 162 "pdo_user_sql_tokenizer.re"
		{ RET(PU_UPDATE); }
#line 2563 "pdo_user_sql_tokenizer.c"
yy443:
		yych = *++YYCURSOR;
		if(yych == 'Q') goto yy451;
		if(yych == 'q') goto yy451;
		goto yy71;
yy444:
		yych = *++YYCURSOR;
		if(yych == 'I') goto yy445;
		if(yych != 'i') goto yy71;
yy445:
		yych = *++YYCURSOR;
		if(yych == 'G') goto yy446;
		if(yych != 'g') goto yy71;
yy446:
		yych = *++YYCURSOR;
		if(yych == 'N') goto yy447;
		if(yych != 'n') goto yy71;
yy447:
		yych = *++YYCURSOR;
		if(yych == 'E') goto yy448;
		if(yych != 'e') goto yy71;
yy448:
		yych = *++YYCURSOR;
		if(yych == 'D') goto yy449;
		if(yych != 'd') goto yy71;
yy449:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy70;
		}
#line 208 "pdo_user_sql_tokenizer.re"
		{ RET(PU_UNSIGNED); }
#line 2596 "pdo_user_sql_tokenizer.c"
yy451:
		yych = *++YYCURSOR;
		if(yych == 'U') goto yy452;
		if(yych != 'u') goto yy71;
yy452:
		yych = *++YYCURSOR;
		if(yych == 'E') goto yy453;
		if(yych != 'e') goto yy71;
yy453:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy70;
		}
#line 194 "pdo_user_sql_tokenizer.re"
		{ RET(PU_UNIQUE); }
#line 2612 "pdo_user_sql_tokenizer.c"
yy455:
		yych = *++YYCURSOR;
		if(yych == 'E') goto yy475;
		if(yych == 'e') goto yy475;
		goto yy71;
yy456:
		yych = *++YYCURSOR;
		if(yych <= 'T') {
			if(yych <= 'N') {
				if(yych <= 'M') goto yy71;
				goto yy460;
			} else {
				if(yych <= 'R') goto yy71;
				if(yych >= 'T') goto yy458;
			}
		} else {
			if(yych <= 'r') {
				if(yych == 'n') goto yy460;
				goto yy71;
			} else {
				if(yych <= 's') goto yy457;
				if(yych <= 't') goto yy458;
				goto yy71;
			}
		}
yy457:
		yych = *++YYCURSOR;
		if(yych == 'E') goto yy471;
		if(yych == 'e') goto yy471;
		goto yy71;
yy458:
		++YYCURSOR;
		if((yych = *YYCURSOR) <= '^') {
			if(yych <= 'D') {
				if(yych <= '/') goto yy459;
				if(yych <= '9') goto yy70;
				if(yych >= 'A') goto yy70;
			} else {
				if(yych <= 'N') {
					if(yych <= 'E') goto yy464;
					goto yy70;
				} else {
					if(yych <= 'O') goto yy465;
					if(yych <= 'Z') goto yy70;
				}
			}
		} else {
			if(yych <= 'e') {
				if(yych == '`') goto yy459;
				if(yych <= 'd') goto yy70;
				goto yy464;
			} else {
				if(yych <= 'o') {
					if(yych <= 'n') goto yy70;
					goto yy465;
				} else {
					if(yych <= 'z') goto yy70;
					if(yych >= 0x80) goto yy70;
				}
			}
		}
yy459:
#line 213 "pdo_user_sql_tokenizer.re"
		{ RET(PU_INT); }
#line 2677 "pdo_user_sql_tokenizer.c"
yy460:
		yych = *++YYCURSOR;
		if(yych == 'E') goto yy461;
		if(yych != 'e') goto yy71;
yy461:
		yych = *++YYCURSOR;
		if(yych == 'R') goto yy462;
		if(yych != 'r') goto yy71;
yy462:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy70;
		}
#line 200 "pdo_user_sql_tokenizer.re"
		{ RET(PU_INNER); }
#line 2693 "pdo_user_sql_tokenizer.c"
yy464:
		yych = *++YYCURSOR;
		if(yych == 'G') goto yy467;
		if(yych == 'g') goto yy467;
		goto yy71;
yy465:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy70;
		}
#line 182 "pdo_user_sql_tokenizer.re"
		{ RET(PU_INTO); }
#line 2706 "pdo_user_sql_tokenizer.c"
yy467:
		yych = *++YYCURSOR;
		if(yych == 'E') goto yy468;
		if(yych != 'e') goto yy71;
yy468:
		yych = *++YYCURSOR;
		if(yych == 'R') goto yy469;
		if(yych != 'r') goto yy71;
yy469:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy70;
		}
#line 214 "pdo_user_sql_tokenizer.re"
		{ RET(PU_INTEGER); }
#line 2722 "pdo_user_sql_tokenizer.c"
yy471:
		yych = *++YYCURSOR;
		if(yych == 'R') goto yy472;
		if(yych != 'r') goto yy71;
yy472:
		yych = *++YYCURSOR;
		if(yych == 'T') goto yy473;
		if(yych != 't') goto yy71;
yy473:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy70;
		}
#line 161 "pdo_user_sql_tokenizer.re"
		{ RET(PU_INSERT); }
#line 2738 "pdo_user_sql_tokenizer.c"
yy475:
		yych = *++YYCURSOR;
		if(yych == 'N') goto yy476;
		if(yych != 'n') goto yy71;
yy476:
		yych = *++YYCURSOR;
		if(yych == 'T') goto yy477;
		if(yych != 't') goto yy71;
yy477:
		yych = *++YYCURSOR;
		if(yych == 'I') goto yy478;
		if(yych != 'i') goto yy71;
yy478:
		yych = *++YYCURSOR;
		if(yych == 'F') goto yy479;
		if(yych != 'f') goto yy71;
yy479:
		yych = *++YYCURSOR;
		if(yych == 'I') goto yy480;
		if(yych != 'i') goto yy71;
yy480:
		yych = *++YYCURSOR;
		if(yych == 'E') goto yy481;
		if(yych != 'e') goto yy71;
yy481:
		yych = *++YYCURSOR;
		if(yych == 'D') goto yy482;
		if(yych != 'd') goto yy71;
yy482:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy70;
		}
#line 198 "pdo_user_sql_tokenizer.re"
		{ RET(PU_IDENTIFIED); }
#line 2774 "pdo_user_sql_tokenizer.c"
yy484:
		yych = *++YYCURSOR;
		if(yych <= 'T') {
			if(yych == 'L') goto yy495;
			if(yych <= 'S') goto yy71;
			goto yy496;
		} else {
			if(yych <= 'l') {
				if(yych <= 'k') goto yy71;
				goto yy495;
			} else {
				if(yych == 't') goto yy496;
				goto yy71;
			}
		}
yy485:
		yych = *++YYCURSOR;
		if(yych == 'A') goto yy488;
		if(yych == 'a') goto yy488;
		goto yy71;
yy486:
		++YYCURSOR;
		if(YYLIMIT == YYCURSOR) YYFILL(1);
		yych = *YYCURSOR;
		if(yybm[0+yych] & 128) {
			goto yy486;
		}
		if(yych <= '9') {
			if(yych <= 0x0D) {
				if(yych <= 0x08) goto yy6;
				if(yych <= 0x0A) goto yy64;
				if(yych <= 0x0C) goto yy6;
				goto yy64;
			} else {
				if(yych == ' ') goto yy64;
				if(yych <= '/') goto yy6;
				goto yy70;
			}
		} else {
			if(yych <= '_') {
				if(yych <= '@') goto yy6;
				if(yych <= 'Z') goto yy70;
				if(yych <= '^') goto yy6;
				goto yy70;
			} else {
				if(yych <= '`') goto yy6;
				if(yych <= 'z') goto yy70;
				if(yych <= 0x7F) goto yy6;
				goto yy70;
			}
		}
yy488:
		yych = *++YYCURSOR;
		if(yych == 'L') goto yy489;
		if(yych != 'l') goto yy71;
yy489:
		yych = *++YYCURSOR;
		if(yych == 'L') goto yy490;
		if(yych != 'l') goto yy71;
yy490:
		yych = *++YYCURSOR;
		if(yych == 'I') goto yy491;
		if(yych != 'i') goto yy71;
yy491:
		yych = *++YYCURSOR;
		if(yych == 'N') goto yy492;
		if(yych != 'n') goto yy71;
yy492:
		yych = *++YYCURSOR;
		if(yych == 'T') goto yy493;
		if(yych != 't') goto yy71;
yy493:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy70;
		}
#line 216 "pdo_user_sql_tokenizer.re"
		{ RET(PU_SMALLINT); }
#line 2853 "pdo_user_sql_tokenizer.c"
yy495:
		yych = *++YYCURSOR;
		if(yych == 'E') goto yy498;
		if(yych == 'e') goto yy498;
		goto yy71;
yy496:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy70;
		}
#line 240 "pdo_user_sql_tokenizer.re"
		{ RET(PU_SET); }
#line 2866 "pdo_user_sql_tokenizer.c"
yy498:
		yych = *++YYCURSOR;
		if(yych == 'C') goto yy499;
		if(yych != 'c') goto yy71;
yy499:
		yych = *++YYCURSOR;
		if(yych == 'T') goto yy500;
		if(yych != 't') goto yy71;
yy500:
		++YYCURSOR;
		if(yybm[0+(yych = *YYCURSOR)] & 32) {
			goto yy70;
		}
#line 160 "pdo_user_sql_tokenizer.re"
		{ RET(PU_SELECT); }
#line 2882 "pdo_user_sql_tokenizer.c"
	}
}
#line 278 "pdo_user_sql_tokenizer.re"

}

#define PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(v)	{ v, #v },
 
php_pdo_user_sql_token_label php_pdo_user_sql_token_labels[] = {
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_END)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_LABEL)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_STRING)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_WHITESPACE)

	/* Verbs */
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_SELECT)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_INSERT)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_UPDATE)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_DELETE)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_CREATE)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_RENAME)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_ALTER)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_GRANT)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_REVOKE)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_ADD)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_DROP)

	/* Nouns */
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_TABLE)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_VIEW)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_COLUMN)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_KEY)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_NULL)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_AUTO_INCREMENT)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_HNUM)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_LNUM)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_ALL)

	/* Prepositions */
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_INTO)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_FROM)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(	PU_DEFAULT)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_WHERE)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_GROUP)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_LIMIT)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_HAVING)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_ORDER)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_BY)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_AS)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_TO)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_VALUES)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_UNIQUE)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_PRIMARY)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_BEFORE)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_AFTER)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_IDENTIFIED)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_DISTINCT)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_INNER)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_OUTER)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_LEFT)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_RIGHT)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_JOIN)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_ON)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_ASC)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_DESC)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_UNSIGNED)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_ZEROFILL)

	/* SQL Types */
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_BIT)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_INT)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_INTEGER)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_TINYINT)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_SMALLINT)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_MEDIUMINT)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_BIGINT)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_CHAR)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_VARCHAR)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_BINARY)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_VARBINARY)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_DATETIME)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_DATE)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_TIME)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_TIMESTAMP)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_YEAR)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_REAL)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_DECIMAL)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_DOUBLE)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_FLOAT)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_TEXT)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_TINYTEXT)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_MEDIUMTEXT)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_LONGTEXT)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_BLOB)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_TINYBLOB)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_MEDIUMBLOB)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_LONGBLOB)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_SET)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_ENUM)

	/* Logicals */
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_NOT_EQUAL) 	/* != */
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_UNEQUAL)		/* <> */
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_LESSER_EQUAL)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_GREATER_EQUAL)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_LIKE)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_RLIKE)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_NOT)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_AND)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_OR)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_XOR)

	/* Single Character Tokens */
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_PLUS)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_MINUS)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_MUL)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_DIV)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_MOD)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_LPAREN)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_RPAREN)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_COMMA)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_EQUALS)
	PHP_PDO_USER_SQL_TOKEN_LABEL_ENTRY(PU_SEMICOLON)

	{ 0, NULL }
};
